using System;
using System.Linq;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Module.Admin.Attribute;
using TIG.TotalLink.Client.Module.Admin.ViewModel.Core;

namespace TIG.TotalLink.Client.Module.Admin.ViewModel.Document
{
    /// <summary>
    /// A read-only viewmodel that describes a document data model type (i.e. a model that can be used to initialize a document.)
    /// </summary>
    public class DocumentModelTypeViewModel : DataModelTypeViewModelBase
    {
        #region Private Fields

        private DocumentDataModelAttribute _documentDataModelAttribute;

        #endregion


        #region Constructors

        public DocumentModelTypeViewModel()
        {
        }

        public DocumentModelTypeViewModel(Type documentModelType)
            : base(documentModelType)
        {
            // Initialize properties
            DocumentDataModelAttribute = (DocumentDataModelAttribute)documentModelType.GetCustomAttributes(typeof(DocumentDataModelAttribute), true).Single();
        }

        #endregion


        #region Public Properties

        /// <summary>
        /// The DocumentDataModelAttribute that was applied to the Type.
        /// </summary>
        public DocumentDataModelAttribute DocumentDataModelAttribute
        {
            get { return _documentDataModelAttribute; }
            private set { SetProperty(ref _documentDataModelAttribute, value, () => DocumentDataModelAttribute); }
        }

        #endregion


        #region Overrides

        public override string Name
        {
            get { return DocumentDataModelAttribute != null ? DocumentDataModelAttribute.Name : null; }
        }

        public override string Description
        {
            get { return DocumentDataModelAttribute != null ? DocumentDataModelAttribute.Description : null; }
        }

        public override string Category
        {
            get { return "Document Model"; }
        }

        #endregion


        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<DocumentModelTypeViewModel> builder)
        {
            builder.Property(p => p.DocumentDataModelAttribute).NotAutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<DocumentModelTypeViewModel> builder)
        {
        }

        #endregion
    }
}
