using System;
using System.Linq;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.ViewModel;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Module.Admin.Attribute;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;

namespace TIG.TotalLink.Client.Module.Admin.ViewModel.Document
{
    /// <summary>
    /// A read-only viewmodel that describes a widget (i.e. view that can be placed within a panel.)
    /// </summary>
    [DisplayField("Name")]
    public class WidgetViewModel : LocalDataObjectBase
    {
        #region Private Fields

        private Type _widgetType;
        private WidgetAttribute _widgetAttribute;
        private string _module;

        #endregion


        #region Constructors

        public WidgetViewModel()
        {
        }

        public WidgetViewModel(Type widgetType)
            : this()
        {
            // Initialize widget properties
            WidgetType = widgetType;
            WidgetAttribute = (WidgetAttribute)widgetType.GetCustomAttributes(typeof(WidgetAttribute), true).Single();

            var moduleNameParts = WidgetType.Assembly.GetName().Name.Split('.');
            Module = moduleNameParts[moduleNameParts.Length - 1];
        }

        public WidgetViewModel(WidgetAttribute widgetAttribute, string module)
            : this()
        {
            // Initialize widget properties
            WidgetAttribute = widgetAttribute;
            Module = module;
        }

        #endregion


        #region Public Properties

        /// <summary>
        /// The type of the widget.
        /// </summary>
        public Type WidgetType
        {
            get { return _widgetType; }
            set { SetProperty(ref _widgetType, value, () => WidgetType); }
        }

        /// <summary>
        /// The WidgetAttribute that was applied to the WidgetType.
        /// </summary>
        public WidgetAttribute WidgetAttribute
        {
            get { return _widgetAttribute; }
            set { SetProperty(ref _widgetAttribute, value, () => WidgetAttribute); }
        }

        /// <summary>
        /// Name of the module that the widget is contained in.
        /// </summary>
        public string Module
        {
            get { return _module; }
            set { SetProperty(ref _module, value, () => Module); }
        }

        /// <summary>
        /// Category that the widget belongs to.
        /// </summary>
        public string Category
        {
            get { return WidgetAttribute != null ? WidgetAttribute.Category : null; }
        }

        /// <summary>
        /// Name of the widget.
        /// </summary>
        public string Name
        {
            get { return WidgetAttribute != null ? WidgetAttribute.Name : null; }
        }

        /// <summary>
        /// Short description of the widget.
        /// </summary>
        public string Description
        {
            get { return WidgetAttribute != null ? WidgetAttribute.Description : null; }
        }

        /// <summary>
        /// Name of the type of the widget.
        /// </summary>
        public string TypeName
        {
            get { return WidgetType != null ? WidgetType.FullName : null; }
        }

        /// <summary>
        /// Name of the view for this widget.
        /// </summary>
        public string ViewName
        {
            get { return WidgetType != null ? WidgetType.Name : null; }
        }

        #endregion


        #region Overrides

        public override string ToString()
        {
            return Name;
        }

        #endregion


        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<WidgetViewModel> builder)
        {
            builder.DataFormLayout()
                .ContainsProperty(p => p.Name)
                .ContainsProperty(p => p.Category)
                .ContainsProperty(p => p.Description)
                .ContainsProperty(p => p.Module)
                .ContainsProperty(p => p.ViewName)
                .ContainsProperty(p => p.TypeName);

            builder.TableLayout().Group("")
                .ContainsProperty(p => p.Name)
                .ContainsProperty(p => p.Category)
                .ContainsProperty(p => p.Description)
                .ContainsProperty(p => p.Module)
                .ContainsProperty(p => p.ViewName)
                .ContainsProperty(p => p.TypeName);

            builder.Property(p => p.Name).ReadOnly();
            builder.Property(p => p.Category).ReadOnly();
            builder.Property(p => p.Description).ReadOnly();
            builder.Property(p => p.Module).ReadOnly();
            builder.Property(p => p.TypeName).ReadOnly();

            builder.Property(p => p.WidgetType).NotAutoGenerated();
            builder.Property(p => p.WidgetAttribute).NotAutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<WidgetViewModel> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Name);

            builder.Property(p => p.Name).ColumnWidth(150);
        }

        #endregion
    }
}
