//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Sale
{

    public partial class DeliveryStatus : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        string _Name;
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        bool _InTransit;
        public bool InTransit
        {
            get { return _InTransit; }
            set { SetPropertyValue<bool>("InTransit", ref _InTransit, value); }
        }
        bool _IsStockAdjusted;
        public bool IsStockAdjusted
        {
            get { return _IsStockAdjusted; }
            set { SetPropertyValue<bool>("IsStockAdjusted", ref _IsStockAdjusted, value); }
        }
        bool _CanBePicked;
        public bool CanBePicked
        {
            get { return _CanBePicked; }
            set { SetPropertyValue<bool>("CanBePicked", ref _CanBePicked, value); }
        }
        bool _CanBeDispatched;
        public bool CanBeDispatched
        {
            get { return _CanBeDispatched; }
            set { SetPropertyValue<bool>("CanBeDispatched", ref _CanBeDispatched, value); }
        }
        [Association(@"DeliveryReferencesDeliveryStatus", typeof(Delivery))]
        public XPCollection<Delivery> Deliveries { get { return GetCollection<Delivery>("Deliveries"); } }
    }

}
