//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Sale
{

    public partial class Delivery : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        long _Reference;
        public long Reference
        {
            get { return _Reference; }
            set { SetPropertyValue<long>("Reference", ref _Reference, value); }
        }
        Invoice _Invoice;
        [ExplicitLoading(1)]
        [Association(@"DeliveryReferencesInvoice")]
        public Invoice Invoice
        {
            get { return _Invoice; }
            set { SetPropertyValue<Invoice>("Invoice", ref _Invoice, value); }
        }
        SalesOrderRelease _SalesOrderRelease;
        [ExplicitLoading(1)]
        [Association(@"DeliveryReferencesSalesOrderRelease")]
        public SalesOrderRelease SalesOrderRelease
        {
            get { return _SalesOrderRelease; }
            set { SetPropertyValue<SalesOrderRelease>("SalesOrderRelease", ref _SalesOrderRelease, value); }
        }
        TIG.TotalLink.Shared.DataModel.Crm.Contact _Contact;
        [ExplicitLoading(1)]
        [TIG.TotalLink.Shared.DataModel.Core.Attribute.RuntimeAssociation("DeliveryReferencesContact", "Deliveries")]
        public TIG.TotalLink.Shared.DataModel.Crm.Contact Contact
        {
            get { return _Contact; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Crm.Contact>("Contact", ref _Contact, value); }
        }
        DeliveryStatus _Status;
        [ExplicitLoading(1)]
        [Association(@"DeliveryReferencesDeliveryStatus")]
        public DeliveryStatus Status
        {
            get { return _Status; }
            set { SetPropertyValue<DeliveryStatus>("Status", ref _Status, value); }
        }
        string _ConsignmentNote;
        [Size(255)]
        public string ConsignmentNote
        {
            get { return _ConsignmentNote; }
            set { SetPropertyValue<string>("ConsignmentNote", ref _ConsignmentNote, value); }
        }
        [DevExpress.Xpo.Aggregated]
        [Association(@"DeliveryItemReferencesDelivery", typeof(DeliveryItem))]
        public XPCollection<DeliveryItem> DeliveryItems { get { return GetCollection<DeliveryItem>("DeliveryItems"); } }
    }

}
