//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Sale
{

    public partial class DeliveryItem : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        TIG.TotalLink.Shared.DataModel.Inventory.Sku _Sku;
        [ExplicitLoading(1)]
        [TIG.TotalLink.Shared.DataModel.Core.Attribute.RuntimeAssociation("DeliveryItemReferencesSku", "DeliveryItems")]
        public TIG.TotalLink.Shared.DataModel.Inventory.Sku Sku
        {
            get { return _Sku; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Inventory.Sku>("Sku", ref _Sku, value); }
        }
        Delivery _Delivery;
        [ExplicitLoading(1)]
        [Association(@"DeliveryItemReferencesDelivery")]
        public Delivery Delivery
        {
            get { return _Delivery; }
            set { SetPropertyValue<Delivery>("Delivery", ref _Delivery, value); }
        }
        SalesOrderReleaseItem _SalesOrderReleaseItem;
        [ExplicitLoading(1)]
        [Association(@"DeliveryItemReferencesSalesOrderReleaseItem")]
        public SalesOrderReleaseItem SalesOrderReleaseItem
        {
            get { return _SalesOrderReleaseItem; }
            set { SetPropertyValue<SalesOrderReleaseItem>("SalesOrderReleaseItem", ref _SalesOrderReleaseItem, value); }
        }
        int _QuantityReleased;
        public int QuantityReleased
        {
            get { return _QuantityReleased; }
            set { SetPropertyValue<int>("QuantityReleased", ref _QuantityReleased, value); }
        }
        decimal _CostPrice;
        public decimal CostPrice
        {
            get { return _CostPrice; }
            set { SetPropertyValue<decimal>("CostPrice", ref _CostPrice, value); }
        }
        decimal _SellPrice;
        public decimal SellPrice
        {
            get { return _SellPrice; }
            set { SetPropertyValue<decimal>("SellPrice", ref _SellPrice, value); }
        }
        InvoiceItem _InvoiceItem;
        [ExplicitLoading(1)]
        [Association(@"DeliveryItemReferencesInvoiceItem")]
        public InvoiceItem InvoiceItem
        {
            get { return _InvoiceItem; }
            set { SetPropertyValue<InvoiceItem>("InvoiceItem", ref _InvoiceItem, value); }
        }
        [PersistentAlias("Iif(PickItems.Exists, PickItems.Sum(Quantity), 0)")]
        public int Quantity
        {
            get { return (int)(EvaluateAlias("Quantity")); }
        }
        [DevExpress.Xpo.Aggregated]
        [Association(@"PickItemReferencesDeliveryItem", typeof(PickItem))]
        public XPCollection<PickItem> PickItems { get { return GetCollection<PickItem>("PickItems"); } }
    }

}
