//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Sale
{

    public partial class EnquiryItem : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        TIG.TotalLink.Shared.DataModel.Inventory.Sku _Sku;
        [ExplicitLoading(1)]
        public TIG.TotalLink.Shared.DataModel.Inventory.Sku Sku
        {
            get { return _Sku; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Inventory.Sku>("Sku", ref _Sku, value); }
        }
        int _Quantity;
        public int Quantity
        {
            get { return _Quantity; }
            set { SetPropertyValue<int>("Quantity", ref _Quantity, value); }
        }
        Enquiry _Enquiry;
        [ExplicitLoading(1)]
        [Association(@"EnquiryItemReferencesEnquiry")]
        public Enquiry Enquiry
        {
            get { return _Enquiry; }
            set { SetPropertyValue<Enquiry>("Enquiry", ref _Enquiry, value); }
        }
        [Association(@"QuoteItemReferencesEnquiryItem", typeof(QuoteItem))]
        public XPCollection<QuoteItem> QuoteItems { get { return GetCollection<QuoteItem>("QuoteItems"); } }
    }

}
