//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Sale
{

    public partial class Enquiry : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        long _Reference;
        public long Reference
        {
            get { return _Reference; }
            set { SetPropertyValue<long>("Reference", ref _Reference, value); }
        }
        EnquiryType _EnquiryType;
        [ExplicitLoading(1)]
        [Association(@"EnquiryReferencesEnquiryType")]
        public EnquiryType EnquiryType
        {
            get { return _EnquiryType; }
            set { SetPropertyValue<EnquiryType>("EnquiryType", ref _EnquiryType, value); }
        }
        EmployeeRange _NumberOfEmployees;
        [ExplicitLoading(1)]
        [Association(@"EnquiryReferencesEmployeeRange")]
        public EmployeeRange NumberOfEmployees
        {
            get { return _NumberOfEmployees; }
            set { SetPropertyValue<EmployeeRange>("NumberOfEmployees", ref _NumberOfEmployees, value); }
        }
        string _CompanyName;
        public string CompanyName
        {
            get { return _CompanyName; }
            set { SetPropertyValue<string>("CompanyName", ref _CompanyName, value); }
        }
        string _Name;
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        TIG.TotalLink.Shared.DataModel.Admin.Country _Country;
        [ExplicitLoading(1)]
        [TIG.TotalLink.Shared.DataModel.Core.Attribute.RuntimeAssociation("EnquiryReferencesCountry", "Enquiries")]
        public TIG.TotalLink.Shared.DataModel.Admin.Country Country
        {
            get { return _Country; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Admin.Country>("Country", ref _Country, value); }
        }
        TIG.TotalLink.Shared.DataModel.Admin.State _State;
        [ExplicitLoading(1)]
        [TIG.TotalLink.Shared.DataModel.Core.Attribute.RuntimeAssociation("EnquiryReferencesState", "Enquiries")]
        public TIG.TotalLink.Shared.DataModel.Admin.State State
        {
            get { return _State; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Admin.State>("State", ref _State, value); }
        }
        bool _AllowPhoneContact;
        public bool AllowPhoneContact
        {
            get { return _AllowPhoneContact; }
            set { SetPropertyValue<bool>("AllowPhoneContact", ref _AllowPhoneContact, value); }
        }
        bool _AllowEmailContact;
        public bool AllowEmailContact
        {
            get { return _AllowEmailContact; }
            set { SetPropertyValue<bool>("AllowEmailContact", ref _AllowEmailContact, value); }
        }
        string _EmailAddress;
        [Size(255)]
        public string EmailAddress
        {
            get { return _EmailAddress; }
            set { SetPropertyValue<string>("EmailAddress", ref _EmailAddress, value); }
        }
        string _PhoneNumber;
        [Size(30)]
        public string PhoneNumber
        {
            get { return _PhoneNumber; }
            set { SetPropertyValue<string>("PhoneNumber", ref _PhoneNumber, value); }
        }
        string _Details;
        [Size(SizeAttribute.Unlimited)]
        public string Details
        {
            get { return _Details; }
            set { SetPropertyValue<string>("Details", ref _Details, value); }
        }
        bool _BrandingRequired;
        public bool BrandingRequired
        {
            get { return _BrandingRequired; }
            set { SetPropertyValue<bool>("BrandingRequired", ref _BrandingRequired, value); }
        }
        int _BrandingLogoCount;
        public int BrandingLogoCount
        {
            get { return _BrandingLogoCount; }
            set { SetPropertyValue<int>("BrandingLogoCount", ref _BrandingLogoCount, value); }
        }
        string _BrandingType;
        public string BrandingType
        {
            get { return _BrandingType; }
            set { SetPropertyValue<string>("BrandingType", ref _BrandingType, value); }
        }
        FindMethod _FindMethod;
        [ExplicitLoading(1)]
        [Association(@"EnquiryReferencesFindMethod")]
        public FindMethod FindMethod
        {
            get { return _FindMethod; }
            set { SetPropertyValue<FindMethod>("FindMethod", ref _FindMethod, value); }
        }
        bool _AllowMarketing;
        public bool AllowMarketing
        {
            get { return _AllowMarketing; }
            set { SetPropertyValue<bool>("AllowMarketing", ref _AllowMarketing, value); }
        }
        EnquiryStatus _Status;
        [ExplicitLoading(1)]
        [Association(@"EnquiryReferencesEnquiryStatus")]
        public EnquiryStatus Status
        {
            get { return _Status; }
            set { SetPropertyValue<EnquiryStatus>("Status", ref _Status, value); }
        }
        [Association(@"EnquiryItemReferencesEnquiry", typeof(EnquiryItem))]
        public XPCollection<EnquiryItem> EnquiryItems { get { return GetCollection<EnquiryItem>("EnquiryItems"); } }
        [Association(@"QuoteReferencesEnquiry", typeof(Quote))]
        public XPCollection<Quote> Quotes { get { return GetCollection<Quote>("Quotes"); } }
    }

}
