//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Sale
{

    public partial class Invoice : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        long _Reference;
        public long Reference
        {
            get { return _Reference; }
            set { SetPropertyValue<long>("Reference", ref _Reference, value); }
        }
        TIG.TotalLink.Shared.DataModel.Crm.Contact _Contact;
        [ExplicitLoading(1)]
        [TIG.TotalLink.Shared.DataModel.Core.Attribute.RuntimeAssociation("InvoiceReferencesContact", "Invoices")]
        public TIG.TotalLink.Shared.DataModel.Crm.Contact Contact
        {
            get { return _Contact; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Crm.Contact>("Contact", ref _Contact, value); }
        }
        SalesOrder _SalesOrder;
        [ExplicitLoading(1)]
        [Association(@"InvoiceReferencesSalesOrder")]
        public SalesOrder SalesOrder
        {
            get { return _SalesOrder; }
            set { SetPropertyValue<SalesOrder>("SalesOrder", ref _SalesOrder, value); }
        }
        InvoiceStatus _Status;
        [ExplicitLoading(1)]
        [Association(@"InvoiceReferencesInvoiceStatus")]
        public InvoiceStatus Status
        {
            get { return _Status; }
            set { SetPropertyValue<InvoiceStatus>("Status", ref _Status, value); }
        }
        [DevExpress.Xpo.Aggregated]
        [Association(@"InvoiceItemReferencesInvoice", typeof(InvoiceItem))]
        public XPCollection<InvoiceItem> InvoiceItems { get { return GetCollection<InvoiceItem>("InvoiceItems"); } }
        [Association(@"DeliveryReferencesInvoice", typeof(Delivery))]
        public XPCollection<Delivery> Deliveries { get { return GetCollection<Delivery>("Deliveries"); } }
    }

}
