//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Sale
{

    public partial class InvoiceItem : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        TIG.TotalLink.Shared.DataModel.Inventory.Sku _Sku;
        [ExplicitLoading(1)]
        [TIG.TotalLink.Shared.DataModel.Core.Attribute.RuntimeAssociation("InvoiceItemReferencesSku", "InvoiceItems")]
        public TIG.TotalLink.Shared.DataModel.Inventory.Sku Sku
        {
            get { return _Sku; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Inventory.Sku>("Sku", ref _Sku, value); }
        }
        int _Quantity;
        public int Quantity
        {
            get { return _Quantity; }
            set { SetPropertyValue<int>("Quantity", ref _Quantity, value); }
        }
        decimal _CostPrice;
        public decimal CostPrice
        {
            get { return _CostPrice; }
            set { SetPropertyValue<decimal>("CostPrice", ref _CostPrice, value); }
        }
        decimal _SellPrice;
        public decimal SellPrice
        {
            get { return _SellPrice; }
            set { SetPropertyValue<decimal>("SellPrice", ref _SellPrice, value); }
        }
        Invoice _Invoice;
        [ExplicitLoading(1)]
        [Association(@"InvoiceItemReferencesInvoice")]
        public Invoice Invoice
        {
            get { return _Invoice; }
            set { SetPropertyValue<Invoice>("Invoice", ref _Invoice, value); }
        }
        SalesOrderItem _SalesOrderItem;
        [ExplicitLoading(1)]
        [Association(@"InvoiceItemReferencesSalesOrderItem")]
        public SalesOrderItem SalesOrderItem
        {
            get { return _SalesOrderItem; }
            set { SetPropertyValue<SalesOrderItem>("SalesOrderItem", ref _SalesOrderItem, value); }
        }
        [Association(@"DeliveryItemReferencesInvoiceItem", typeof(DeliveryItem))]
        public XPCollection<DeliveryItem> DeliveryItems { get { return GetCollection<DeliveryItem>("DeliveryItems"); } }
    }

}
