//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Sale
{

    public partial class QuoteItem : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        TIG.TotalLink.Shared.DataModel.Inventory.Sku _Sku;
        [ExplicitLoading(1)]
        [TIG.TotalLink.Shared.DataModel.Core.Attribute.RuntimeAssociation("QuoteItemReferencesSku", "QuoteItems")]
        public TIG.TotalLink.Shared.DataModel.Inventory.Sku Sku
        {
            get { return _Sku; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Inventory.Sku>("Sku", ref _Sku, value); }
        }
        int _Quantity;
        public int Quantity
        {
            get { return _Quantity; }
            set { SetPropertyValue<int>("Quantity", ref _Quantity, value); }
        }
        decimal _CostPrice;
        public decimal CostPrice
        {
            get { return _CostPrice; }
            set { SetPropertyValue<decimal>("CostPrice", ref _CostPrice, value); }
        }
        decimal _SellPrice;
        public decimal SellPrice
        {
            get { return _SellPrice; }
            set { SetPropertyValue<decimal>("SellPrice", ref _SellPrice, value); }
        }
        QuoteVersion _QuoteVersion;
        [ExplicitLoading(1)]
        [Association(@"QuoteItemReferencesQuoteVersion")]
        public QuoteVersion QuoteVersion
        {
            get { return _QuoteVersion; }
            set { SetPropertyValue<QuoteVersion>("QuoteVersion", ref _QuoteVersion, value); }
        }
        EnquiryItem _EnquiryItem;
        [ExplicitLoading(1)]
        [Association(@"QuoteItemReferencesEnquiryItem")]
        public EnquiryItem EnquiryItem
        {
            get { return _EnquiryItem; }
            set { SetPropertyValue<EnquiryItem>("EnquiryItem", ref _EnquiryItem, value); }
        }
        [PersistentAlias("SellPrice * Quantity")]
        public decimal TotalSellPrice
        {
            get { return (decimal)(EvaluateAlias("TotalSellPrice")); }
        }
        [Association(@"SalesOrderItemReferencesQuoteItem", typeof(SalesOrderItem))]
        public XPCollection<SalesOrderItem> SalesOrderItems { get { return GetCollection<SalesOrderItem>("SalesOrderItems"); } }
    }

}
