//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Sale
{

    public partial class QuoteVersion : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        int _Version;
        public int Version
        {
            get { return _Version; }
            set { SetPropertyValue<int>("Version", ref _Version, value); }
        }
        Quote _Quote;
        [ExplicitLoading(1)]
        [Association(@"QuoteVersionReferencesQuote")]
        public Quote Quote
        {
            get { return _Quote; }
            set { SetPropertyValue<Quote>("Quote", ref _Quote, value); }
        }
        [PersistentAlias("Iif(QuoteItems.Exists,QuoteItems.Sum(Quantity),0)")]
        public int TotalQuantity
        {
            get { return (int)(EvaluateAlias("TotalQuantity")); }
        }
        [PersistentAlias("ToDecimal(Iif(QuoteItems.Exists,QuoteItems.Sum(TotalSellPrice),0))")]
        public decimal TotalSellPrice
        {
            get { return (decimal)(EvaluateAlias("TotalSellPrice")); }
        }
        [DevExpress.Xpo.Aggregated]
        [Association(@"QuoteItemReferencesQuoteVersion", typeof(QuoteItem))]
        public XPCollection<QuoteItem> QuoteItems { get { return GetCollection<QuoteItem>("QuoteItems"); } }
        [Association(@"SalesOrderReferencesQuoteVersion", typeof(SalesOrder))]
        public XPCollection<SalesOrder> SalesOrders { get { return GetCollection<SalesOrder>("SalesOrders"); } }
    }

}
