//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Sale
{

    public partial class Quote : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        long _Reference;
        public long Reference
        {
            get { return _Reference; }
            set { SetPropertyValue<long>("Reference", ref _Reference, value); }
        }
        TIG.TotalLink.Shared.DataModel.Crm.Contact _Contact;
        [ExplicitLoading(1)]
        [TIG.TotalLink.Shared.DataModel.Core.Attribute.RuntimeAssociation("QuoteReferencesContact", "Quotes")]
        public TIG.TotalLink.Shared.DataModel.Crm.Contact Contact
        {
            get { return _Contact; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Crm.Contact>("Contact", ref _Contact, value); }
        }
        Enquiry _Enquiry;
        [ExplicitLoading(1)]
        [Association(@"QuoteReferencesEnquiry")]
        public Enquiry Enquiry
        {
            get { return _Enquiry; }
            set { SetPropertyValue<Enquiry>("Enquiry", ref _Enquiry, value); }
        }
        [DevExpress.Xpo.Aggregated]
        [Association(@"QuoteVersionReferencesQuote", typeof(QuoteVersion))]
        public XPCollection<QuoteVersion> QuoteVersions { get { return GetCollection<QuoteVersion>("QuoteVersions"); } }
    }

}
