//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Sale
{

    public partial class SalesOrderReleaseItem : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        SalesOrderRelease _SalesOrderRelease;
        [ExplicitLoading(1)]
        [Association(@"SalesOrderReleaseItemReferencesSalesOrderRelease")]
        public SalesOrderRelease SalesOrderRelease
        {
            get { return _SalesOrderRelease; }
            set { SetPropertyValue<SalesOrderRelease>("SalesOrderRelease", ref _SalesOrderRelease, value); }
        }
        SalesOrderItem _SalesOrderItem;
        [ExplicitLoading(1)]
        [Association(@"SalesOrderReleaseItemReferencesSalesOrderItem")]
        public SalesOrderItem SalesOrderItem
        {
            get { return _SalesOrderItem; }
            set { SetPropertyValue<SalesOrderItem>("SalesOrderItem", ref _SalesOrderItem, value); }
        }
        int _QuantityToRelease;
        public int QuantityToRelease
        {
            get { return _QuantityToRelease; }
            set { SetPropertyValue<int>("QuantityToRelease", ref _QuantityToRelease, value); }
        }
        [PersistentAlias("Iif(DeliveryItems.Exists, DeliveryItems.Sum(Quantity), 0)")]
        public int QuantityReleased
        {
            get { return (int)(EvaluateAlias("QuantityReleased")); }
        }
        TIG.TotalLink.Shared.DataModel.Core.Enum.Sale.SalesOrderReleaseItemStatus _Status;
        public TIG.TotalLink.Shared.DataModel.Core.Enum.Sale.SalesOrderReleaseItemStatus Status
        {
            get { return _Status; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Core.Enum.Sale.SalesOrderReleaseItemStatus>("Status", ref _Status, value); }
        }
        string _ErrorMessage;
        [Size(SizeAttribute.Unlimited)]
        public string ErrorMessage
        {
            get { return _ErrorMessage; }
            set { SetPropertyValue<string>("ErrorMessage", ref _ErrorMessage, value); }
        }
        [PersistentAlias("SalesOrderItem.SalesOrder.Reference")]
        public long SalesOrder
        {
            get { return (long)(EvaluateAlias("SalesOrder")); }
        }
        [Association(@"DeliveryItemReferencesSalesOrderReleaseItem", typeof(DeliveryItem))]
        public XPCollection<DeliveryItem> DeliveryItems { get { return GetCollection<DeliveryItem>("DeliveryItems"); } }
    }

}
