//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Sale
{

    [TIG.TotalLink.Shared.DataModel.Core.Attribute.ModifiesParent("SalesOrderRelease")]
    public partial class SalesOrderRelease_BinLocation : TIG.TotalLink.Shared.DataModel.Core.DataObjectBase
    {
        SalesOrderRelease _SalesOrderRelease;
        [Association(@"SalesOrderRelease_BinLocationReferencesSalesOrderRelease")]
        public SalesOrderRelease SalesOrderRelease
        {
            get { return _SalesOrderRelease; }
            set { SetPropertyValue<SalesOrderRelease>("SalesOrderRelease", ref _SalesOrderRelease, value); }
        }
        TIG.TotalLink.Shared.DataModel.Inventory.BinLocation _BinLocation;
        [ExplicitLoading(1)]
        [TIG.TotalLink.Shared.DataModel.Core.Attribute.RuntimeAssociation("SalesOrderRelease_BinLocationReferencesBinLocation", "SalesOrderRelease_BinLocations")]
        public TIG.TotalLink.Shared.DataModel.Inventory.BinLocation BinLocation
        {
            get { return _BinLocation; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Inventory.BinLocation>("BinLocation", ref _BinLocation, value); }
        }
    }

}
