//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Sale
{

    public partial class SalesOrderRelease : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        long _Reference;
        public long Reference
        {
            get { return _Reference; }
            set { SetPropertyValue<long>("Reference", ref _Reference, value); }
        }
        [Association(@"SalesOrderReleaseReferencesSalesOrder", typeof(SalesOrder))]
        public XPCollection<SalesOrder> SalesOrders { get { return GetCollection<SalesOrder>("SalesOrders"); } }
        [DevExpress.Xpo.Aggregated]
        [Association(@"SalesOrderReleaseItemReferencesSalesOrderRelease", typeof(SalesOrderReleaseItem))]
        public XPCollection<SalesOrderReleaseItem> SalesOrderReleaseItems { get { return GetCollection<SalesOrderReleaseItem>("SalesOrderReleaseItems"); } }
        [DevExpress.Xpo.Aggregated]
        [Association(@"SalesOrderRelease_BinLocationReferencesSalesOrderRelease", typeof(SalesOrderRelease_BinLocation))]
        public XPCollection<SalesOrderRelease_BinLocation> BinLocations { get { return GetCollection<SalesOrderRelease_BinLocation>("BinLocations"); } }
        [DevExpress.Xpo.Aggregated]
        [Association(@"SalesOrderRelease_PhysicalStockTypeReferencesSalesOrderRelease", typeof(SalesOrderRelease_PhysicalStockType))]
        public XPCollection<SalesOrderRelease_PhysicalStockType> PhysicalStockTypes { get { return GetCollection<SalesOrderRelease_PhysicalStockType>("PhysicalStockTypes"); } }
        [Association(@"DeliveryReferencesSalesOrderRelease", typeof(Delivery))]
        public XPCollection<Delivery> Deliveries { get { return GetCollection<Delivery>("Deliveries"); } }
    }

}
