//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Sale
{

    public partial class SalesOrderItem : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        TIG.TotalLink.Shared.DataModel.Inventory.Sku _Sku;
        [ExplicitLoading(1)]
        [TIG.TotalLink.Shared.DataModel.Core.Attribute.RuntimeAssociation("SalesOrderItemReferencesSku", "SalesOrderItems")]
        public TIG.TotalLink.Shared.DataModel.Inventory.Sku Sku
        {
            get { return _Sku; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Inventory.Sku>("Sku", ref _Sku, value); }
        }
        int _Quantity;
        public int Quantity
        {
            get { return _Quantity; }
            set { SetPropertyValue<int>("Quantity", ref _Quantity, value); }
        }
        int _QuantityReleased;
        public int QuantityReleased
        {
            get { return _QuantityReleased; }
            set { SetPropertyValue<int>("QuantityReleased", ref _QuantityReleased, value); }
        }
        int _QuantityCancelled;
        public int QuantityCancelled
        {
            get { return _QuantityCancelled; }
            set { SetPropertyValue<int>("QuantityCancelled", ref _QuantityCancelled, value); }
        }
        decimal _CostPrice;
        public decimal CostPrice
        {
            get { return _CostPrice; }
            set { SetPropertyValue<decimal>("CostPrice", ref _CostPrice, value); }
        }
        decimal _SellPrice;
        public decimal SellPrice
        {
            get { return _SellPrice; }
            set { SetPropertyValue<decimal>("SellPrice", ref _SellPrice, value); }
        }
        QuoteItem _QuoteItem;
        [ExplicitLoading(1)]
        [Association(@"SalesOrderItemReferencesQuoteItem")]
        public QuoteItem QuoteItem
        {
            get { return _QuoteItem; }
            set { SetPropertyValue<QuoteItem>("QuoteItem", ref _QuoteItem, value); }
        }
        SalesOrder _SalesOrder;
        [ExplicitLoading(1)]
        [Association(@"SalesOrderItemReferencesSalesOrder")]
        public SalesOrder SalesOrder
        {
            get { return _SalesOrder; }
            set { SetPropertyValue<SalesOrder>("SalesOrder", ref _SalesOrder, value); }
        }
        [PersistentAlias("SellPrice * Quantity")]
        public decimal TotalSellPrice
        {
            get { return (decimal)(EvaluateAlias("TotalSellPrice")); }
        }
        [Association(@"InvoiceItemReferencesSalesOrderItem", typeof(InvoiceItem))]
        public XPCollection<InvoiceItem> InvoiceItems { get { return GetCollection<InvoiceItem>("InvoiceItems"); } }
        [Association(@"SalesOrderReleaseItemReferencesSalesOrderItem", typeof(SalesOrderReleaseItem))]
        public XPCollection<SalesOrderReleaseItem> SalesOrderReleaseItems { get { return GetCollection<SalesOrderReleaseItem>("SalesOrderReleaseItems"); } }
    }

}
