using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.DataModel.Core.Extension;
using TIG.TotalLink.Shared.Facade.Sale;

namespace TIG.TotalLink.Shared.DataModel.Sale
{
    [FacadeType(typeof(ISaleFacade))]
    [DisplayField("Sku")]
    [EntityFilter(typeof(Delivery), "Delivery.Oid IN (?)", "Delivery IN (?)")]
    [EntityFilter(typeof(SalesOrderReleaseItem), "SalesOrderReleaseItem.Oid IN (?)", "SalesOrderReleaseItem IN (?)")]
    public partial class DeliveryItem
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<DeliveryItem> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.Delivery)
                .ContainsProperty(p => p.SalesOrderReleaseItem)
                .ContainsProperty(p => p.InvoiceItem)
                .ContainsProperty(p => p.Sku)
                .ContainsProperty(p => p.Quantity)
                .ContainsProperty(p => p.QuantityReleased)
                .ContainsProperty(p => p.CostPrice)
                .ContainsProperty(p => p.SellPrice)
                .ContainsProperty(p => p.PickItems);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.Delivery)
                    .ContainsProperty(p => p.SalesOrderReleaseItem)
                    .ContainsProperty(p => p.InvoiceItem)
                    .ContainsProperty(p => p.Sku)
                    .ContainsProperty(p => p.Quantity)
                    .ContainsProperty(p => p.QuantityReleased)
                    .ContainsProperty(p => p.CostPrice)
                    .ContainsProperty(p => p.SellPrice)
                .EndGroup()
                .Group("Pick Items")
                    .ContainsProperty(p => p.PickItems);

            builder.Property(p => p.Delivery).ReadOnly();
            builder.Property(p => p.InvoiceItem).ReadOnly();
            builder.Property(p => p.Sku).ReadOnly();
            builder.Property(p => p.Quantity).ReadOnly();
            builder.Property(p => p.QuantityReleased).ReadOnly();
            builder.Property(p => p.CostPrice).ReadOnly();
            builder.Property(p => p.SellPrice).ReadOnly();
            builder.Property(p => p.PickItems).AutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<DeliveryItem> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Delivery)
                .ContainsProperty(p => p.Sku);

            builder.Property(p => p.Sku).ColumnWidth(300);
            builder.Property(p => p.Quantity)
                .ColumnWidth(130)
                .GetEditor<SpinEditorDefinition>().MinValue = 0;
            builder.Property(p => p.QuantityReleased)
                .ColumnWidth(130);
            builder.Property(p => p.CostPrice).ReplaceEditor(new CurrencyEditorDefinition());
            builder.Property(p => p.SellPrice).ReplaceEditor(new CurrencyEditorDefinition());

            builder.GridBaseColumnEditors().Property(p => p.PickItems)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(PickItem),
                    FilterMethod = context => CriteriaOperator.Parse("DeliveryItem.Oid = ?", ((DeliveryItem)context).Oid)
                });

            builder.DataFormEditors().Property(p => p.PickItems)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(PickItem),
                    FilterMethod = context => CriteriaOperator.Parse("DeliveryItem.Oid = ?", ((DeliveryItem)context).Oid),
                    ShowToolBar = true,
                    BuildNewRowMethod = (context, session) => new PickItem(session)
                    {
                        DeliveryItem = session.GetDataObject((DeliveryItem)context)
                    }
                });
        }

        #endregion
    }
}