using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.DataModel.Core.Extension;
using TIG.TotalLink.Shared.Facade.Sale;

namespace TIG.TotalLink.Shared.DataModel.Sale
{
    [FacadeType(typeof(ISaleFacade))]
    [DisplayField("Reference")]
    [EntityFilter(typeof(SalesOrderRelease), "SalesOrderRelease.Oid IN (?)", "SalesOrderRelease IN (?)")]
    public partial class Delivery
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<Delivery> builder)
        {
            builder.TableLayout().Group("")
                    .ContainsProperty(p => p.Reference)
                    .ContainsProperty(p => p.SalesOrderRelease)
                    .ContainsProperty(p => p.Invoice)
                    .ContainsProperty(p => p.Contact)
                    .ContainsProperty(p => p.Status)
                    .ContainsProperty(p => p.ConsignmentNote)
                    .ContainsProperty(p => p.DeliveryItems);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.Reference)
                    .ContainsProperty(p => p.SalesOrderRelease)
                    .ContainsProperty(p => p.Invoice)
                    .ContainsProperty(p => p.Contact)
                    .ContainsProperty(p => p.Status)
                    .ContainsProperty(p => p.ConsignmentNote)
                .EndGroup()
                .Group("Items")
                    .ContainsProperty(p => p.DeliveryItems);

            builder.Property(p => p.Reference).ReadOnly();
            builder.Property(p => p.DeliveryItems)
                .DisplayName("Items")
                .AutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<Delivery> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Reference);

            builder.Property(p => p.Reference).GetEditor<SpinEditorDefinition>().DisplayFormat = "D0";

            builder.GridBaseColumnEditors().Property(p => p.DeliveryItems)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(DeliveryItem),
                    FilterMethod = context => CriteriaOperator.Parse("Delivery.Oid=?", ((Delivery)context).Oid)
                });

            builder.DataFormEditors().Property(p => p.DeliveryItems)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(DeliveryItem),
                    FilterMethod = context => CriteriaOperator.Parse("Delivery.Oid=?", ((Delivery)context).Oid),
                    ShowToolBar = true,
                    BuildNewRowMethod = (context, session) => new DeliveryItem(session)
                    {
                        Delivery = session.GetDataObject((Delivery)context)
                    }
                });
        }

        #endregion
    }
}