using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.Facade.Sale;

namespace TIG.TotalLink.Shared.DataModel.Sale
{
    [FacadeType(typeof(ISaleFacade))]
    [DisplayField("Sku")]
    [EntityFilter(typeof(Enquiry), "Enquiry.Oid IN (?)", "Enquiry IN (?)")]
    public partial class EnquiryItem
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<EnquiryItem> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.Enquiry)
                .ContainsProperty(p => p.Sku)
                .ContainsProperty(p => p.Quantity)
                .ContainsProperty(p => p.QuoteItems);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.Enquiry)
                    .ContainsProperty(p => p.Sku)
                    .ContainsProperty(p => p.Quantity)
                .EndGroup()
                .Group("Quote Items")
                    .ContainsProperty(p => p.QuoteItems);

            builder.Property(p => p.QuoteItems).AutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<EnquiryItem> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Enquiry)
                .ContainsProperty(p => p.Sku);

            builder.Property(p => p.Sku).ColumnWidth(300);
            builder.Property(p => p.Quantity).GetEditor<SpinEditorDefinition>().MinValue = 0;
            
            builder.GridBaseColumnEditors().Property(p => p.QuoteItems)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(QuoteItem),
                    FilterMethod = context => CriteriaOperator.Parse("EnquiryItem.Oid=?", ((EnquiryItem)context).Oid)
                });

            builder.DataFormEditors().Property(p => p.QuoteItems)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(QuoteItem),
                    FilterMethod = context => CriteriaOperator.Parse("EnquiryItem.Oid=?", ((EnquiryItem)context).Oid),
                });
        }

        #endregion
    }
}