using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.DataModel.Core.Extension;
using TIG.TotalLink.Shared.Facade.Sale;

namespace TIG.TotalLink.Shared.DataModel.Sale
{
    [FacadeType(typeof(ISaleFacade))]
    [DisplayField("Reference")]
    public partial class Enquiry
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<Enquiry> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.Reference)
                .ContainsProperty(p => p.Name)
                .ContainsProperty(p => p.Status)
                .ContainsProperty(p => p.EnquiryType)
                .ContainsProperty(p => p.NumberOfEmployees)
                .ContainsProperty(p => p.CompanyName)
                .ContainsProperty(p => p.AllowEmailContact)
                .ContainsProperty(p => p.EmailAddress)
                .ContainsProperty(p => p.AllowPhoneContact)
                .ContainsProperty(p => p.PhoneNumber)
                .ContainsProperty(p => p.Details)
                .ContainsProperty(p => p.EnquiryItems)
                .ContainsProperty(p => p.Quotes);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.Reference)
                    .ContainsProperty(p => p.Name)
                    .ContainsProperty(p => p.Status)
                    .ContainsProperty(p => p.EnquiryType)
                    .ContainsProperty(p => p.NumberOfEmployees)
                    .ContainsProperty(p => p.CompanyName)
                    .ContainsProperty(p => p.Details)
                    .ContainsProperty(p => p.Country)
                    .ContainsProperty(p => p.State)
                    .ContainsProperty(p => p.FindMethod)
                .EndGroup()
                .Group("Branding")
                    .ContainsProperty(p => p.BrandingRequired)
                    .ContainsProperty(p => p.BrandingLogoCount)
                    .ContainsProperty(p => p.BrandingType)
                .EndGroup()
                .Group("Contact")
                    .ContainsProperty(p => p.AllowEmailContact)
                    .ContainsProperty(p => p.EmailAddress)
                    .ContainsProperty(p => p.AllowPhoneContact)
                    .ContainsProperty(p => p.PhoneNumber)
                    .ContainsProperty(p => p.AllowMarketing)
                .EndGroup()
                .Group("Items")
                    .ContainsProperty(p => p.EnquiryItems)
                .EndGroup()
                .Group("Quotes")
                    .ContainsProperty(p => p.Quotes);

            builder.Property(p => p.Reference).ReadOnly();
            builder.Property(p => p.EnquiryItems)
                .AutoGenerated()
                .DisplayName("Items");
            builder.Property(p => p.Quotes).AutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<Enquiry> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Reference);

            builder.GridBaseColumnEditors()
                .Property(p => p.Country).Hidden().EndProperty()
                .Property(p => p.State).Hidden().EndProperty()
                .Property(p => p.BrandingRequired).Hidden().EndProperty()
                .Property(p => p.BrandingLogoCount).Hidden().EndProperty()
                .Property(p => p.BrandingType).Hidden().EndProperty()
                .Property(p => p.FindMethod).Hidden().EndProperty()
                .Property(p => p.AllowMarketing).Hidden().EndProperty();

            builder.Property(p => p.Reference).GetEditor<SpinEditorDefinition>().DisplayFormat = "D0";
            builder.Property(p => p.EmailAddress).ReplaceEditor(new HyperLinkEditorDefinition() { AllowUrls = false });
            builder.Property(p => p.Details).ReplaceEditor(new MemoEditorDefinition());
            builder.Property(p => p.BrandingLogoCount).GetEditor<SpinEditorDefinition>().MinValue = 0;

            builder.GridBaseColumnEditors().Property(p => p.EnquiryItems)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(EnquiryItem),
                    FilterMethod = context => CriteriaOperator.Parse("Enquiry.Oid=?", ((Enquiry)context).Oid)
                });

            builder.DataFormEditors().Property(p => p.EnquiryItems)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(EnquiryItem),
                    FilterMethod = context => CriteriaOperator.Parse("Enquiry.Oid=?", ((Enquiry)context).Oid),
                    ShowToolBar = true,
                    BuildNewRowMethod = (context, session) => new EnquiryItem(session)
                    {
                        Enquiry = session.GetDataObject((Enquiry)context)
                    }
                });

            builder.GridBaseColumnEditors().Property(p => p.Quotes)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(Quote),
                    FilterMethod = context => CriteriaOperator.Parse("Enquiry.Oid=?", ((Enquiry)context).Oid)
                });

            builder.DataFormEditors().Property(p => p.Quotes)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(Quote),
                    FilterMethod = context => CriteriaOperator.Parse("Enquiry.Oid=?", ((Enquiry)context).Oid),
                });
        }

        #endregion
    }
}