using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.Facade.Sale;

namespace TIG.TotalLink.Shared.DataModel.Sale
{
    [FacadeType(typeof(ISaleFacade))]
    [DisplayField("Sku")]
    [EntityFilter(typeof(Invoice), "Invoice.Oid IN (?)", "Invoice IN (?)")]
    public partial class InvoiceItem
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<InvoiceItem> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.Invoice)
                .ContainsProperty(p => p.SalesOrderItem)
                .ContainsProperty(p => p.Sku)
                .ContainsProperty(p => p.Quantity)
                .ContainsProperty(p => p.CostPrice)
                .ContainsProperty(p => p.SellPrice)
                .ContainsProperty(p => p.DeliveryItems);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.Invoice)
                    .ContainsProperty(p => p.SalesOrderItem)
                    .ContainsProperty(p => p.Sku)
                    .ContainsProperty(p => p.Quantity)
                    .ContainsProperty(p => p.CostPrice)
                    .ContainsProperty(p => p.SellPrice)
                .EndGroup()
                .Group("Delivery Items")
                    .ContainsProperty(p => p.DeliveryItems);

            builder.Property(p => p.DeliveryItems).AutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<InvoiceItem> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Invoice)
                .ContainsProperty(p => p.Sku);

            builder.Property(p => p.Sku).ColumnWidth(300);
            builder.Property(p => p.Quantity).GetEditor<SpinEditorDefinition>().MinValue = 0;
            builder.Property(p => p.CostPrice).ReplaceEditor(new CurrencyEditorDefinition());
            builder.Property(p => p.SellPrice).ReplaceEditor(new CurrencyEditorDefinition());

            builder.GridBaseColumnEditors().Property(p => p.DeliveryItems)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(DeliveryItem),
                    FilterMethod = context => CriteriaOperator.Parse("InvoiceItem.Oid=?", ((InvoiceItem)context).Oid)
                });

            builder.DataFormEditors().Property(p => p.DeliveryItems)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(DeliveryItem),
                    FilterMethod = context => CriteriaOperator.Parse("InvoiceItem.Oid=?", ((InvoiceItem)context).Oid),
                });
        }

        #endregion
    }
}