using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.DataModel.Core.Extension;
using TIG.TotalLink.Shared.Facade.Sale;

namespace TIG.TotalLink.Shared.DataModel.Sale
{
    [FacadeType(typeof(ISaleFacade))]
    [DisplayField("Reference")]
    public partial class Invoice
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<Invoice> builder)
        {
            builder.TableLayout().Group("")
                    .ContainsProperty(p => p.Reference)
                    .ContainsProperty(p => p.SalesOrder)
                    .ContainsProperty(p => p.Contact)
                    .ContainsProperty(p => p.Status)
                    .ContainsProperty(p => p.InvoiceItems)
                    .ContainsProperty(p => p.Deliveries);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.Reference)
                    .ContainsProperty(p => p.SalesOrder)
                    .ContainsProperty(p => p.Contact)
                    .ContainsProperty(p => p.Status)
                .EndGroup()
                .Group("Items")
                    .ContainsProperty(p => p.InvoiceItems)
                .EndGroup()
                .Group("Deliveries")
                    .ContainsProperty(p => p.Deliveries);

            builder.Property(p => p.Reference).ReadOnly();
            builder.Property(p => p.InvoiceItems)
                .AutoGenerated()
                .DisplayName("Items");
            builder.Property(p => p.Deliveries).AutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<Invoice> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Reference);

            builder.Property(p => p.Reference).GetEditor<SpinEditorDefinition>().DisplayFormat = "D0";

            builder.GridBaseColumnEditors().Property(p => p.InvoiceItems)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(InvoiceItem),
                    FilterMethod = context => CriteriaOperator.Parse("Invoice.Oid=?", ((Invoice)context).Oid)
                });

            builder.DataFormEditors().Property(p => p.InvoiceItems)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(InvoiceItem),
                    FilterMethod = context => CriteriaOperator.Parse("Invoice.Oid=?", ((Invoice)context).Oid),
                    ShowToolBar = true,
                    BuildNewRowMethod = (context, session) => new InvoiceItem(session)
                    {
                        Invoice = session.GetDataObject((Invoice)context)
                    }
                });

            builder.GridBaseColumnEditors().Property(p => p.Deliveries)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(Delivery),
                    FilterMethod = context => CriteriaOperator.Parse("Invoice.Oid=?", ((Invoice)context).Oid)
                });

            builder.DataFormEditors().Property(p => p.Deliveries)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(Delivery),
                    FilterMethod = context => CriteriaOperator.Parse("Invoice.Oid=?", ((Invoice)context).Oid),
                });
        }

        #endregion
    }
}