using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.DataModel.Core.Extension;
using TIG.TotalLink.Shared.Facade.Sale;

namespace TIG.TotalLink.Shared.DataModel.Sale
{
    [FacadeType(typeof(ISaleFacade))]
    [DisplayField("Version")]
    [EntityFilter(typeof(Quote), "Quote.Oid IN (?)", "Quote IN (?)")]
    public partial class QuoteVersion
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<QuoteVersion> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.Quote)
                .ContainsProperty(p => p.Version)
                .ContainsProperty(p => p.QuoteItems);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.Quote)
                    .ContainsProperty(p => p.Version)
                .EndGroup()
                .Group("Items")
                    .ContainsProperty(p => p.QuoteItems)
                .EndGroup()
                .Group("Sales Orders")
                    .ContainsProperty(p => p.SalesOrders);

            builder.Property(p => p.QuoteItems)
                .AutoGenerated()
                .DisplayName("Items");
            builder.Property(p => p.TotalQuantity).Hidden();
            builder.Property(p => p.TotalSellPrice).Hidden();
            builder.Property(p => p.SalesOrders).AutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<QuoteVersion> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Quote)
                .ContainsProperty(p => p.Version);

            builder.GridBaseColumnEditors().Property(p => p.QuoteItems)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(QuoteItem),
                    FilterMethod = context => CriteriaOperator.Parse("QuoteVersion.Oid=?", ((QuoteVersion)context).Oid)
                });

            builder.DataFormEditors().Property(p => p.QuoteItems)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(QuoteItem),
                    FilterMethod = context => CriteriaOperator.Parse("QuoteVersion.Oid=?", ((QuoteVersion)context).Oid),
                    ShowToolBar = true,
                    BuildNewRowMethod = (context, session) => new QuoteItem(session)
                    {
                        QuoteVersion = session.GetDataObject((QuoteVersion)context)
                    }
                });

            builder.GridBaseColumnEditors().Property(p => p.SalesOrders)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(SalesOrder),
                    FilterMethod = context => CriteriaOperator.Parse("QuoteVersion.Oid=?", ((QuoteVersion)context).Oid)
                });

            builder.DataFormEditors().Property(p => p.SalesOrders)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(SalesOrder),
                    FilterMethod = context => CriteriaOperator.Parse("QuoteVersion.Oid=?", ((QuoteVersion)context).Oid),
                });
        }

        #endregion
    }
}