using System.Linq;
using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.Facade.Sale;

namespace TIG.TotalLink.Shared.DataModel.Sale
{
    [FacadeType(typeof(ISaleFacade))]
    [DisplayField("Reference")]
    public partial class Quote
    {
        #region Public Methods

        /// <summary>
        /// Returns the Quote Reference excluding the version number.
        /// </summary>
        /// <returns></returns>
        public string BaseToString()
        {
            return base.ToString();
        }

        #endregion


        #region Overrides

        public override string ToString()
        {
            if (QuoteVersions.Count > 0)
                return string.Format("{0}.{1}", base.ToString(), QuoteVersions.OrderByDescending(v => v.Version).First());

            return base.ToString();
        }

        #endregion


        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<Quote> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.Reference)
                .ContainsProperty(p => p.Contact)
                .ContainsProperty(p => p.Enquiry)
                .ContainsProperty(p => p.QuoteVersions);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.Reference)
                    .ContainsProperty(p => p.Contact)
                    .ContainsProperty(p => p.Enquiry)
                .EndGroup()
                .Group("Versions")
                    .ContainsProperty(p => p.QuoteVersions);

            builder.Property(p => p.Reference).ReadOnly();
            builder.Property(p => p.QuoteVersions).AutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<Quote> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Reference);

            builder.Property(p => p.Reference).GetEditor<SpinEditorDefinition>().DisplayFormat = "D0";

            builder.GridBaseColumnEditors().Property(p => p.QuoteVersions)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(QuoteVersion),
                    FilterMethod = context => CriteriaOperator.Parse("Quote.Oid=?", ((Quote)context).Oid)
                });

            builder.DataFormEditors().Property(p => p.QuoteVersions)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(QuoteVersion),
                    FilterMethod = context => CriteriaOperator.Parse("Quote.Oid=?", ((Quote)context).Oid),
                });
        }

        #endregion
    }
}