using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.Facade.Sale;

namespace TIG.TotalLink.Shared.DataModel.Sale
{
    [FacadeType(typeof(ISaleFacade))]
    [DisplayField("Sku")]
    [EntityFilter(typeof(QuoteVersion), "QuoteVersion.Oid IN (?)", "QuoteVersion IN (?)")]
    public partial class QuoteItem
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<QuoteItem> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.QuoteVersion)
                .ContainsProperty(p => p.EnquiryItem)
                .ContainsProperty(p => p.Sku)
                .ContainsProperty(p => p.Quantity)
                .ContainsProperty(p => p.CostPrice)
                .ContainsProperty(p => p.SellPrice)
                .ContainsProperty(p => p.SalesOrderItems);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.QuoteVersion)
                    .ContainsProperty(p => p.EnquiryItem)
                    .ContainsProperty(p => p.Sku)
                    .ContainsProperty(p => p.Quantity)
                    .ContainsProperty(p => p.CostPrice)
                    .ContainsProperty(p => p.SellPrice)
                .EndGroup()
                .Group("Sales Order Items")
                    .ContainsProperty(p => p.SalesOrderItems);

            builder.Property(p => p.TotalSellPrice).Hidden();
            builder.Property(p => p.SalesOrderItems).AutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<QuoteItem> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.QuoteVersion)
                .ContainsProperty(p => p.Sku);

            builder.Property(p => p.Sku).ColumnWidth(300);
            builder.Property(p => p.Quantity)
                .ColumnWidth(100)
                .GetEditor<SpinEditorDefinition>().MinValue = 0;
            builder.Property(p => p.CostPrice).ReplaceEditor(new CurrencyEditorDefinition());
            builder.Property(p => p.SellPrice).ReplaceEditor(new CurrencyEditorDefinition());

            builder.GridBaseColumnEditors().Property(p => p.SalesOrderItems)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(SalesOrderItem),
                    FilterMethod = context => CriteriaOperator.Parse("QuoteItem.Oid=?", ((QuoteItem)context).Oid)
                });

            builder.DataFormEditors().Property(p => p.SalesOrderItems)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(SalesOrderItem),
                    FilterMethod = context => CriteriaOperator.Parse("QuoteItem.Oid=?", ((QuoteItem)context).Oid),
                });
        }

        #endregion
    }
}