using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.DataModel.Core.Extension;
using TIG.TotalLink.Shared.Facade.Sale;

namespace TIG.TotalLink.Shared.DataModel.Sale
{
    [FacadeType(typeof(ISaleFacade))]
    [DisplayField("Reference")]
    public partial class SalesOrder
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<SalesOrder> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.Reference)
                .ContainsProperty(p => p.QuoteVersion)
                .ContainsProperty(p => p.Contact)
                .ContainsProperty(p => p.Status)
                .ContainsProperty(p => p.AllowPartialDelivery)
                .ContainsProperty(p => p.SalesOrderItems)
                .ContainsProperty(p => p.SalesOrderReleases)
                .ContainsProperty(p => p.Invoices);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.Reference)
                    .ContainsProperty(p => p.QuoteVersion)
                    .ContainsProperty(p => p.Contact)
                    .ContainsProperty(p => p.Status)
                    .ContainsProperty(p => p.AllowPartialDelivery)
                .EndGroup()
                .Group("Items")
                    .ContainsProperty(p => p.SalesOrderItems)
                .EndGroup()
                .Group("Releases")
                    .ContainsProperty(p => p.SalesOrderReleases)
                .EndGroup()
                .Group("Invoices")
                    .ContainsProperty(p => p.Invoices);

            builder.Property(p => p.TotalQuantity).Hidden();
            builder.Property(p => p.TotalQuantityReleased).Hidden();
            builder.Property(p => p.TotalQuantityCancelled).Hidden();
            builder.Property(p => p.TotalSellPrice).Hidden();
            builder.Property(p => p.Reference).ReadOnly();
            builder.Property(p => p.SalesOrderItems)
                .AutoGenerated()
                .DisplayName("Items");
            builder.Property(p => p.SalesOrderReleases)
                .AutoGenerated()
                .DisplayName("Releases");
            builder.Property(p => p.Invoices).AutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<SalesOrder> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Reference);

            builder.Property(p => p.Reference).GetEditor<SpinEditorDefinition>().DisplayFormat = "D0";

            builder.GridBaseColumnEditors().Property(p => p.SalesOrderItems)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(SalesOrderItem),
                    FilterMethod = context => CriteriaOperator.Parse("SalesOrder.Oid = ?", ((SalesOrder)context).Oid)
                });

            builder.DataFormEditors().Property(p => p.SalesOrderItems)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(SalesOrderItem),
                    FilterMethod = context => CriteriaOperator.Parse("SalesOrder.Oid = ?", ((SalesOrder)context).Oid),
                    ShowToolBar = true,
                    BuildNewRowMethod = (context, session) => new SalesOrderItem(session)
                    {
                        SalesOrder = session.GetDataObject((SalesOrder)context)
                    }
                });

            builder.GridBaseColumnEditors().Property(p => p.SalesOrderReleases)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(SalesOrderRelease),
                    FilterMethod = context => CriteriaOperator.Parse("SalesOrders[Oid = ?]", ((SalesOrder)context).Oid)
                });

            builder.DataFormEditors().Property(p => p.SalesOrderReleases)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(SalesOrderRelease),
                    FilterMethod = context => CriteriaOperator.Parse("SalesOrders[Oid = ?]", ((SalesOrder)context).Oid),
                });

            builder.GridBaseColumnEditors().Property(p => p.Invoices)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(Invoice),
                    FilterMethod = context => CriteriaOperator.Parse("SalesOrder.Oid = ?", ((SalesOrder)context).Oid)
                });

            builder.DataFormEditors().Property(p => p.Invoices)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(Invoice),
                    FilterMethod = context => CriteriaOperator.Parse("SalesOrder.Oid = ?", ((SalesOrder)context).Oid),
                });
        }

        #endregion
    }
}