using System;
using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Core.Enum;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Control;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.Facade.Sale;

namespace TIG.TotalLink.Shared.DataModel.Sale
{
    [FacadeType(typeof(ISaleFacade))]
    [DisplayField("Sku")]
    [EntityFilter(typeof(SalesOrder), "SalesOrder.Oid IN (?)", "SalesOrder IN (?)")]
    public partial class SalesOrderItem
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<SalesOrderItem> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.SalesOrder)
                .ContainsProperty(p => p.QuoteItem)
                .ContainsProperty(p => p.Sku)
                .ContainsProperty(p => p.Quantity)
                .ContainsProperty(p => p.QuantityReleased)
                .ContainsProperty(p => p.QuantityCancelled)
                .ContainsProperty(p => p.CostPrice)
                .ContainsProperty(p => p.SellPrice)
                .ContainsProperty(p => p.SalesOrderReleaseItems)
                .ContainsProperty(p => p.InvoiceItems);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.SalesOrder)
                    .ContainsProperty(p => p.QuoteItem)
                    .ContainsProperty(p => p.Sku)
                    .ContainsProperty(p => p.Quantity)
                    .ContainsProperty(p => p.QuantityReleased)
                    .ContainsProperty(p => p.QuantityCancelled)
                    .ContainsProperty(p => p.CostPrice)
                    .ContainsProperty(p => p.SellPrice)
                .EndGroup()
                .Group("Release Items")
                    .ContainsProperty(p => p.SalesOrderReleaseItems)
                .EndGroup()
                .Group("Invoice Items")
                    .ContainsProperty(p => p.InvoiceItems);

            builder.Property(p => p.Sku).ReadOnly();
            builder.Property(p => p.QuantityReleased).ReadOnly();
            builder.Property(p => p.TotalSellPrice).Hidden();
            builder.Property(p => p.InvoiceItems).AutoGenerated();
            builder.Property(p => p.SalesOrderReleaseItems)
                .DisplayName("Release Items")
                .AutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<SalesOrderItem> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.SalesOrder)
                .ContainsProperty(p => p.Sku);

            builder.Condition(c => true)
                .ContainsProperty(p => p.Quantity)
                .ContainsProperty(p => p.QuantityReleased)
                .InvokesInstanceMethod(p => p.QuantityCancelled, new Action<SalesOrderItem, SpinEditorDefinition>((context, editor) =>
                    editor.MaxValue = context.Quantity - context.QuantityReleased
                ));

            builder.Condition(c => true)
                .ContainsProperty(p => p.QuantityCancelled)
                .ContainsProperty(p => p.QuantityReleased)
                .InvokesInstanceMethod(p => p.Quantity, new Action<SalesOrderItem, SpinEditorDefinition>((context, editor) =>
                    editor.MinValue = context.QuantityReleased + context.QuantityCancelled
                ));

            builder.Property(p => p.Sku).ColumnWidth(300);
            builder.Property(p => p.Quantity)
                .ColumnWidth(130)
                .GetEditor<SpinEditorDefinition>().MinValue = 0;
            builder.Property(p => p.QuantityReleased)
                .ColumnWidth(130)
                .GetEditor<SpinEditorDefinition>().MinValue = 0;
            builder.Property(p => p.QuantityCancelled)
                .ColumnWidth(130)
                .GetEditor<SpinEditorDefinition>().MinValue = 0;
            
            builder.Property(p => p.CostPrice)
                .ReplaceEditor(new CurrencyEditorDefinition());

            builder.Property(p => p.SellPrice)
                .ReplaceEditor(new CurrencyEditorDefinition());

            builder.GridBaseColumnEditors().Property(p => p.SalesOrderReleaseItems)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(SalesOrderReleaseItem),
                    FilterMethod = context => CriteriaOperator.Parse("SalesOrderItem.Oid=?", ((SalesOrderItem)context).Oid)
                });

            builder.DataFormEditors().Property(p => p.SalesOrderReleaseItems)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(SalesOrderReleaseItem),
                    FilterMethod = context => CriteriaOperator.Parse("SalesOrderItem.Oid=?", ((SalesOrderItem)context).Oid),
                });

            builder.GridBaseColumnEditors().Property(p => p.InvoiceItems)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(InvoiceItem),
                    FilterMethod = context => CriteriaOperator.Parse("SalesOrderItem.Oid=?", ((SalesOrderItem)context).Oid)
                });

            builder.DataFormEditors().Property(p => p.InvoiceItems)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(InvoiceItem),
                    FilterMethod = context => CriteriaOperator.Parse("SalesOrderItem.Oid=?", ((SalesOrderItem)context).Oid),
                });
        }

        /// <summary>
        /// Builds metadata for form editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        /// <param name="dataLayoutControl">The DataLayoutControlEx that is displaying the object.</param>
        public void BuildFormMetadata(EditorMetadataBuilder<SalesOrderItem> builder, DataLayoutControlEx dataLayoutControl)
        {
            if (dataLayoutControl.EditMode == DetailEditMode.Add)
            {
                builder.DataFormEditors()
                    .Property(p => p.Sku).NotReadOnly().EndProperty();
            }
            else
            {
                builder.DataFormEditors()
                    .Property(p => p.Sku).ReadOnly().EndProperty();
            }
        }
        #endregion
    }
}