using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using DevExpress.Xpf.LayoutControl;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.Facade.Sale;

namespace TIG.TotalLink.Shared.DataModel.Sale
{
    [FacadeType(typeof(ISaleFacade))]
    [DisplayField("Reference")]
    public partial class SalesOrderRelease
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<SalesOrderRelease> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.Reference)
                .ContainsProperty(p => p.BinLocations)
                .ContainsProperty(p => p.PhysicalStockTypes)
                .ContainsProperty(p => p.SalesOrderReleaseItems)
                .ContainsProperty(p => p.Deliveries);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.Reference)
                    .ContainsProperty(p => p.BinLocations)
                    .ContainsProperty(p => p.PhysicalStockTypes)
                .EndGroup()
                .Group("Items")
                    .ContainsProperty(p => p.SalesOrderReleaseItems)
                .EndGroup()
                .Group("Sales Orders")
                    .ContainsProperty(p => p.SalesOrders)
                .EndGroup()
                .Group("Deliveries")
                    .ContainsProperty(p => p.Deliveries);

            builder.Property(p => p.Reference).ReadOnly();
            builder.Property(p => p.SalesOrderReleaseItems)
                .AutoGenerated()
                .DisplayName("Items");
            builder.Property(p => p.Deliveries).AutoGenerated();
            builder.Property(p => p.BinLocations).AutoGenerated();
            builder.Property(p => p.PhysicalStockTypes).AutoGenerated();
            builder.Property(p => p.SalesOrders).AutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<SalesOrderRelease> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Reference);

            builder.Property(p => p.Reference).GetEditor<SpinEditorDefinition>().DisplayFormat = "D0";

            builder.GridBaseColumnEditors().Property(p => p.SalesOrderReleaseItems)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(SalesOrderReleaseItem),
                    FilterMethod = context => CriteriaOperator.Parse("SalesOrderRelease.Oid = ?", ((SalesOrderRelease)context).Oid)
                });

            builder.DataFormEditors().Property(p => p.SalesOrderReleaseItems)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(SalesOrderReleaseItem),
                    FilterMethod = context => CriteriaOperator.Parse("SalesOrderRelease.Oid = ?", ((SalesOrderRelease)context).Oid)
                });

            builder.GridBaseColumnEditors().Property(p => p.SalesOrders)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(SalesOrder),
                    FilterMethod = context => CriteriaOperator.Parse("SalesOrderReleases[Oid = ?]", ((SalesOrderRelease)context).Oid)
                });

            builder.DataFormEditors().Property(p => p.SalesOrders)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(SalesOrder),
                    FilterMethod = context => CriteriaOperator.Parse("SalesOrderReleases[Oid = ?]", ((SalesOrderRelease)context).Oid)
                });

            builder.GridBaseColumnEditors().Property(p => p.Deliveries)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(Delivery),
                    FilterMethod = context => CriteriaOperator.Parse("SalesOrderRelease.Oid = ?", ((SalesOrderRelease)context).Oid)
                });

            builder.DataFormEditors().Property(p => p.Deliveries)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(Delivery),
                    FilterMethod = context => CriteriaOperator.Parse("SalesOrderRelease.Oid = ?", ((SalesOrderRelease)context).Oid)
                });
            
            builder.GridBaseColumnEditors().Property(p => p.BinLocations)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(SalesOrderRelease_BinLocation),
                    FilterMethod = context => CriteriaOperator.Parse("SalesOrderRelease.Oid = ?", ((SalesOrderRelease)context).Oid)
                });

            builder.DataFormEditors().Property(p => p.BinLocations)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(SalesOrderRelease_BinLocation),
                    FilterMethod = context => CriteriaOperator.Parse("SalesOrderRelease.Oid = ?", ((SalesOrderRelease)context).Oid)
                })
                .LabelPosition(LayoutItemLabelPosition.Top);

            builder.GridBaseColumnEditors().Property(p => p.PhysicalStockTypes)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(SalesOrderRelease_PhysicalStockType),
                    FilterMethod = context => CriteriaOperator.Parse("SalesOrderRelease.Oid = ?", ((SalesOrderRelease)context).Oid)
                });

            builder.DataFormEditors().Property(p => p.PhysicalStockTypes)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(SalesOrderRelease_PhysicalStockType),
                    FilterMethod = context => CriteriaOperator.Parse("SalesOrderRelease.Oid = ?", ((SalesOrderRelease)context).Oid)
                })
                .LabelPosition(LayoutItemLabelPosition.Top);
        }

        #endregion
    }
}