using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.DataModel.Core.Enum.Sale;
using TIG.TotalLink.Shared.Facade.Sale;

namespace TIG.TotalLink.Shared.DataModel.Sale
{
    [FacadeType(typeof(ISaleFacade))]
    [DisplayField("SalesOrderItem")]
    [EntityFilter(typeof(SalesOrderRelease), "SalesOrderRelease.Oid IN (?)", "SalesOrderRelease IN (?)")]
    public partial class SalesOrderReleaseItem
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<SalesOrderReleaseItem> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.Status)
                .ContainsProperty(p => p.ErrorMessage)
                .ContainsProperty(p => p.QuantityToRelease)
                .ContainsProperty(p => p.QuantityReleased)
                .ContainsProperty(p => p.SalesOrderRelease)
                .ContainsProperty(p => p.SalesOrder)
                .ContainsProperty(p => p.SalesOrderItem)
                .ContainsProperty(p => p.DeliveryItems);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.SalesOrderRelease)
                    .ContainsProperty(p => p.SalesOrder)
                    .ContainsProperty(p => p.SalesOrderItem)
                    .ContainsProperty(p => p.Status)
                    .ContainsProperty(p => p.ErrorMessage)
                    .ContainsProperty(p => p.QuantityToRelease)
                    .ContainsProperty(p => p.QuantityReleased)
                .EndGroup()
                .Group("Delivery Items")
                    .ContainsProperty(p => p.DeliveryItems);

            builder.Property(p => p.Status).ReadOnly();
            builder.Property(p => p.ErrorMessage).ReadOnly();
            builder.Property(p => p.SalesOrderRelease).ReadOnly();
            builder.Property(p => p.SalesOrderItem).ReadOnly();
            builder.Property(p => p.QuantityToRelease).ReadOnly();
            builder.Property(p => p.QuantityReleased).ReadOnly();
            builder.Property(p => p.DeliveryItems).AutoGenerated();
        }
        
        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<SalesOrderReleaseItem> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.SalesOrderRelease)
                .ContainsProperty(p => p.SalesOrderItem);

            builder.Property(p => p.QuantityToRelease).ColumnWidth(130);
            builder.Property(p => p.QuantityReleased).ColumnWidth(130);
            builder.Property(p => p.ErrorMessage)
                .ColumnWidth(300)
                .ReplaceEditor(new MemoEditorDefinition());
            builder.Property(p => p.Status).ReplaceEditor(new ComboEditorDefinition(typeof(SalesOrderReleaseItemStatus)));

            builder.GridBaseColumnEditors().Property(p => p.DeliveryItems)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(DeliveryItem),
                    FilterMethod = context => CriteriaOperator.Parse("SalesOrderReleaseItem.Oid = ?", ((SalesOrderReleaseItem)context).Oid)
                });

            builder.DataFormEditors().Property(p => p.DeliveryItems)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(DeliveryItem),
                    FilterMethod = context => CriteriaOperator.Parse("SalesOrderReleaseItem.Oid = ?", ((SalesOrderReleaseItem)context).Oid)
                });
        }

        #endregion
    }
}