//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Integration
{

    public partial class SyncEntityBundle : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        string _Name;
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        bool? _IsActive;
        public bool? IsActive
        {
            get { return _IsActive; }
            set { SetPropertyValue<bool?>("IsActive", ref _IsActive, value); }
        }
        int? _Timeout;
        public int? Timeout
        {
            get { return _Timeout; }
            set { SetPropertyValue<int?>("Timeout", ref _Timeout, value); }
        }
        [Association(@"ItemToSyncReferencesTypeToSync", typeof(SyncInstanceBundle))]
        public XPCollection<SyncInstanceBundle> InstanceBundles { get { return GetCollection<SyncInstanceBundle>("InstanceBundles"); } }
        [ExplicitLoading(1)]
        [Association(@"SyncEntityReferencesSyncEntityBundle", typeof(SyncEntity))]
        public XPCollection<SyncEntity> Entities { get { return GetCollection<SyncEntity>("Entities"); } }
    }

}
