//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Integration
{

    public partial class SyncInstanceBundle : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        SyncEntityBundle _EntityBundle;
        [Association(@"ItemToSyncReferencesTypeToSync")]
        public SyncEntityBundle EntityBundle
        {
            get { return _EntityBundle; }
            set { SetPropertyValue<SyncEntityBundle>("EntityBundle", ref _EntityBundle, value); }
        }
        TIG.TotalLink.Shared.DataModel.Core.Enum.Integration.SyncInstanceBundleState _State;
        [Indexed(Name = @"IX_SyncInstanceBundle_State")]
        public TIG.TotalLink.Shared.DataModel.Core.Enum.Integration.SyncInstanceBundleState State
        {
            get { return _State; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Core.Enum.Integration.SyncInstanceBundleState>("State", ref _State, value); }
        }
        [ExplicitLoading(1)]
        [Association(@"ItemToSyncDetailReferencesItemToSync", typeof(SyncInstance))]
        public XPCollection<SyncInstance> Instances { get { return GetCollection<SyncInstance>("Instances"); } }
    }

}
