//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Integration
{

    public partial class SyncEntityMap : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        string _Name;
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        SyncEntity _SourceEntity;
        [Association(@"SyncEntityMapReferencesSyncEntity")]
        public SyncEntity SourceEntity
        {
            get { return _SourceEntity; }
            set { SetPropertyValue<SyncEntity>("SourceEntity", ref _SourceEntity, value); }
        }
        string _SourceFilter;
        public string SourceFilter
        {
            get { return _SourceFilter; }
            set { SetPropertyValue<string>("SourceFilter", ref _SourceFilter, value); }
        }
        SyncEntity _TargetEntity;
        [Association(@"SyncEntityMapReferencesSyncEntity1")]
        public SyncEntity TargetEntity
        {
            get { return _TargetEntity; }
            set { SetPropertyValue<SyncEntity>("TargetEntity", ref _TargetEntity, value); }
        }
        string _SyncKeyInfo;
        [Size(SizeAttribute.Unlimited)]
        public string SyncKeyInfo
        {
            get { return _SyncKeyInfo; }
            set { SetPropertyValue<string>("SyncKeyInfo", ref _SyncKeyInfo, value); }
        }
        Guid _MapperPluginId;
        public Guid MapperPluginId
        {
            get { return _MapperPluginId; }
            set { SetPropertyValue<Guid>("MapperPluginId", ref _MapperPluginId, value); }
        }
        bool _IsActive;
        public bool IsActive
        {
            get { return _IsActive; }
            set { SetPropertyValue<bool>("IsActive", ref _IsActive, value); }
        }
        string _FieldMappings;
        [Size(SizeAttribute.Unlimited)]
        public string FieldMappings
        {
            get { return _FieldMappings; }
            set { SetPropertyValue<string>("FieldMappings", ref _FieldMappings, value); }
        }
        int _Order;
        public int Order
        {
            get { return _Order; }
            set { SetPropertyValue<int>("Order", ref _Order, value); }
        }
    }

}
