//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Integration
{

    public partial class SyncEntity : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        string _EntityName;
        public string EntityName
        {
            get { return _EntityName; }
            set { SetPropertyValue<string>("EntityName", ref _EntityName, value); }
        }
        string _TableName;
        public string TableName
        {
            get { return _TableName; }
            set { SetPropertyValue<string>("TableName", ref _TableName, value); }
        }
        string _PrimaryKey;
        [Size(SizeAttribute.Unlimited)]
        public string PrimaryKey
        {
            get { return _PrimaryKey; }
            set { SetPropertyValue<string>("PrimaryKey", ref _PrimaryKey, value); }
        }
        bool? _IsActive;
        public bool? IsActive
        {
            get { return _IsActive; }
            set { SetPropertyValue<bool?>("IsActive", ref _IsActive, value); }
        }
        Guid? _AgentPluginId;
        public Guid? AgentPluginId
        {
            get { return _AgentPluginId; }
            set { SetPropertyValue<Guid?>("AgentPluginId", ref _AgentPluginId, value); }
        }
        Guid? _ChangeTrackerPluginId;
        public Guid? ChangeTrackerPluginId
        {
            get { return _ChangeTrackerPluginId; }
            set { SetPropertyValue<Guid?>("ChangeTrackerPluginId", ref _ChangeTrackerPluginId, value); }
        }
        long? _LastChangeTrackerVersionId;
        public long? LastChangeTrackerVersionId
        {
            get { return _LastChangeTrackerVersionId; }
            set { SetPropertyValue<long?>("LastChangeTrackerVersionId", ref _LastChangeTrackerVersionId, value); }
        }
        SyncEntityBundle _Bundle;
        [Association(@"SyncEntityReferencesSyncEntityBundle")]
        public SyncEntityBundle Bundle
        {
            get { return _Bundle; }
            set { SetPropertyValue<SyncEntityBundle>("Bundle", ref _Bundle, value); }
        }
        double? _PriorityInBundle;
        public double? PriorityInBundle
        {
            get { return _PriorityInBundle; }
            set { SetPropertyValue<double?>("PriorityInBundle", ref _PriorityInBundle, value); }
        }
        [Association(@"SyncEntityMapReferencesSyncEntity", typeof(SyncEntityMap))]
        public XPCollection<SyncEntityMap> SourceEntityMaps { get { return GetCollection<SyncEntityMap>("SourceEntityMaps"); } }
        [Association(@"SyncEntityMapReferencesSyncEntity1", typeof(SyncEntityMap))]
        public XPCollection<SyncEntityMap> TargetEntityMaps { get { return GetCollection<SyncEntityMap>("TargetEntityMaps"); } }
        [Association(@"SyncInstanceReferencesSyncEntity", typeof(SyncInstance))]
        public XPCollection<SyncInstance> Instances { get { return GetCollection<SyncInstance>("Instances"); } }
    }

}
