//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Integration
{

    public partial class SyncInstance : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        SyncInstanceBundle _Bundle;
        [ExplicitLoading(1)]
        [Association(@"ItemToSyncDetailReferencesItemToSync")]
        public SyncInstanceBundle Bundle
        {
            get { return _Bundle; }
            set { SetPropertyValue<SyncInstanceBundle>("Bundle", ref _Bundle, value); }
        }
        SyncEntity _Entity;
        [Association(@"SyncInstanceReferencesSyncEntity")]
        public SyncEntity Entity
        {
            get { return _Entity; }
            set { SetPropertyValue<SyncEntity>("Entity", ref _Entity, value); }
        }
        string _EntityRawId;
        public string EntityRawId
        {
            get { return _EntityRawId; }
            set { SetPropertyValue<string>("EntityRawId", ref _EntityRawId, value); }
        }
        TIG.TotalLink.Shared.DataModel.Core.Enum.Integration.SyncInstanceState _State;
        public TIG.TotalLink.Shared.DataModel.Core.Enum.Integration.SyncInstanceState State
        {
            get { return _State; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Core.Enum.Integration.SyncInstanceState>("State", ref _State, value); }
        }
        DateTime? _LastChangeCapturedTime;
        public DateTime? LastChangeCapturedTime
        {
            get { return _LastChangeCapturedTime; }
            set { SetPropertyValue<DateTime?>("LastChangeCapturedTime", ref _LastChangeCapturedTime, value); }
        }
        DateTime? _LastUpdateTime;
        public DateTime? LastUpdateTime
        {
            get { return _LastUpdateTime; }
            set { SetPropertyValue<DateTime?>("LastUpdateTime", ref _LastUpdateTime, value); }
        }
        string _Hash;
        public string Hash
        {
            get { return _Hash; }
            set { SetPropertyValue<string>("Hash", ref _Hash, value); }
        }
    }

}
