//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Threading.Tasks;
using TIG.IntegrationServer.Plugin.Core.ServiceContext.AuthenticationServiceContext.Contract;

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class AuthenticationServiceContext : System.ServiceModel.ClientBase<IAuthenticationMethodService>, IAuthenticationMethodService
{
    public AuthenticationServiceContext()
    {
    }
    
    public AuthenticationServiceContext(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public AuthenticationServiceContext(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AuthenticationServiceContext(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AuthenticationServiceContext(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void Ping()
    {
        base.Channel.Ping();
    }
    
    public System.Threading.Tasks.Task PingAsync()
    {
        return base.Channel.PingAsync();
    }
    
    public string Login(string userName, string password)
    {
        return base.Channel.Login(userName, password);
    }
    
    public async Task<string> LoginAsync(string userName, string password)
    {
        return await base.Channel.LoginAsync(userName, password);
    }
    
    public string LoginByActiveDirectory(byte[] userSid, System.Guid userGuid)
    {
        return base.Channel.LoginByActiveDirectory(userSid, userGuid);
    }
    
    public async Task<string> LoginByActiveDirectoryAsync(byte[] userSid, System.Guid userGuid)
    {
        return await base.Channel.LoginByActiveDirectoryAsync(userSid, userGuid);
    }
}
