//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Workflow
{

    public partial class Workflow : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        string _Name;
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        WorkflowActivity _WorkflowActivity;
        [Association(@"WorkflowReferencesWorkflowActivity")]
        public WorkflowActivity WorkflowActivity
        {
            get { return _WorkflowActivity; }
            set { SetPropertyValue<WorkflowActivity>("WorkflowActivity", ref _WorkflowActivity, value); }
        }
        DateTime? _PublishedDate;
        public DateTime? PublishedDate
        {
            get { return _PublishedDate; }
            set { SetPropertyValue<DateTime?>("PublishedDate", ref _PublishedDate, value); }
        }
        DateTime? _UnpublishedDate;
        public DateTime? UnpublishedDate
        {
            get { return _UnpublishedDate; }
            set { SetPropertyValue<DateTime?>("UnpublishedDate", ref _UnpublishedDate, value); }
        }
    }

}
