//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Workflow
{

    public partial class WorkflowActivity : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        string _Name;
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        string _Xaml;
        [Size(SizeAttribute.Unlimited)]
        public string Xaml
        {
            get { return _Xaml; }
            set { SetPropertyValue<string>("Xaml", ref _Xaml, value); }
        }
        DateTime? _PublishedDate;
        public DateTime? PublishedDate
        {
            get { return _PublishedDate; }
            set { SetPropertyValue<DateTime?>("PublishedDate", ref _PublishedDate, value); }
        }
        DateTime? _UnpublishedDate;
        public DateTime? UnpublishedDate
        {
            get { return _UnpublishedDate; }
            set { SetPropertyValue<DateTime?>("UnpublishedDate", ref _UnpublishedDate, value); }
        }
        [PersistentAlias("Iif(StartsWith([Xaml], '<Sequence'), 1, Iif(StartsWith([Xaml], '<StateMachine'), 2, Iif(StartsWith([Xaml], '<Flowchart'), 3, 0)))")]
        public int TypeId
        {
            get { return (int)(EvaluateAlias("TypeId")); }
        }
        [PersistentAlias("Iif([TypeId] = 1, 'Sequence', Iif([TypeId] = 2, 'State Machine', Iif([TypeId] = 3, 'Flowchart', 'Undefined')))")]
        public string TypeName
        {
            get { return (string)(EvaluateAlias("TypeName")); }
        }
        [Association(@"WorkflowReferencesWorkflowActivity", typeof(Workflow))]
        public XPCollection<Workflow> Workflows { get { return GetCollection<Workflow>("Workflows"); } }
    }

}
