using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.Facade.Workflow;

namespace TIG.TotalLink.Shared.DataModel.Workflow
{
    [FacadeType(typeof(IWorkflowFacade))]
    [DisplayField("Name")]
    public partial class WorkflowActivity
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<WorkflowActivity> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.Name)
                .ContainsProperty(p => p.PublishedDate)
                .ContainsProperty(p => p.UnpublishedDate)
                .ContainsProperty(p => p.TypeId)
                .ContainsProperty(p => p.TypeName)
                .ContainsProperty(p => p.Xaml);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.Name)
                    .ContainsProperty(p => p.PublishedDate)
                    .ContainsProperty(p => p.UnpublishedDate)
                    .ContainsProperty(p => p.TypeId)
                    .ContainsProperty(p => p.TypeName)
                    .ContainsProperty(p => p.Xaml)
                .EndGroup()
                .Group("Workflows")
                    .ContainsProperty(p => p.Workflows);

            builder.Property(p => p.PublishedDate).ReadOnly();
            builder.Property(p => p.UnpublishedDate).ReadOnly();
            builder.Property(p => p.Xaml).ReadOnly();
            builder.Property(p => p.Workflows).AutoGenerated();
            builder.Property(p => p.TypeId).NotAutoGenerated();
            builder.Property(p => p.TypeName).DisplayName("Type").ReadOnly();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<WorkflowActivity> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Name);

            builder.Property(p => p.PublishedDate).GetEditor<DateTimeEditorDefinition>().ShowTime = true;
            builder.Property(p => p.UnpublishedDate).GetEditor<DateTimeEditorDefinition>().ShowTime = true;
            builder.Property(p => p.Xaml).ReplaceEditor(new MemoEditorDefinition());

            builder.GridBaseColumnEditors().Property(p => p.Workflows)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(Workflow),
                    FilterMethod = context => CriteriaOperator.Parse("WorkflowActivity.Oid = ?", ((WorkflowActivity)context).Oid)
                });

            builder.DataFormEditors().Property(p => p.Workflows)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(Workflow),
                    FilterMethod = context => CriteriaOperator.Parse("WorkflowActivity.Oid = ?", ((WorkflowActivity)context).Oid)
                });
        }

        #endregion
    }
}
