using System;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Extension;
using TIG.TotalLink.Client.Core.ViewModel;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;

namespace TIG.TotalLink.Client.Module.Admin.ViewModel.Core
{
    /// <summary>
    /// Base class for a view model which describes a data model type.
    /// </summary>
    [DisplayField("Name")]
    public abstract class DataModelTypeViewModelBase : LocalDataObjectBase
    {
        #region Private Fields

        private Type _type;

        #endregion


        #region Constructors

        protected DataModelTypeViewModelBase()
        {
        }

        protected DataModelTypeViewModelBase(Type modelType)
            : this()
        {
            // Initialize properties
            Type = modelType;
        }

        #endregion


        #region Public Properties

        /// <summary>
        /// The type of the data model.
        /// </summary>
        public Type Type
        {
            get { return _type; }
            private set { SetProperty(ref _type, value, () => Type); }
        }

        /// <summary>
        /// Name of the type of the data model.
        /// </summary>
        public string TypeName
        {
            get { return Type != null ? Type.FullName : null; }
        }

        /// <summary>
        /// Name of the data model type.
        /// </summary>
        public virtual string Name
        {
            get { return Type != null ? Type.Name.AddSpaces() : null; }
        }

        /// <summary>
        /// Short description of the data model type.
        /// </summary>
        public virtual string Description
        {
            get { return null; }
        }

        /// <summary>
        /// The category of the data model type.
        /// </summary>
        public virtual string Category
        {
            get { return null; }
        }

        #endregion


        #region Overrides

        public override string ToString()
        {
            return Name;
        }

        #endregion


        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<DataModelTypeViewModelBase> builder)
        {
            builder.DataFormLayout()
                .ContainsProperty(p => p.Name)
                .ContainsProperty(p => p.Description)
                .ContainsProperty(p => p.Category)
                .ContainsProperty(p => p.TypeName);

            builder.TableLayout().Group("")
                .ContainsProperty(p => p.Name)
                .ContainsProperty(p => p.Description)
                .ContainsProperty(p => p.Category)
                .ContainsProperty(p => p.TypeName);

            builder.Property(p => p.Name).ReadOnly();
            builder.Property(p => p.Description).ReadOnly();
            builder.Property(p => p.Category).ReadOnly();
            builder.Property(p => p.TypeName).ReadOnly();

            builder.Property(p => p.Type).NotAutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<DataModelTypeViewModelBase> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Category)
                .ContainsProperty(p => p.Name);
        }

        #endregion
    }
}
