//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIG.IntegrationServer.Common.Configuration
{
    
    
    /// <summary>
    /// The SyncAgentConfigurationSection Configuration Section.
    /// </summary>
    public partial class SyncAgentConfigurationSection : global::System.Configuration.ConfigurationSection
    {
        
        #region Singleton Instance
        /// <summary>
        /// The XML name of the SyncAgentConfigurationSection Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string SyncAgentConfigurationSectionSectionName = "syncAgentConfigurationSection";
        
        /// <summary>
        /// The XML path of the SyncAgentConfigurationSection Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string SyncAgentConfigurationSectionSectionPath = "syncAgentConfigurationSection";
        
        /// <summary>
        /// Gets the SyncAgentConfigurationSection instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public static global::TIG.IntegrationServer.Common.Configuration.SyncAgentConfigurationSection Instance
        {
            get
            {
                return ((global::TIG.IntegrationServer.Common.Configuration.SyncAgentConfigurationSection)(global::System.Configuration.ConfigurationManager.GetSection(global::TIG.IntegrationServer.Common.Configuration.SyncAgentConfigurationSection.SyncAgentConfigurationSectionSectionPath)));
            }
        }
        #endregion
        
        #region Xmlns Property
        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string XmlnsPropertyName = "xmlns";
        
        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::TIG.IntegrationServer.Common.Configuration.SyncAgentConfigurationSection.XmlnsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::TIG.IntegrationServer.Common.Configuration.SyncAgentConfigurationSection.XmlnsPropertyName]));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region SyncServiceSettings Property
        /// <summary>
        /// The XML name of the <see cref="SyncServiceSettings"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string SyncServiceSettingsPropertyName = "syncServiceSettings";
        
        /// <summary>
        /// Gets or sets the SyncServiceSettings.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The SyncServiceSettings.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::TIG.IntegrationServer.Common.Configuration.SyncAgentConfigurationSection.SyncServiceSettingsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::TIG.IntegrationServer.Common.Configuration.SyncServiceSettings SyncServiceSettings
        {
            get
            {
                return ((global::TIG.IntegrationServer.Common.Configuration.SyncServiceSettings)(base[global::TIG.IntegrationServer.Common.Configuration.SyncAgentConfigurationSection.SyncServiceSettingsPropertyName]));
            }
            set
            {
                base[global::TIG.IntegrationServer.Common.Configuration.SyncAgentConfigurationSection.SyncServiceSettingsPropertyName] = value;
            }
        }
        #endregion
        
        #region ChangeTrackerSettings Property
        /// <summary>
        /// The XML name of the <see cref="ChangeTrackerSettings"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string ChangeTrackerSettingsPropertyName = "changeTrackerSettings";
        
        /// <summary>
        /// Gets or sets the ChangeTrackerSettings.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The ChangeTrackerSettings.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::TIG.IntegrationServer.Common.Configuration.SyncAgentConfigurationSection.ChangeTrackerSettingsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::TIG.IntegrationServer.Common.Configuration.ChangeTrackerConfigurationElement ChangeTrackerSettings
        {
            get
            {
                return ((global::TIG.IntegrationServer.Common.Configuration.ChangeTrackerConfigurationElement)(base[global::TIG.IntegrationServer.Common.Configuration.SyncAgentConfigurationSection.ChangeTrackerSettingsPropertyName]));
            }
            set
            {
                base[global::TIG.IntegrationServer.Common.Configuration.SyncAgentConfigurationSection.ChangeTrackerSettingsPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace TIG.IntegrationServer.Common.Configuration
{
    
    
    /// <summary>
    /// The AuthenticationConfigurationElement Configuration Element.
    /// </summary>
    public partial class AuthenticationConfigurationElement : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region ServiceUri Property
        /// <summary>
        /// The XML name of the <see cref="ServiceUri"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string ServiceUriPropertyName = "serviceUri";
        
        /// <summary>
        /// Gets or sets the ServiceUri.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The ServiceUri.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::TIG.IntegrationServer.Common.Configuration.AuthenticationConfigurationElement.ServiceUriPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string ServiceUri
        {
            get
            {
                return ((string)(base[global::TIG.IntegrationServer.Common.Configuration.AuthenticationConfigurationElement.ServiceUriPropertyName]));
            }
            set
            {
                base[global::TIG.IntegrationServer.Common.Configuration.AuthenticationConfigurationElement.ServiceUriPropertyName] = value;
            }
        }
        #endregion
        
        #region Login Property
        /// <summary>
        /// The XML name of the <see cref="Login"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string LoginPropertyName = "login";
        
        /// <summary>
        /// Gets or sets the Login.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Login.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::TIG.IntegrationServer.Common.Configuration.AuthenticationConfigurationElement.LoginPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Login
        {
            get
            {
                return ((string)(base[global::TIG.IntegrationServer.Common.Configuration.AuthenticationConfigurationElement.LoginPropertyName]));
            }
            set
            {
                base[global::TIG.IntegrationServer.Common.Configuration.AuthenticationConfigurationElement.LoginPropertyName] = value;
            }
        }
        #endregion
        
        #region Password Property
        /// <summary>
        /// The XML name of the <see cref="Password"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string PasswordPropertyName = "password";
        
        /// <summary>
        /// Gets or sets the Password.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Password.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::TIG.IntegrationServer.Common.Configuration.AuthenticationConfigurationElement.PasswordPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Password
        {
            get
            {
                return ((string)(base[global::TIG.IntegrationServer.Common.Configuration.AuthenticationConfigurationElement.PasswordPropertyName]));
            }
            set
            {
                base[global::TIG.IntegrationServer.Common.Configuration.AuthenticationConfigurationElement.PasswordPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace TIG.IntegrationServer.Common.Configuration
{
    
    
    /// <summary>
    /// The SyncServiceSettings Configuration Element.
    /// </summary>
    public partial class SyncServiceSettings : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region ServiceUri Property
        /// <summary>
        /// The XML name of the <see cref="ServiceUri"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string ServiceUriPropertyName = "serviceUri";
        
        /// <summary>
        /// Gets or sets the ServiceUri.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The ServiceUri.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::TIG.IntegrationServer.Common.Configuration.SyncServiceSettings.ServiceUriPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string ServiceUri
        {
            get
            {
                return ((string)(base[global::TIG.IntegrationServer.Common.Configuration.SyncServiceSettings.ServiceUriPropertyName]));
            }
            set
            {
                base[global::TIG.IntegrationServer.Common.Configuration.SyncServiceSettings.ServiceUriPropertyName] = value;
            }
        }
        #endregion
        
        #region Authentication Property
        /// <summary>
        /// The XML name of the <see cref="Authentication"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string AuthenticationPropertyName = "authentication";
        
        /// <summary>
        /// Gets or sets the Authentication.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Authentication.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::TIG.IntegrationServer.Common.Configuration.SyncServiceSettings.AuthenticationPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual bool Authentication
        {
            get
            {
                return ((bool)(base[global::TIG.IntegrationServer.Common.Configuration.SyncServiceSettings.AuthenticationPropertyName]));
            }
            set
            {
                base[global::TIG.IntegrationServer.Common.Configuration.SyncServiceSettings.AuthenticationPropertyName] = value;
            }
        }
        #endregion
        
        #region MetadataUri Property
        /// <summary>
        /// The XML name of the <see cref="MetadataUri"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string MetadataUriPropertyName = "metadataUri";
        
        /// <summary>
        /// Gets or sets the MetadataUri.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The MetadataUri.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::TIG.IntegrationServer.Common.Configuration.SyncServiceSettings.MetadataUriPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string MetadataUri
        {
            get
            {
                return ((string)(base[global::TIG.IntegrationServer.Common.Configuration.SyncServiceSettings.MetadataUriPropertyName]));
            }
            set
            {
                base[global::TIG.IntegrationServer.Common.Configuration.SyncServiceSettings.MetadataUriPropertyName] = value;
            }
        }
        #endregion
        
        #region AuthenticationSettings Property
        /// <summary>
        /// The XML name of the <see cref="AuthenticationSettings"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string AuthenticationSettingsPropertyName = "authenticationSettings";
        
        /// <summary>
        /// Gets or sets the AuthenticationSettings.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The AuthenticationSettings.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::TIG.IntegrationServer.Common.Configuration.SyncServiceSettings.AuthenticationSettingsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::TIG.IntegrationServer.Common.Configuration.AuthenticationConfigurationElement AuthenticationSettings
        {
            get
            {
                return ((global::TIG.IntegrationServer.Common.Configuration.AuthenticationConfigurationElement)(base[global::TIG.IntegrationServer.Common.Configuration.SyncServiceSettings.AuthenticationSettingsPropertyName]));
            }
            set
            {
                base[global::TIG.IntegrationServer.Common.Configuration.SyncServiceSettings.AuthenticationSettingsPropertyName] = value;
            }
        }
        #endregion
        
        #region NetworkCredential Property
        /// <summary>
        /// The XML name of the <see cref="NetworkCredential"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string NetworkCredentialPropertyName = "networkCredential";
        
        /// <summary>
        /// Gets or sets the NetworkCredential.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The NetworkCredential.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::TIG.IntegrationServer.Common.Configuration.SyncServiceSettings.NetworkCredentialPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::TIG.IntegrationServer.Common.Configuration.NetworkCredential NetworkCredential
        {
            get
            {
                return ((global::TIG.IntegrationServer.Common.Configuration.NetworkCredential)(base[global::TIG.IntegrationServer.Common.Configuration.SyncServiceSettings.NetworkCredentialPropertyName]));
            }
            set
            {
                base[global::TIG.IntegrationServer.Common.Configuration.SyncServiceSettings.NetworkCredentialPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace TIG.IntegrationServer.Common.Configuration
{
    
    
    /// <summary>
    /// The ChangeTrackerConfigurationElement Configuration Element.
    /// </summary>
    public partial class ChangeTrackerConfigurationElement : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Provider Property
        /// <summary>
        /// The XML name of the <see cref="Provider"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string ProviderPropertyName = "provider";
        
        /// <summary>
        /// Gets or sets the Provider.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Provider.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::TIG.IntegrationServer.Common.Configuration.ChangeTrackerConfigurationElement.ProviderPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Provider
        {
            get
            {
                return ((string)(base[global::TIG.IntegrationServer.Common.Configuration.ChangeTrackerConfigurationElement.ProviderPropertyName]));
            }
            set
            {
                base[global::TIG.IntegrationServer.Common.Configuration.ChangeTrackerConfigurationElement.ProviderPropertyName] = value;
            }
        }
        #endregion
        
        #region ConnectionString Property
        /// <summary>
        /// The XML name of the <see cref="ConnectionString"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string ConnectionStringPropertyName = "connectionString";
        
        /// <summary>
        /// Gets or sets the ConnectionString.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The ConnectionString.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::TIG.IntegrationServer.Common.Configuration.ChangeTrackerConfigurationElement.ConnectionStringPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string ConnectionString
        {
            get
            {
                return ((string)(base[global::TIG.IntegrationServer.Common.Configuration.ChangeTrackerConfigurationElement.ConnectionStringPropertyName]));
            }
            set
            {
                base[global::TIG.IntegrationServer.Common.Configuration.ChangeTrackerConfigurationElement.ConnectionStringPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace TIG.IntegrationServer.Common.Configuration
{
    
    
    /// <summary>
    /// The NetworkCredential Configuration Element.
    /// </summary>
    public partial class NetworkCredential : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Username Property
        /// <summary>
        /// The XML name of the <see cref="Username"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string UsernamePropertyName = "username";
        
        /// <summary>
        /// Gets or sets the Username.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Username.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::TIG.IntegrationServer.Common.Configuration.NetworkCredential.UsernamePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Username
        {
            get
            {
                return ((string)(base[global::TIG.IntegrationServer.Common.Configuration.NetworkCredential.UsernamePropertyName]));
            }
            set
            {
                base[global::TIG.IntegrationServer.Common.Configuration.NetworkCredential.UsernamePropertyName] = value;
            }
        }
        #endregion
        
        #region Password Property
        /// <summary>
        /// The XML name of the <see cref="Password"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string PasswordPropertyName = "password";
        
        /// <summary>
        /// Gets or sets the Password.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Password.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::TIG.IntegrationServer.Common.Configuration.NetworkCredential.PasswordPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Password
        {
            get
            {
                return ((string)(base[global::TIG.IntegrationServer.Common.Configuration.NetworkCredential.PasswordPropertyName]));
            }
            set
            {
                base[global::TIG.IntegrationServer.Common.Configuration.NetworkCredential.PasswordPropertyName] = value;
            }
        }
        #endregion
        
        #region Domain Property
        /// <summary>
        /// The XML name of the <see cref="Domain"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string DomainPropertyName = "domain";
        
        /// <summary>
        /// Gets or sets the Domain.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Domain.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::TIG.IntegrationServer.Common.Configuration.NetworkCredential.DomainPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Domain
        {
            get
            {
                return ((string)(base[global::TIG.IntegrationServer.Common.Configuration.NetworkCredential.DomainPropertyName]));
            }
            set
            {
                base[global::TIG.IntegrationServer.Common.Configuration.NetworkCredential.DomainPropertyName] = value;
            }
        }
        #endregion
    }
}
