using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.DataModel.Core.Extension;
using TIG.TotalLink.Shared.Facade.Purchasing;

namespace TIG.TotalLink.Shared.DataModel.Purchasing
{
    [FacadeType(typeof(IPurchasingFacade))]
    [DisplayField("Reference")]
    public partial class PurchaseOrder
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<PurchaseOrder> builder)
        {
            builder.TableLayout().Group("")
                    .ContainsProperty(p => p.Reference)
                    .ContainsProperty(p => p.Vendor)
                    .ContainsProperty(p => p.Status)
                    .ContainsProperty(p => p.PurchaseOrderItems)
                    .ContainsProperty(p => p.PurchaseReceipts);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.Reference)
                    .ContainsProperty(p => p.Vendor)
                    .ContainsProperty(p => p.Status)
                .EndGroup()
                .Group("Items")
                    .ContainsProperty(p => p.PurchaseOrderItems)
                .EndGroup()
                .Group("Receipts")
                    .ContainsProperty(p => p.PurchaseReceipts);

            builder.Property(p => p.PurchaseOrderItems)
                .AutoGenerated()
                .DisplayName("Items");
            builder.Property(p => p.PurchaseReceipts)
                .AutoGenerated()
                .DisplayName("Receipts");
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<PurchaseOrder> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Reference);

            builder.GridBaseColumnEditors().Property(p => p.PurchaseOrderItems)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(PurchaseOrderItem),
                    FilterMethod = context => CriteriaOperator.Parse("PurchaseOrder.Oid=?", ((PurchaseOrder)context).Oid)
                });

            builder.DataFormEditors().Property(p => p.PurchaseOrderItems)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(PurchaseOrderItem),
                    FilterMethod = context => CriteriaOperator.Parse("PurchaseOrder.Oid=?", ((PurchaseOrder)context).Oid),
                    ShowToolBar = true,
                    BuildNewRowMethod = (context, session) => new PurchaseOrderItem(session)
                    {
                        PurchaseOrder = session.GetDataObject((PurchaseOrder)context)
                    }
                });

            builder.GridBaseColumnEditors().Property(p => p.PurchaseReceipts)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(PurchaseReceipt),
                    FilterMethod = context => CriteriaOperator.Parse("PurchaseOrder.Oid=?", ((PurchaseOrder)context).Oid)
                });

            builder.DataFormEditors().Property(p => p.PurchaseReceipts)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(PurchaseReceipt),
                    FilterMethod = context => CriteriaOperator.Parse("PurchaseOrder.Oid=?", ((PurchaseOrder)context).Oid),
                });
        }

        #endregion
    }
}