using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.DataModel.Core.Extension;
using TIG.TotalLink.Shared.Facade.Purchasing;

namespace TIG.TotalLink.Shared.DataModel.Purchasing
{
    [FacadeType(typeof(IPurchasingFacade))]
    [DisplayField("Reference")]
    public partial class PurchaseReceipt
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<PurchaseReceipt> builder)
        {
            builder.TableLayout().Group("")
                    .ContainsProperty(p => p.Reference)
                    .ContainsProperty(p => p.PurchaseOrder)
                    .ContainsProperty(p => p.Status)
                    .ContainsProperty(p => p.PurchaseReceiptItems);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.Reference)
                    .ContainsProperty(p => p.PurchaseOrder)
                    .ContainsProperty(p => p.Status)
                .EndGroup()
                .Group("Items")
                    .ContainsProperty(p => p.PurchaseReceiptItems);

            builder.Property(p => p.PurchaseReceiptItems)
                .AutoGenerated()
                .DisplayName("Items");
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<PurchaseReceipt> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Reference);

            builder.GridBaseColumnEditors().Property(p => p.PurchaseReceiptItems)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(PurchaseReceiptItem),
                    FilterMethod = context => CriteriaOperator.Parse("PurchaseReceipt.Oid=?", ((PurchaseReceipt)context).Oid)
                });

            builder.DataFormEditors().Property(p => p.PurchaseReceiptItems)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(PurchaseReceiptItem),
                    FilterMethod = context => CriteriaOperator.Parse("PurchaseReceipt.Oid=?", ((PurchaseReceipt)context).Oid),
                    ShowToolBar = true,
                    BuildNewRowMethod = (context, session) => new PurchaseReceiptItem(session)
                    {
                        PurchaseReceipt = session.GetDataObject((PurchaseReceipt)context)
                    }
                });
        }

        #endregion
    }
}