using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.Facade.Purchasing;

namespace TIG.TotalLink.Shared.DataModel.Purchasing
{
    [FacadeType(typeof(IPurchasingFacade))]
    [DisplayField("Quantity")]
    public partial class PurchaseOrderItem
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<PurchaseOrderItem> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.PurchaseOrder)
                .ContainsProperty(p => p.Sku)
                .ContainsProperty(p => p.Quantity)
                .ContainsProperty(p => p.PurchaseReceiptItems);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.PurchaseOrder)
                    .ContainsProperty(p => p.Sku)
                    .ContainsProperty(p => p.Quantity)
                .EndGroup()
                .Group("Receipt Items")
                    .ContainsProperty(p => p.PurchaseReceiptItems);

            builder.Property(p => p.PurchaseReceiptItems)
                .AutoGenerated()
                .DisplayName("Receipt Items");
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<PurchaseOrderItem> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.PurchaseOrder)
                .ContainsProperty(p => p.Sku);

            builder.GridBaseColumnEditors().Property(p => p.PurchaseReceiptItems)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(PurchaseReceiptItem),
                    FilterMethod = context => CriteriaOperator.Parse("PurchaseOrderItem.Oid=?", ((PurchaseOrderItem)context).Oid)
                });

            builder.DataFormEditors().Property(p => p.PurchaseReceiptItems)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(PurchaseReceiptItem),
                    FilterMethod = context => CriteriaOperator.Parse("PurchaseOrderItem.Oid=?", ((PurchaseOrderItem)context).Oid),
                });
        }

        #endregion
    }
}