using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.Facade.Task;

namespace TIG.TotalLink.Shared.DataModel.Task
{
    [FacadeType(typeof(ITaskFacade))]
    [DisplayField("Name")]
    public partial class Task
    {
        #region Public Methods

        /// <summary>
        /// Creates a grid filter for the Children editor.
        /// </summary>
        /// <param name="dataContext">The object being edited.</param>
        /// <returns>A CriteriaOperator.</returns>
        public static CriteriaOperator GetChildrenGridFilter(object dataContext)
        {
            return CriteriaOperator.Parse("Parent.Oid = ?", ((Task)dataContext).Oid);
        }

        #endregion


        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<Task> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.Name)
                .ContainsProperty(p => p.Parent)
                .ContainsProperty(p => p.Children);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.Name)
                    .ContainsProperty(p => p.Parent)
                .EndGroup()
                .Group("Children")
                    .ContainsProperty(p => p.Children);

            builder.Property(p => p.Name).MaxLength(1000);

            builder.Property(p => p.Children).AutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<Task> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Name);

            builder.Property(p => p.Parent).AllowNull();

            builder.GridBaseColumnEditors().Property(p => p.Children).ReplaceEditor(new PopupGridEditorDefinition()
            {
                EntityType = typeof(Task),
                FilterMethod = GetChildrenGridFilter
            });

            builder.DataFormEditors().Property(p => p.Children).ReplaceEditor(new GridEditorDefinition()
            {
                EntityType = typeof(Task),
                FilterMethod = GetChildrenGridFilter
            });

            builder.DataFormEditors().Property(p => p.Children).HideLabel();
        }

        #endregion
    }
}
