//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIG.TotalLink.Server.Core.Configuration
{
    
    
    /// <summary>
    /// The ActiveDirectoryConfigurationSection Configuration Section.
    /// </summary>
    public partial class ActiveDirectoryConfigurationSection : global::System.Configuration.ConfigurationSection
    {
        
        #region Singleton Instance
        /// <summary>
        /// The XML name of the ActiveDirectoryConfigurationSection Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string ActiveDirectoryConfigurationSectionSectionName = "activeDirectoryConfigurationSection";
        
        /// <summary>
        /// The XML path of the ActiveDirectoryConfigurationSection Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string ActiveDirectoryConfigurationSectionSectionPath = "activeDirectoryConfigurationSection";
        
        /// <summary>
        /// Gets the ActiveDirectoryConfigurationSection instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public static global::TIG.TotalLink.Server.Core.Configuration.ActiveDirectoryConfigurationSection Instance
        {
            get
            {
                return ((global::TIG.TotalLink.Server.Core.Configuration.ActiveDirectoryConfigurationSection)(global::System.Configuration.ConfigurationManager.GetSection(global::TIG.TotalLink.Server.Core.Configuration.ActiveDirectoryConfigurationSection.ActiveDirectoryConfigurationSectionSectionPath)));
            }
        }
        #endregion
        
        #region Xmlns Property
        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string XmlnsPropertyName = "xmlns";
        
        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::TIG.TotalLink.Server.Core.Configuration.ActiveDirectoryConfigurationSection.XmlnsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::TIG.TotalLink.Server.Core.Configuration.ActiveDirectoryConfigurationSection.XmlnsPropertyName]));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Root Property
        /// <summary>
        /// The XML name of the <see cref="Root"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string RootPropertyName = "root";
        
        /// <summary>
        /// Gets or sets the Root.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Root.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::TIG.TotalLink.Server.Core.Configuration.ActiveDirectoryConfigurationSection.RootPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Root
        {
            get
            {
                return ((string)(base[global::TIG.TotalLink.Server.Core.Configuration.ActiveDirectoryConfigurationSection.RootPropertyName]));
            }
            set
            {
                base[global::TIG.TotalLink.Server.Core.Configuration.ActiveDirectoryConfigurationSection.RootPropertyName] = value;
            }
        }
        #endregion
        
        #region Domain Property
        /// <summary>
        /// The XML name of the <see cref="Domain"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string DomainPropertyName = "domain";
        
        /// <summary>
        /// Gets or sets the Domain.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Domain.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::TIG.TotalLink.Server.Core.Configuration.ActiveDirectoryConfigurationSection.DomainPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Domain
        {
            get
            {
                return ((string)(base[global::TIG.TotalLink.Server.Core.Configuration.ActiveDirectoryConfigurationSection.DomainPropertyName]));
            }
            set
            {
                base[global::TIG.TotalLink.Server.Core.Configuration.ActiveDirectoryConfigurationSection.DomainPropertyName] = value;
            }
        }
        #endregion
        
        #region User Property
        /// <summary>
        /// The XML name of the <see cref="User"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string UserPropertyName = "user";
        
        /// <summary>
        /// Gets or sets the User.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The User.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::TIG.TotalLink.Server.Core.Configuration.ActiveDirectoryConfigurationSection.UserPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string User
        {
            get
            {
                return ((string)(base[global::TIG.TotalLink.Server.Core.Configuration.ActiveDirectoryConfigurationSection.UserPropertyName]));
            }
            set
            {
                base[global::TIG.TotalLink.Server.Core.Configuration.ActiveDirectoryConfigurationSection.UserPropertyName] = value;
            }
        }
        #endregion
        
        #region Password Property
        /// <summary>
        /// The XML name of the <see cref="Password"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string PasswordPropertyName = "password";
        
        /// <summary>
        /// Gets or sets the Password.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Password.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::TIG.TotalLink.Server.Core.Configuration.ActiveDirectoryConfigurationSection.PasswordPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Password
        {
            get
            {
                return ((string)(base[global::TIG.TotalLink.Server.Core.Configuration.ActiveDirectoryConfigurationSection.PasswordPropertyName]));
            }
            set
            {
                base[global::TIG.TotalLink.Server.Core.Configuration.ActiveDirectoryConfigurationSection.PasswordPropertyName] = value;
            }
        }
        #endregion
    }
}
