//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Inventory
{

    public partial class Barcode : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        BarcodeType _BarcodeType;
        [ExplicitLoading(1)]
        [Association(@"BarcodeReferencesBarcodeType")]
        public BarcodeType BarcodeType
        {
            get { return _BarcodeType; }
            set { SetPropertyValue<BarcodeType>("BarcodeType", ref _BarcodeType, value); }
        }
        string _Number;
        [Size(150)]
        public string Number
        {
            get { return _Number; }
            set { SetPropertyValue<string>("Number", ref _Number, value); }
        }
        [Association(@"SkuReferencesBarcode", typeof(Sku))]
        public XPCollection<Sku> Skus { get { return GetCollection<Sku>("Skus"); } }
    }

}
