//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Inventory
{

    public partial class BinLocation : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        string _Name;
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        string _IsleCode;
        public string IsleCode
        {
            get { return _IsleCode; }
            set { SetPropertyValue<string>("IsleCode", ref _IsleCode, value); }
        }
        string _BinCode;
        public string BinCode
        {
            get { return _BinCode; }
            set { SetPropertyValue<string>("BinCode", ref _BinCode, value); }
        }
        WarehouseLocation _WarehouseLocation;
        [Association(@"BinLocationReferencesWarehouseLocation")]
        public WarehouseLocation WarehouseLocation
        {
            get { return _WarehouseLocation; }
            set { SetPropertyValue<WarehouseLocation>("WarehouseLocation", ref _WarehouseLocation, value); }
        }
        [Association(@"StockAdjustmentReferencesBinLocation", typeof(StockAdjustment))]
        public XPCollection<StockAdjustment> TargetStockAdjustments { get { return GetCollection<StockAdjustment>("TargetStockAdjustments"); } }
        [Association(@"StockAdjustmentReferencesBinLocation1", typeof(StockAdjustment))]
        public XPCollection<StockAdjustment> SourceStockAdjustments { get { return GetCollection<StockAdjustment>("SourceStockAdjustments"); } }
        [DevExpress.Xpo.Aggregated]
        [Association(@"PhysicalStockReferencesBinLocation", typeof(PhysicalStock))]
        public XPCollection<PhysicalStock> PhysicalStocks { get { return GetCollection<PhysicalStock>("PhysicalStocks"); } }
    }

}
