//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Inventory
{

    public partial class Colour : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        string _Name;
        [Size(150)]
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        ColourCategory _Category;
        [ExplicitLoading(1)]
        [Association(@"ColourReferencesColourCategory")]
        public ColourCategory Category
        {
            get { return _Category; }
            set { SetPropertyValue<ColourCategory>("Category", ref _Category, value); }
        }
        [Association(@"SkuReferencesColour", typeof(Sku))]
        public XPCollection<Sku> Skus { get { return GetCollection<Sku>("Skus"); } }
        [Association(@"SkuReferencesWebColour", typeof(Sku))]
        public XPCollection<Sku> Web_Skus { get { return GetCollection<Sku>("Web_Skus"); } }
    }

}
