//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Inventory
{

    public partial class PhysicalStockType : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        string _Name;
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        [Association(@"PhysicalStockReferencesPhysicalStockType", typeof(PhysicalStock))]
        public XPCollection<PhysicalStock> PhysicalStocks { get { return GetCollection<PhysicalStock>("PhysicalStocks"); } }
        [Association(@"StockAdjustmentReferencesPhysicalStockType", typeof(StockAdjustment))]
        public XPCollection<StockAdjustment> TargetStockAdjustments { get { return GetCollection<StockAdjustment>("TargetStockAdjustments"); } }
        [Association(@"StockAdjustmentReferencesPhysicalStockType1", typeof(StockAdjustment))]
        public XPCollection<StockAdjustment> SourceStockAdjustments { get { return GetCollection<StockAdjustment>("SourceStockAdjustments"); } }
    }

}
