//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Inventory
{

    public partial class PhysicalStock : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        Sku _Sku;
        [Indexed(@"PhysicalStockType;BinLocation", Name = @"IX_PhysicalStock")]
        [Association(@"PhysicalStockReferencesSku")]
        public Sku Sku
        {
            get { return _Sku; }
            set { SetPropertyValue<Sku>("Sku", ref _Sku, value); }
        }
        PhysicalStockType _PhysicalStockType;
        [Association(@"PhysicalStockReferencesPhysicalStockType")]
        public PhysicalStockType PhysicalStockType
        {
            get { return _PhysicalStockType; }
            set { SetPropertyValue<PhysicalStockType>("PhysicalStockType", ref _PhysicalStockType, value); }
        }
        int _Quantity;
        public int Quantity
        {
            get { return _Quantity; }
            set { SetPropertyValue<int>("Quantity", ref _Quantity, value); }
        }
        BinLocation _BinLocation;
        [Association(@"PhysicalStockReferencesBinLocation")]
        public BinLocation BinLocation
        {
            get { return _BinLocation; }
            set { SetPropertyValue<BinLocation>("BinLocation", ref _BinLocation, value); }
        }
    }

}
