//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Inventory
{

    public partial class ProductType : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        string _Name;
        [Size(150)]
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        [Association(@"StyleReferencesProductType", typeof(Style))]
        public XPCollection<Style> Styles { get { return GetCollection<Style>("Styles"); } }
        [Association(@"StyleReferencesWebProductType", typeof(Style))]
        public XPCollection<Style> Web_Styles { get { return GetCollection<Style>("Web_Styles"); } }
    }

}
