//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Inventory
{

    public partial class Size : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        string _Name;
        [Size(150)]
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        SizeRange _SizeRange;
        [ExplicitLoading(1)]
        [Association(@"SizeReferencesSizeRange")]
        public SizeRange SizeRange
        {
            get { return _SizeRange; }
            set { SetPropertyValue<SizeRange>("SizeRange", ref _SizeRange, value); }
        }
        [Association(@"SkuReferencesSize", typeof(Sku))]
        public XPCollection<Sku> Skus { get { return GetCollection<Sku>("Skus"); } }
    }

}
