//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Inventory
{

    public partial class Sku : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        string _Name;
        [Size(150)]
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        TIG.TotalLink.Shared.DataModel.Admin.PostingGroup _InventoryPostingGroup;
        [ExplicitLoading(1)]
        [TIG.TotalLink.Shared.DataModel.Core.Attribute.RuntimeAssociation("SkuReferencesInventoryPostingGroup", "InventoryPostingGroups")]
        public TIG.TotalLink.Shared.DataModel.Admin.PostingGroup InventoryPostingGroup
        {
            get { return _InventoryPostingGroup; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Admin.PostingGroup>("InventoryPostingGroup", ref _InventoryPostingGroup, value); }
        }
        decimal _UnitPrice;
        public decimal UnitPrice
        {
            get { return _UnitPrice; }
            set { SetPropertyValue<decimal>("UnitPrice", ref _UnitPrice, value); }
        }
        TIG.TotalLink.Shared.DataModel.Core.Enum.Inventory.CostingMethod _CostingMethod;
        public TIG.TotalLink.Shared.DataModel.Core.Enum.Inventory.CostingMethod CostingMethod
        {
            get { return _CostingMethod; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Core.Enum.Inventory.CostingMethod>("CostingMethod", ref _CostingMethod, value); }
        }
        decimal _UnitCost;
        public decimal UnitCost
        {
            get { return _UnitCost; }
            set { SetPropertyValue<decimal>("UnitCost", ref _UnitCost, value); }
        }
        TIG.TotalLink.Shared.DataModel.Admin.PostingGroup _GeneralProductPostingGroup;
        [ExplicitLoading(1)]
        [TIG.TotalLink.Shared.DataModel.Core.Attribute.RuntimeAssociation("SkuReferencesGeneralProductPostingGroup", "GeneralProductPostingGroups")]
        public TIG.TotalLink.Shared.DataModel.Admin.PostingGroup GeneralProductPostingGroup
        {
            get { return _GeneralProductPostingGroup; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Admin.PostingGroup>("GeneralProductPostingGroup", ref _GeneralProductPostingGroup, value); }
        }
        TIG.TotalLink.Shared.DataModel.Admin.PostingGroup _GSTProductPostingGroup;
        [ExplicitLoading(1)]
        [TIG.TotalLink.Shared.DataModel.Core.Attribute.RuntimeAssociation("SkuReferencesGSTProductPostingGroup", "GSTProductPostingGroups")]
        public TIG.TotalLink.Shared.DataModel.Admin.PostingGroup GSTProductPostingGroup
        {
            get { return _GSTProductPostingGroup; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Admin.PostingGroup>("GSTProductPostingGroup", ref _GSTProductPostingGroup, value); }
        }
        TIG.TotalLink.Shared.DataModel.Core.Enum.Inventory.ReplenishmentSystem _ReplenishmentSystem;
        public TIG.TotalLink.Shared.DataModel.Core.Enum.Inventory.ReplenishmentSystem ReplenishmentSystem
        {
            get { return _ReplenishmentSystem; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Core.Enum.Inventory.ReplenishmentSystem>("ReplenishmentSystem", ref _ReplenishmentSystem, value); }
        }
        TIG.TotalLink.Shared.DataModel.Core.Enum.Inventory.ReorderingPolicy _ReorderingPolicy;
        public TIG.TotalLink.Shared.DataModel.Core.Enum.Inventory.ReorderingPolicy ReorderingPolicy
        {
            get { return _ReorderingPolicy; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Core.Enum.Inventory.ReorderingPolicy>("ReorderingPolicy", ref _ReorderingPolicy, value); }
        }
        bool _IncludeInventory;
        public bool IncludeInventory
        {
            get { return _IncludeInventory; }
            set { SetPropertyValue<bool>("IncludeInventory", ref _IncludeInventory, value); }
        }
        string _ReschedulingPeriod;
        [Size(32)]
        public string ReschedulingPeriod
        {
            get { return _ReschedulingPeriod; }
            set { SetPropertyValue<string>("ReschedulingPeriod", ref _ReschedulingPeriod, value); }
        }
        string _LotAccumulationPeriod;
        [Size(32)]
        public string LotAccumulationPeriod
        {
            get { return _LotAccumulationPeriod; }
            set { SetPropertyValue<string>("LotAccumulationPeriod", ref _LotAccumulationPeriod, value); }
        }
        Style _Style;
        [ExplicitLoading(1)]
        [Association(@"SkuReferencesStyle")]
        public Style Style
        {
            get { return _Style; }
            set { SetPropertyValue<Style>("Style", ref _Style, value); }
        }
        Size _Size;
        [ExplicitLoading(1)]
        [Association(@"SkuReferencesSize")]
        public Size Size
        {
            get { return _Size; }
            set { SetPropertyValue<Size>("Size", ref _Size, value); }
        }
        Colour _Colour;
        [ExplicitLoading(1)]
        [Association(@"SkuReferencesColour")]
        public Colour Colour
        {
            get { return _Colour; }
            set { SetPropertyValue<Colour>("Colour", ref _Colour, value); }
        }
        BusinessDivision _BusinessDivision;
        [ExplicitLoading(1)]
        [Association(@"SkuReferencesBusinessDivision")]
        public BusinessDivision BusinessDivision
        {
            get { return _BusinessDivision; }
            set { SetPropertyValue<BusinessDivision>("BusinessDivision", ref _BusinessDivision, value); }
        }
        Season _Season;
        [ExplicitLoading(1)]
        [Association(@"SkuReferencesSeason")]
        public Season Season
        {
            get { return _Season; }
            set { SetPropertyValue<Season>("Season", ref _Season, value); }
        }
        UnitOfMeasure _PackUnitOfMeasure;
        [ExplicitLoading(1)]
        [Association(@"SkuReferencesUnitOfMeasure1")]
        public UnitOfMeasure PackUnitOfMeasure
        {
            get { return _PackUnitOfMeasure; }
            set { SetPropertyValue<UnitOfMeasure>("PackUnitOfMeasure", ref _PackUnitOfMeasure, value); }
        }
        UnitOfMeasure _ItemUnitOfMeasure;
        [ExplicitLoading(1)]
        public UnitOfMeasure ItemUnitOfMeasure
        {
            get { return _ItemUnitOfMeasure; }
            set { SetPropertyValue<UnitOfMeasure>("ItemUnitOfMeasure", ref _ItemUnitOfMeasure, value); }
        }
        bool _PriceIncludesGST;
        public bool PriceIncludesGST
        {
            get { return _PriceIncludesGST; }
            set { SetPropertyValue<bool>("PriceIncludesGST", ref _PriceIncludesGST, value); }
        }
        bool _AllowLineDiscount;
        public bool AllowLineDiscount
        {
            get { return _AllowLineDiscount; }
            set { SetPropertyValue<bool>("AllowLineDiscount", ref _AllowLineDiscount, value); }
        }
        Barcode _Barcode;
        [Association(@"SkuReferencesBarcode")]
        public Barcode Barcode
        {
            get { return _Barcode; }
            set { SetPropertyValue<Barcode>("Barcode", ref _Barcode, value); }
        }
        TIG.TotalLink.Shared.DataModel.Admin.Country _Country;
        [TIG.TotalLink.Shared.DataModel.Core.Attribute.RuntimeAssociation("SkuReferencesCountry", "Skus")]
        public TIG.TotalLink.Shared.DataModel.Admin.Country Country
        {
            get { return _Country; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Admin.Country>("Country", ref _Country, value); }
        }
        [PersistentAlias("Iif(PhysicalStocks.Exists, PhysicalStocks.Sum(Quantity), 0)")]
        public int PhysicalStock
        {
            get { return (int)(EvaluateAlias("PhysicalStock")); }
        }
        string _Web_SkuId;
        public string Web_SkuId
        {
            get { return _Web_SkuId; }
            set { SetPropertyValue<string>("Web_SkuId", ref _Web_SkuId, value); }
        }
        Colour _Web_Colour;
        [Association(@"SkuReferencesWebColour")]
        public Colour Web_Colour
        {
            get { return _Web_Colour; }
            set { SetPropertyValue<Colour>("Web_Colour", ref _Web_Colour, value); }
        }
        Season _Web_Season;
        [Association(@"SkuReferencesWebSeason")]
        public Season Web_Season
        {
            get { return _Web_Season; }
            set { SetPropertyValue<Season>("Web_Season", ref _Web_Season, value); }
        }
        string _Web_ImageCodeFront;
        [Size(255)]
        public string Web_ImageCodeFront
        {
            get { return _Web_ImageCodeFront; }
            set { SetPropertyValue<string>("Web_ImageCodeFront", ref _Web_ImageCodeFront, value); }
        }
        string _Web_ImageCodeBack;
        [Size(255)]
        public string Web_ImageCodeBack
        {
            get { return _Web_ImageCodeBack; }
            set { SetPropertyValue<string>("Web_ImageCodeBack", ref _Web_ImageCodeBack, value); }
        }
        string _Web_ImageCodeSide;
        [Size(255)]
        public string Web_ImageCodeSide
        {
            get { return _Web_ImageCodeSide; }
            set { SetPropertyValue<string>("Web_ImageCodeSide", ref _Web_ImageCodeSide, value); }
        }
        string _Web_ImageCodeFull;
        [Size(255)]
        public string Web_ImageCodeFull
        {
            get { return _Web_ImageCodeFull; }
            set { SetPropertyValue<string>("Web_ImageCodeFull", ref _Web_ImageCodeFull, value); }
        }
        Sku _Parent;
        [Association(@"SkuReferencesSku")]
        public Sku Parent
        {
            get { return _Parent; }
            set { SetPropertyValue<Sku>("Parent", ref _Parent, value); }
        }
        long _Reference;
        public long Reference
        {
            get { return _Reference; }
            set { SetPropertyValue<long>("Reference", ref _Reference, value); }
        }
        string _LegacyReference;
        public string LegacyReference
        {
            get { return _LegacyReference; }
            set { SetPropertyValue<string>("LegacyReference", ref _LegacyReference, value); }
        }
        [Association(@"PriceRangeReferencesSku", typeof(PriceRange))]
        public XPCollection<PriceRange> PriceRanges { get { return GetCollection<PriceRange>("PriceRanges"); } }
        [Association(@"PhysicalStockReferencesSku", typeof(PhysicalStock))]
        public XPCollection<PhysicalStock> PhysicalStocks { get { return GetCollection<PhysicalStock>("PhysicalStocks"); } }
        [Association(@"SkuReferencesSku", typeof(Sku))]
        public XPCollection<Sku> Children { get { return GetCollection<Sku>("Children"); } }
    }

}
