//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Inventory
{

    public partial class StockAdjustment : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        Sku _Sku;
        public Sku Sku
        {
            get { return _Sku; }
            set { SetPropertyValue<Sku>("Sku", ref _Sku, value); }
        }
        int _Quantity;
        public int Quantity
        {
            get { return _Quantity; }
            set { SetPropertyValue<int>("Quantity", ref _Quantity, value); }
        }
        string _Notes;
        [Size(SizeAttribute.Unlimited)]
        public string Notes
        {
            get { return _Notes; }
            set { SetPropertyValue<string>("Notes", ref _Notes, value); }
        }
        BinLocation _TargetBinLocation;
        [Association(@"StockAdjustmentReferencesBinLocation")]
        public BinLocation TargetBinLocation
        {
            get { return _TargetBinLocation; }
            set { SetPropertyValue<BinLocation>("TargetBinLocation", ref _TargetBinLocation, value); }
        }
        BinLocation _SourceBinLocation;
        [Association(@"StockAdjustmentReferencesBinLocation1")]
        public BinLocation SourceBinLocation
        {
            get { return _SourceBinLocation; }
            set { SetPropertyValue<BinLocation>("SourceBinLocation", ref _SourceBinLocation, value); }
        }
        StockAdjustmentReason _Reason;
        [Association(@"StockAdjustmentReferencesStockAdjustmentReason")]
        public StockAdjustmentReason Reason
        {
            get { return _Reason; }
            set { SetPropertyValue<StockAdjustmentReason>("Reason", ref _Reason, value); }
        }
        PhysicalStockType _TargetPhysicalStockType;
        [Association(@"StockAdjustmentReferencesPhysicalStockType")]
        public PhysicalStockType TargetPhysicalStockType
        {
            get { return _TargetPhysicalStockType; }
            set { SetPropertyValue<PhysicalStockType>("TargetPhysicalStockType", ref _TargetPhysicalStockType, value); }
        }
        PhysicalStockType _SourcePhysicalStockType;
        [Association(@"StockAdjustmentReferencesPhysicalStockType1")]
        public PhysicalStockType SourcePhysicalStockType
        {
            get { return _SourcePhysicalStockType; }
            set { SetPropertyValue<PhysicalStockType>("SourcePhysicalStockType", ref _SourcePhysicalStockType, value); }
        }
        TIG.TotalLink.Shared.DataModel.Crm.Contact _Vendor;
        [TIG.TotalLink.Shared.DataModel.Core.Attribute.RuntimeAssociation("StockAdjustmentReferencesContact", "StockAdjustments")]
        public TIG.TotalLink.Shared.DataModel.Crm.Contact Vendor
        {
            get { return _Vendor; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Crm.Contact>("Vendor", ref _Vendor, value); }
        }
        string _VendorReference;
        [Size(255)]
        public string VendorReference
        {
            get { return _VendorReference; }
            set { SetPropertyValue<string>("VendorReference", ref _VendorReference, value); }
        }
    }

}
