//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Inventory
{

    public partial class StockAdjustmentReason : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        string _Name;
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        bool _IsTargetIncrease;
        public bool IsTargetIncrease
        {
            get { return _IsTargetIncrease; }
            set { SetPropertyValue<bool>("IsTargetIncrease", ref _IsTargetIncrease, value); }
        }
        bool? _IsSourceIncrease;
        public bool? IsSourceIncrease
        {
            get { return _IsSourceIncrease; }
            set { SetPropertyValue<bool?>("IsSourceIncrease", ref _IsSourceIncrease, value); }
        }
        [Association(@"StockAdjustmentReferencesStockAdjustmentReason", typeof(StockAdjustment))]
        public XPCollection<StockAdjustment> StockAdjustments { get { return GetCollection<StockAdjustment>("StockAdjustments"); } }
    }

}
