//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Inventory
{

    public partial class Style : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        string _Name;
        [Size(150)]
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        string _Code;
        public string Code
        {
            get { return _Code; }
            set { SetPropertyValue<string>("Code", ref _Code, value); }
        }
        StyleGender _Gender;
        [ExplicitLoading(1)]
        [Association(@"StyleReferencesStyleGender")]
        public StyleGender Gender
        {
            get { return _Gender; }
            set { SetPropertyValue<StyleGender>("Gender", ref _Gender, value); }
        }
        StyleCategory _Category;
        [ExplicitLoading(1)]
        [Association(@"StyleReferencesStyleCategory")]
        public StyleCategory Category
        {
            get { return _Category; }
            set { SetPropertyValue<StyleCategory>("Category", ref _Category, value); }
        }
        ProductCategory _ProductCategory;
        [ExplicitLoading(1)]
        [Association(@"StyleReferencesProductCategory")]
        public ProductCategory ProductCategory
        {
            get { return _ProductCategory; }
            set { SetPropertyValue<ProductCategory>("ProductCategory", ref _ProductCategory, value); }
        }
        ProductType _ProductType;
        [ExplicitLoading(1)]
        [Association(@"StyleReferencesProductType")]
        public ProductType ProductType
        {
            get { return _ProductType; }
            set { SetPropertyValue<ProductType>("ProductType", ref _ProductType, value); }
        }
        StyleClass _StyleClass;
        [ExplicitLoading(1)]
        [Association(@"StyleReferencesStyleClass")]
        public StyleClass StyleClass
        {
            get { return _StyleClass; }
            set { SetPropertyValue<StyleClass>("StyleClass", ref _StyleClass, value); }
        }
        Fabric _Fabric;
        [ExplicitLoading(1)]
        [Association(@"StyleReferencesFabric")]
        public Fabric Fabric
        {
            get { return _Fabric; }
            set { SetPropertyValue<Fabric>("Fabric", ref _Fabric, value); }
        }
        string _Content;
        [Size(255)]
        public string Content
        {
            get { return _Content; }
            set { SetPropertyValue<string>("Content", ref _Content, value); }
        }
        string _LongDescription;
        [Size(SizeAttribute.Unlimited)]
        public string LongDescription
        {
            get { return _LongDescription; }
            set { SetPropertyValue<string>("LongDescription", ref _LongDescription, value); }
        }
        StyleDepartment _Department;
        [ExplicitLoading(1)]
        [Association(@"StyleReferencesStyleDepartment")]
        public StyleDepartment Department
        {
            get { return _Department; }
            set { SetPropertyValue<StyleDepartment>("Department", ref _Department, value); }
        }
        Fit _Fit;
        [ExplicitLoading(1)]
        [Association(@"StyleReferencesFit")]
        public Fit Fit
        {
            get { return _Fit; }
            set { SetPropertyValue<Fit>("Fit", ref _Fit, value); }
        }
        SizeRange _SizeRange;
        [ExplicitLoading(1)]
        [Association(@"StyleReferencesSizeRange")]
        public SizeRange SizeRange
        {
            get { return _SizeRange; }
            set { SetPropertyValue<SizeRange>("SizeRange", ref _SizeRange, value); }
        }
        string _Web_Number;
        public string Web_Number
        {
            get { return _Web_Number; }
            set { SetPropertyValue<string>("Web_Number", ref _Web_Number, value); }
        }
        string _Web_Name;
        [Size(150)]
        public string Web_Name
        {
            get { return _Web_Name; }
            set { SetPropertyValue<string>("Web_Name", ref _Web_Name, value); }
        }
        string _Web_Description;
        [Size(SizeAttribute.Unlimited)]
        public string Web_Description
        {
            get { return _Web_Description; }
            set { SetPropertyValue<string>("Web_Description", ref _Web_Description, value); }
        }
        string _Web_LongDescription;
        [Size(SizeAttribute.Unlimited)]
        public string Web_LongDescription
        {
            get { return _Web_LongDescription; }
            set { SetPropertyValue<string>("Web_LongDescription", ref _Web_LongDescription, value); }
        }
        string _Web_Details;
        public string Web_Details
        {
            get { return _Web_Details; }
            set { SetPropertyValue<string>("Web_Details", ref _Web_Details, value); }
        }
        StyleCategory _Web_Category;
        [Association(@"StyleReferencesWebStyleCategory")]
        public StyleCategory Web_Category
        {
            get { return _Web_Category; }
            set { SetPropertyValue<StyleCategory>("Web_Category", ref _Web_Category, value); }
        }
        ProductCategory _Web_ProductCategory;
        [Association(@"StyleReferencesWebProductCategory")]
        public ProductCategory Web_ProductCategory
        {
            get { return _Web_ProductCategory; }
            set { SetPropertyValue<ProductCategory>("Web_ProductCategory", ref _Web_ProductCategory, value); }
        }
        ProductType _Web_ProductType;
        [Association(@"StyleReferencesWebProductType")]
        public ProductType Web_ProductType
        {
            get { return _Web_ProductType; }
            set { SetPropertyValue<ProductType>("Web_ProductType", ref _Web_ProductType, value); }
        }
        StyleClass _Web_StyleClass;
        [Association(@"StyleReferencesWebStyleClass")]
        public StyleClass Web_StyleClass
        {
            get { return _Web_StyleClass; }
            set { SetPropertyValue<StyleClass>("Web_StyleClass", ref _Web_StyleClass, value); }
        }
        string _Web_Industry;
        public string Web_Industry
        {
            get { return _Web_Industry; }
            set { SetPropertyValue<string>("Web_Industry", ref _Web_Industry, value); }
        }
        Fabric _Web_Fabric;
        [Association(@"StyleReferencesWebFabric")]
        public Fabric Web_Fabric
        {
            get { return _Web_Fabric; }
            set { SetPropertyValue<Fabric>("Web_Fabric", ref _Web_Fabric, value); }
        }
        Fit _Web_Fit;
        [Association(@"StyleReferencesWebFit")]
        public Fit Web_Fit
        {
            get { return _Web_Fit; }
            set { SetPropertyValue<Fit>("Web_Fit", ref _Web_Fit, value); }
        }
        string _Web_SizingTable;
        [Size(150)]
        public string Web_SizingTable
        {
            get { return _Web_SizingTable; }
            set { SetPropertyValue<string>("Web_SizingTable", ref _Web_SizingTable, value); }
        }
        SizeRange _Web_SizeRange;
        [Association(@"StyleReferencesWebSizeRange")]
        public SizeRange Web_SizeRange
        {
            get { return _Web_SizeRange; }
            set { SetPropertyValue<SizeRange>("Web_SizeRange", ref _Web_SizeRange, value); }
        }
        string _Web_ImageCode1;
        [Size(255)]
        public string Web_ImageCode1
        {
            get { return _Web_ImageCode1; }
            set { SetPropertyValue<string>("Web_ImageCode1", ref _Web_ImageCode1, value); }
        }
        string _Web_ImageCode2;
        [Size(255)]
        public string Web_ImageCode2
        {
            get { return _Web_ImageCode2; }
            set { SetPropertyValue<string>("Web_ImageCode2", ref _Web_ImageCode2, value); }
        }
        string _Web_ImageCode3;
        [Size(255)]
        public string Web_ImageCode3
        {
            get { return _Web_ImageCode3; }
            set { SetPropertyValue<string>("Web_ImageCode3", ref _Web_ImageCode3, value); }
        }
        long _Reference;
        public long Reference
        {
            get { return _Reference; }
            set { SetPropertyValue<long>("Reference", ref _Reference, value); }
        }
        [Association(@"SkuReferencesStyle", typeof(Sku))]
        public XPCollection<Sku> Skus { get { return GetCollection<Sku>("Skus"); } }
    }

}
