//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Inventory
{

    public partial class WarehouseLocation : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        string _Name;
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        string _Code;
        [Size(10)]
        public string Code
        {
            get { return _Code; }
            set { SetPropertyValue<string>("Code", ref _Code, value); }
        }
        TIG.TotalLink.Shared.DataModel.Crm.Address _Address;
        [TIG.TotalLink.Shared.DataModel.Core.Attribute.RuntimeAssociation("WarehouseLocationReferencesAddress", "WarehouseLocations")]
        public TIG.TotalLink.Shared.DataModel.Crm.Address Address
        {
            get { return _Address; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Crm.Address>("Address", ref _Address, value); }
        }
        [DevExpress.Xpo.Aggregated]
        [Association(@"BinLocationReferencesWarehouseLocation", typeof(BinLocation))]
        public XPCollection<BinLocation> BinLocations { get { return GetCollection<BinLocation>("BinLocations"); } }
    }

}
