using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.Facade.Test;

namespace TIG.TotalLink.Shared.DataModel.Test
{
    [FacadeType(typeof(ITestFacade))]
    [DisplayField("Name")]
    public partial class TestObjectLookUp
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<TestObjectLookUp> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.Name)
                .ContainsProperty(p => p.AltName)
                .ContainsProperty(p => p.TestObjects);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.Name)
                    .ContainsProperty(p => p.AltName)
                .EndGroup()
                .Group("TestObjects")
                    .ContainsProperty(p => p.TestObjects);

            builder.Property(p => p.TestObjects).AutoGenerated();
            builder.Property(p => p.AltTestObjects).AutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<TestObjectLookUp> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Name);

            var testObjectsEditor = new GridEditorDefinition()
            {
                EntityType = typeof(TestObject),
                FilterMethod = context => CriteriaOperator.Parse("LookUp.Oid = ?", ((TestObjectLookUp)context).Oid)
            };
            builder.DataFormEditors().Property(p => p.TestObjects)
                .ReplaceEditor(testObjectsEditor)
                .HideLabel();

            var testObjectsPopupEditor = new PopupGridEditorDefinition()
            {
                EntityType = typeof(TestObject),
                FilterMethod = context => CriteriaOperator.Parse("LookUp.Oid = ?", ((TestObjectLookUp)context).Oid)
            };
            builder.GridBaseColumnEditors().Property(p => p.TestObjects)
                .ReplaceEditor(testObjectsPopupEditor);

            var altTestObjectsEditor = new GridEditorDefinition()
            {
                EntityType = typeof(TestObject),
                FilterMethod = context => CriteriaOperator.Parse("AltLookUp.Oid = ?", ((TestObjectLookUp)context).Oid)
            };
            builder.DataFormEditors().Property(p => p.AltTestObjects)
                .ReplaceEditor(altTestObjectsEditor)
                .HideLabel();

            var altTestObjectsPopupEditor = new PopupGridEditorDefinition()
            {
                EntityType = typeof(TestObject),
                FilterMethod = context => CriteriaOperator.Parse("AltLookUp.Oid = ?", ((TestObjectLookUp)context).Oid)
            };
            builder.GridBaseColumnEditors().Property(p => p.AltTestObjects)
                .ReplaceEditor(altTestObjectsPopupEditor);
        }

        #endregion
    }
}
