//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Purchasing
{

    public partial class PurchaseOrderItem : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        TIG.TotalLink.Shared.DataModel.Inventory.Sku _Sku;
        [TIG.TotalLink.Shared.DataModel.Core.Attribute.RuntimeAssociation("PurchaseOrderItemReferencesSku", "PurchaseOrderItems")]
        public TIG.TotalLink.Shared.DataModel.Inventory.Sku Sku
        {
            get { return _Sku; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Inventory.Sku>("Sku", ref _Sku, value); }
        }
        PurchaseOrder _PurchaseOrder;
        [Association(@"PurchaseOrderItemReferencesPurchaseOrder")]
        public PurchaseOrder PurchaseOrder
        {
            get { return _PurchaseOrder; }
            set { SetPropertyValue<PurchaseOrder>("PurchaseOrder", ref _PurchaseOrder, value); }
        }
        int _Quantity;
        public int Quantity
        {
            get { return _Quantity; }
            set { SetPropertyValue<int>("Quantity", ref _Quantity, value); }
        }
        [Association(@"PurchaseReceiptItemReferencesPurchaseOrderItem", typeof(PurchaseReceiptItem))]
        public XPCollection<PurchaseReceiptItem> PurchaseReceiptItems { get { return GetCollection<PurchaseReceiptItem>("PurchaseReceiptItems"); } }
    }

}
