//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Purchasing
{

    public partial class PurchaseReceiptStatus : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        string _Name;
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        bool _IsCompleted;
        public bool IsCompleted
        {
            get { return _IsCompleted; }
            set { SetPropertyValue<bool>("IsCompleted", ref _IsCompleted, value); }
        }
        [Association(@"PurchaseReceiptReferencesPurchaseReceiptStatus", typeof(PurchaseReceipt))]
        public XPCollection<PurchaseReceipt> PurchaseReceipts { get { return GetCollection<PurchaseReceipt>("PurchaseReceipts"); } }
    }

}
