//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Purchasing
{

    public partial class PurchaseOrder : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        string _Reference;
        public string Reference
        {
            get { return _Reference; }
            set { SetPropertyValue<string>("Reference", ref _Reference, value); }
        }
        TIG.TotalLink.Shared.DataModel.Crm.Contact _Vendor;
        [TIG.TotalLink.Shared.DataModel.Core.Attribute.RuntimeAssociation("PurchaseOrderReferencesContact", "PurchaseOrders")]
        public TIG.TotalLink.Shared.DataModel.Crm.Contact Vendor
        {
            get { return _Vendor; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Crm.Contact>("Vendor", ref _Vendor, value); }
        }
        PurchaseOrderStatus _Status;
        [Association(@"PurchaseOrderReferencesPurchaseOrderStatus")]
        public PurchaseOrderStatus Status
        {
            get { return _Status; }
            set { SetPropertyValue<PurchaseOrderStatus>("Status", ref _Status, value); }
        }
        [DevExpress.Xpo.Aggregated]
        [Association(@"PurchaseOrderItemReferencesPurchaseOrder", typeof(PurchaseOrderItem))]
        public XPCollection<PurchaseOrderItem> PurchaseOrderItems { get { return GetCollection<PurchaseOrderItem>("PurchaseOrderItems"); } }
        [Association(@"PurchaseReceiptReferencesPurchaseOrder", typeof(PurchaseReceipt))]
        public XPCollection<PurchaseReceipt> PurchaseReceipts { get { return GetCollection<PurchaseReceipt>("PurchaseReceipts"); } }
    }

}
