//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Purchasing
{

    public partial class PurchaseReceipt : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        string _Reference;
        [Size(255)]
        public string Reference
        {
            get { return _Reference; }
            set { SetPropertyValue<string>("Reference", ref _Reference, value); }
        }
        PurchaseOrder _PurchaseOrder;
        [Association(@"PurchaseReceiptReferencesPurchaseOrder")]
        public PurchaseOrder PurchaseOrder
        {
            get { return _PurchaseOrder; }
            set { SetPropertyValue<PurchaseOrder>("PurchaseOrder", ref _PurchaseOrder, value); }
        }
        PurchaseReceiptStatus _Status;
        [Association(@"PurchaseReceiptReferencesPurchaseReceiptStatus")]
        public PurchaseReceiptStatus Status
        {
            get { return _Status; }
            set { SetPropertyValue<PurchaseReceiptStatus>("Status", ref _Status, value); }
        }
        [DevExpress.Xpo.Aggregated]
        [Association(@"PurchaseReceiptItemReferencesPurchaseReceipt", typeof(PurchaseReceiptItem))]
        public XPCollection<PurchaseReceiptItem> PurchaseReceiptItems { get { return GetCollection<PurchaseReceiptItem>("PurchaseReceiptItems"); } }
    }

}
