//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Purchasing
{

    public partial class PurchaseReceiptItem : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        TIG.TotalLink.Shared.DataModel.Inventory.Sku _Sku;
        [TIG.TotalLink.Shared.DataModel.Core.Attribute.RuntimeAssociation("PurchaseOrderReceiptItemReferencesSku", "PurchaseOrderReceiptItems")]
        public TIG.TotalLink.Shared.DataModel.Inventory.Sku Sku
        {
            get { return _Sku; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Inventory.Sku>("Sku", ref _Sku, value); }
        }
        PurchaseOrderItem _PurchaseOrderItem;
        [Association(@"PurchaseReceiptItemReferencesPurchaseOrderItem")]
        public PurchaseOrderItem PurchaseOrderItem
        {
            get { return _PurchaseOrderItem; }
            set { SetPropertyValue<PurchaseOrderItem>("PurchaseOrderItem", ref _PurchaseOrderItem, value); }
        }
        PurchaseReceipt _PurchaseReceipt;
        [Association(@"PurchaseReceiptItemReferencesPurchaseReceipt")]
        public PurchaseReceipt PurchaseReceipt
        {
            get { return _PurchaseReceipt; }
            set { SetPropertyValue<PurchaseReceipt>("PurchaseReceipt", ref _PurchaseReceipt, value); }
        }
        int _QuantityReceived;
        public int QuantityReceived
        {
            get { return _QuantityReceived; }
            set { SetPropertyValue<int>("QuantityReceived", ref _QuantityReceived, value); }
        }
        int _QuantityPassedQA;
        public int QuantityPassedQA
        {
            get { return _QuantityPassedQA; }
            set { SetPropertyValue<int>("QuantityPassedQA", ref _QuantityPassedQA, value); }
        }
        int _QuantityFailedQA;
        public int QuantityFailedQA
        {
            get { return _QuantityFailedQA; }
            set { SetPropertyValue<int>("QuantityFailedQA", ref _QuantityFailedQA, value); }
        }
    }

}
