//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Test
{

    public partial class TestObject : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        string _Text;
        public string Text
        {
            get { return _Text; }
            set { SetPropertyValue<string>("Text", ref _Text, value); }
        }
        int _SpinInt;
        public int SpinInt
        {
            get { return _SpinInt; }
            set { SetPropertyValue<int>("SpinInt", ref _SpinInt, value); }
        }
        long? _SpinLong;
        public long? SpinLong
        {
            get { return _SpinLong; }
            set { SetPropertyValue<long?>("SpinLong", ref _SpinLong, value); }
        }
        bool _Checkbox;
        public bool Checkbox
        {
            get { return _Checkbox; }
            set { SetPropertyValue<bool>("Checkbox", ref _Checkbox, value); }
        }
        string _Label;
        public string Label
        {
            get { return _Label; }
            set { SetPropertyValue<string>("Label", ref _Label, value); }
        }
        string _Password;
        public string Password
        {
            get { return _Password; }
            set { SetPropertyValue<string>("Password", ref _Password, value); }
        }
        int _Progress;
        public int Progress
        {
            get { return _Progress; }
            set { SetPropertyValue<int>("Progress", ref _Progress, value); }
        }
        string _RichText;
        [Size(SizeAttribute.Unlimited)]
        public string RichText
        {
            get { return _RichText; }
            set { SetPropertyValue<string>("RichText", ref _RichText, value); }
        }
        DateTime _DateTime;
        public DateTime DateTime
        {
            get { return _DateTime; }
            set { SetPropertyValue<DateTime>("DateTime", ref _DateTime, value); }
        }
        string _HyperLink;
        public string HyperLink
        {
            get { return _HyperLink; }
            set { SetPropertyValue<string>("HyperLink", ref _HyperLink, value); }
        }
        int _IncrementingTime;
        public int IncrementingTime
        {
            get { return _IncrementingTime; }
            set { SetPropertyValue<int>("IncrementingTime", ref _IncrementingTime, value); }
        }
        string _Comments;
        [Size(SizeAttribute.Unlimited)]
        public string Comments
        {
            get { return _Comments; }
            set { SetPropertyValue<string>("Comments", ref _Comments, value); }
        }
        TestObjectLookUp _LookUp;
        [ExplicitLoading(1)]
        [Association(@"TestObjectReferencesTestObjectLookUp")]
        public TestObjectLookUp LookUp
        {
            get { return _LookUp; }
            set { SetPropertyValue<TestObjectLookUp>("LookUp", ref _LookUp, value); }
        }
        TestObjectLookUp _AltLookUp;
        [ExplicitLoading(1)]
        [Association(@"TestObjectReferencesTestObjectLookUpAlt")]
        public TestObjectLookUp AltLookUp
        {
            get { return _AltLookUp; }
            set { SetPropertyValue<TestObjectLookUp>("AltLookUp", ref _AltLookUp, value); }
        }
        string _Memo;
        [Size(SizeAttribute.Unlimited)]
        public string Memo
        {
            get { return _Memo; }
            set { SetPropertyValue<string>("Memo", ref _Memo, value); }
        }
        decimal _Currency;
        public decimal Currency
        {
            get { return _Currency; }
            set { SetPropertyValue<decimal>("Currency", ref _Currency, value); }
        }
        decimal _Decimal;
        public decimal Decimal
        {
            get { return _Decimal; }
            set { SetPropertyValue<decimal>("Decimal", ref _Decimal, value); }
        }
        TIG.TotalLink.Shared.DataModel.Core.Enum.Test.TestEnum _Option;
        public TIG.TotalLink.Shared.DataModel.Core.Enum.Test.TestEnum Option
        {
            get { return _Option; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Core.Enum.Test.TestEnum>("Option", ref _Option, value); }
        }
        TIG.TotalLink.Shared.DataModel.Core.Enum.Test.TestEnum _Combo;
        public TIG.TotalLink.Shared.DataModel.Core.Enum.Test.TestEnum Combo
        {
            get { return _Combo; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Core.Enum.Test.TestEnum>("Combo", ref _Combo, value); }
        }
        [Association(@"TestObjectGridReferencesTestObject", typeof(TestObjectGrid))]
        public XPCollection<TestObjectGrid> TestObjectGrids { get { return GetCollection<TestObjectGrid>("TestObjectGrids"); } }
    }

}
