//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Test
{

    public partial class TestObjectGrid : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        string _Name;
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        TestObject _TestObject;
        [Association(@"TestObjectGridReferencesTestObject")]
        public TestObject TestObject
        {
            get { return _TestObject; }
            set { SetPropertyValue<TestObject>("TestObject", ref _TestObject, value); }
        }
    }

}
