//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Test
{

    public partial class TestObjectLookUp : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        string _Name;
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        string _AltName;
        public string AltName
        {
            get { return _AltName; }
            set { SetPropertyValue<string>("AltName", ref _AltName, value); }
        }
        [Association(@"TestObjectReferencesTestObjectLookUp", typeof(TestObject))]
        public XPCollection<TestObject> TestObjects { get { return GetCollection<TestObject>("TestObjects"); } }
        [Association(@"TestObjectReferencesTestObjectLookUpAlt", typeof(TestObject))]
        public XPCollection<TestObject> AltTestObjects { get { return GetCollection<TestObject>("AltTestObjects"); } }
    }

}
