//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Crm
{

    public partial class Address : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        string _Label;
        public string Label
        {
            get { return _Label; }
            set { SetPropertyValue<string>("Label", ref _Label, value); }
        }
        bool _IsDefault;
        public bool IsDefault
        {
            get { return _IsDefault; }
            set { SetPropertyValue<bool>("IsDefault", ref _IsDefault, value); }
        }
        string _AttentionTo;
        public string AttentionTo
        {
            get { return _AttentionTo; }
            set { SetPropertyValue<string>("AttentionTo", ref _AttentionTo, value); }
        }
        UnitType _UnitType;
        [ExplicitLoading(1)]
        [Association(@"AddressReferencesUnitType")]
        public UnitType UnitType
        {
            get { return _UnitType; }
            set { SetPropertyValue<UnitType>("UnitType", ref _UnitType, value); }
        }
        string _UnitNumber;
        [Size(10)]
        public string UnitNumber
        {
            get { return _UnitNumber; }
            set { SetPropertyValue<string>("UnitNumber", ref _UnitNumber, value); }
        }
        string _StreetNumber;
        [Size(10)]
        public string StreetNumber
        {
            get { return _StreetNumber; }
            set { SetPropertyValue<string>("StreetNumber", ref _StreetNumber, value); }
        }
        string _StreetName;
        public string StreetName
        {
            get { return _StreetName; }
            set { SetPropertyValue<string>("StreetName", ref _StreetName, value); }
        }
        StreetType _StreetType;
        [ExplicitLoading(1)]
        [Association(@"AddressReferencesStreetType")]
        public StreetType StreetType
        {
            get { return _StreetType; }
            set { SetPropertyValue<StreetType>("StreetType", ref _StreetType, value); }
        }
        string _LegacyLine1;
        [Size(255)]
        public string LegacyLine1
        {
            get { return _LegacyLine1; }
            set { SetPropertyValue<string>("LegacyLine1", ref _LegacyLine1, value); }
        }
        string _LegacyLine2;
        [Size(255)]
        public string LegacyLine2
        {
            get { return _LegacyLine2; }
            set { SetPropertyValue<string>("LegacyLine2", ref _LegacyLine2, value); }
        }
        string _City;
        public string City
        {
            get { return _City; }
            set { SetPropertyValue<string>("City", ref _City, value); }
        }
        AddressValidationApi _ValidationAPI;
        [ExplicitLoading(1)]
        [Association(@"AddressReferencesAddressValidationAPI")]
        public AddressValidationApi ValidationAPI
        {
            get { return _ValidationAPI; }
            set { SetPropertyValue<AddressValidationApi>("ValidationAPI", ref _ValidationAPI, value); }
        }
        DateTime _ValidationDate;
        public DateTime ValidationDate
        {
            get { return _ValidationDate; }
            set { SetPropertyValue<DateTime>("ValidationDate", ref _ValidationDate, value); }
        }
        string _CompanyName;
        public string CompanyName
        {
            get { return _CompanyName; }
            set { SetPropertyValue<string>("CompanyName", ref _CompanyName, value); }
        }
        decimal _Longitude;
        [DbType("decimal(9,6)")]
        public decimal Longitude
        {
            get { return _Longitude; }
            set { SetPropertyValue<decimal>("Longitude", ref _Longitude, value); }
        }
        decimal _Latitude;
        [DbType("decimal(9,6)")]
        public decimal Latitude
        {
            get { return _Latitude; }
            set { SetPropertyValue<decimal>("Latitude", ref _Latitude, value); }
        }
        AddressType _AddressType;
        [ExplicitLoading(1)]
        [Association(@"AddressReferencesAddressType")]
        public AddressType AddressType
        {
            get { return _AddressType; }
            set { SetPropertyValue<AddressType>("AddressType", ref _AddressType, value); }
        }
        Contact _Contact;
        [ExplicitLoading(1)]
        [Association(@"AddressReferencesContact")]
        public Contact Contact
        {
            get { return _Contact; }
            set { SetPropertyValue<Contact>("Contact", ref _Contact, value); }
        }
        TIG.TotalLink.Shared.DataModel.Admin.Postcode _Postcode;
        [ExplicitLoading(1)]
        [TIG.TotalLink.Shared.DataModel.Core.Attribute.RuntimeAssociation("AddressReferencesPostcode", "Addresses")]
        public TIG.TotalLink.Shared.DataModel.Admin.Postcode Postcode
        {
            get { return _Postcode; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Admin.Postcode>("Postcode", ref _Postcode, value); }
        }
    }

}
