//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Crm
{

    public partial class AddressValidationApi : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        string _Name;
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        string _Webpage;
        [Size(255)]
        public string Webpage
        {
            get { return _Webpage; }
            set { SetPropertyValue<string>("Webpage", ref _Webpage, value); }
        }
        string _BaseUrl;
        [Size(255)]
        public string BaseUrl
        {
            get { return _BaseUrl; }
            set { SetPropertyValue<string>("BaseUrl", ref _BaseUrl, value); }
        }
        [Association(@"AddressReferencesAddressValidationAPI", typeof(Address))]
        public XPCollection<Address> Addresses { get { return GetCollection<Address>("Addresses"); } }
    }

}
