//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Crm
{

    [MapInheritance(MapInheritanceType.ParentTable)]
    public partial class Branch : Business
    {
        string _BranchNumber;
        [Size(20)]
        public string BranchNumber
        {
            get { return _BranchNumber; }
            set { SetPropertyValue<string>("BranchNumber", ref _BranchNumber, value); }
        }
        BranchType _BranchType;
        [ExplicitLoading(1)]
        [Association(@"BranchReferencesBranchType")]
        public BranchType BranchType
        {
            get { return _BranchType; }
            set { SetPropertyValue<BranchType>("BranchType", ref _BranchType, value); }
        }
    }

}
