//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Crm
{

    [MapInheritance(MapInheritanceType.ParentTable)]
    public partial class Business : Contact
    {
        int _TotalStores;
        public int TotalStores
        {
            get { return _TotalStores; }
            set { SetPropertyValue<int>("TotalStores", ref _TotalStores, value); }
        }
        int _TotalEmployees;
        public int TotalEmployees
        {
            get { return _TotalEmployees; }
            set { SetPropertyValue<int>("TotalEmployees", ref _TotalEmployees, value); }
        }
        GlobalRegion _GlobalRegion;
        [ExplicitLoading(1)]
        [Association(@"BusinessReferencesGlobalRegion")]
        public GlobalRegion GlobalRegion
        {
            get { return _GlobalRegion; }
            set { SetPropertyValue<GlobalRegion>("GlobalRegion", ref _GlobalRegion, value); }
        }
    }

}
