//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Crm
{

    public partial class Contact : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        long _Reference;
        public long Reference
        {
            get { return _Reference; }
            set { SetPropertyValue<long>("Reference", ref _Reference, value); }
        }
        string _LegacyReference;
        public string LegacyReference
        {
            get { return _LegacyReference; }
            set { SetPropertyValue<string>("LegacyReference", ref _LegacyReference, value); }
        }
        string _ExternalReference;
        public string ExternalReference
        {
            get { return _ExternalReference; }
            set { SetPropertyValue<string>("ExternalReference", ref _ExternalReference, value); }
        }
        decimal _CreditLimit;
        public decimal CreditLimit
        {
            get { return _CreditLimit; }
            set { SetPropertyValue<decimal>("CreditLimit", ref _CreditLimit, value); }
        }
        IndustryClass _IndustryClass;
        [ExplicitLoading(1)]
        [Association(@"ContactReferencesIndustryClass")]
        public IndustryClass IndustryClass
        {
            get { return _IndustryClass; }
            set { SetPropertyValue<IndustryClass>("IndustryClass", ref _IndustryClass, value); }
        }
        string _Email;
        [Size(255)]
        public string Email
        {
            get { return _Email; }
            set { SetPropertyValue<string>("Email", ref _Email, value); }
        }
        string _Webpage;
        [Size(255)]
        public string Webpage
        {
            get { return _Webpage; }
            set { SetPropertyValue<string>("Webpage", ref _Webpage, value); }
        }
        Currency _Currency;
        [ExplicitLoading(1)]
        [Association(@"ContactReferencesCurrencies")]
        public Currency Currency
        {
            get { return _Currency; }
            set { SetPropertyValue<Currency>("Currency", ref _Currency, value); }
        }
        Language _Language;
        [ExplicitLoading(1)]
        [Association(@"ContactReferencesLanguages")]
        public Language Language
        {
            get { return _Language; }
            set { SetPropertyValue<Language>("Language", ref _Language, value); }
        }
        string _FirstName;
        public string FirstName
        {
            get { return _FirstName; }
            set { SetPropertyValue<string>("FirstName", ref _FirstName, value); }
        }
        string _Fax;
        [Size(30)]
        public string Fax
        {
            get { return _Fax; }
            set { SetPropertyValue<string>("Fax", ref _Fax, value); }
        }
        string _BusinessPhone;
        [Size(30)]
        public string BusinessPhone
        {
            get { return _BusinessPhone; }
            set { SetPropertyValue<string>("BusinessPhone", ref _BusinessPhone, value); }
        }
        string _BusinessPhone2;
        [Size(30)]
        public string BusinessPhone2
        {
            get { return _BusinessPhone2; }
            set { SetPropertyValue<string>("BusinessPhone2", ref _BusinessPhone2, value); }
        }
        string _BusinessFax;
        [Size(30)]
        public string BusinessFax
        {
            get { return _BusinessFax; }
            set { SetPropertyValue<string>("BusinessFax", ref _BusinessFax, value); }
        }
        string _BusinessMobile;
        [Size(30)]
        public string BusinessMobile
        {
            get { return _BusinessMobile; }
            set { SetPropertyValue<string>("BusinessMobile", ref _BusinessMobile, value); }
        }
        string _Facebook;
        [Size(255)]
        public string Facebook
        {
            get { return _Facebook; }
            set { SetPropertyValue<string>("Facebook", ref _Facebook, value); }
        }
        string _Twitter;
        [Size(255)]
        public string Twitter
        {
            get { return _Twitter; }
            set { SetPropertyValue<string>("Twitter", ref _Twitter, value); }
        }
        string _InternetChat;
        [Size(255)]
        public string InternetChat
        {
            get { return _InternetChat; }
            set { SetPropertyValue<string>("InternetChat", ref _InternetChat, value); }
        }
        ChatType _InternetChatType;
        [ExplicitLoading(1)]
        [Association(@"ContactReferencesChatType")]
        public ChatType InternetChatType
        {
            get { return _InternetChatType; }
            set { SetPropertyValue<ChatType>("InternetChatType", ref _InternetChatType, value); }
        }
        TIG.TotalLink.Shared.DataModel.Core.Enum.CRM.BlockType? _Blocked;
        public TIG.TotalLink.Shared.DataModel.Core.Enum.CRM.BlockType? Blocked
        {
            get { return _Blocked; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Core.Enum.CRM.BlockType?>("Blocked", ref _Blocked, value); }
        }
        string _BlockedReason;
        [Size(SizeAttribute.Unlimited)]
        public string BlockedReason
        {
            get { return _BlockedReason; }
            set { SetPropertyValue<string>("BlockedReason", ref _BlockedReason, value); }
        }
        bool _AllowLineDiscount;
        public bool AllowLineDiscount
        {
            get { return _AllowLineDiscount; }
            set { SetPropertyValue<bool>("AllowLineDiscount", ref _AllowLineDiscount, value); }
        }
        bool _GSTIncluded;
        public bool GSTIncluded
        {
            get { return _GSTIncluded; }
            set { SetPropertyValue<bool>("GSTIncluded", ref _GSTIncluded, value); }
        }
        decimal _PrepaymentPercent;
        public decimal PrepaymentPercent
        {
            get { return _PrepaymentPercent; }
            set { SetPropertyValue<decimal>("PrepaymentPercent", ref _PrepaymentPercent, value); }
        }
        bool _BackOrderNotAccepted;
        public bool BackOrderNotAccepted
        {
            get { return _BackOrderNotAccepted; }
            set { SetPropertyValue<bool>("BackOrderNotAccepted", ref _BackOrderNotAccepted, value); }
        }
        PaymentTerms _PaymentTerms;
        [ExplicitLoading(1)]
        [Association(@"ContactPaymentTermsReferencesPaymentTerms")]
        public PaymentTerms PaymentTerms
        {
            get { return _PaymentTerms; }
            set { SetPropertyValue<PaymentTerms>("PaymentTerms", ref _PaymentTerms, value); }
        }
        ReminderTerms _ReminderTerms;
        [ExplicitLoading(1)]
        [Association(@"ContactReferencesReminderTerms")]
        public ReminderTerms ReminderTerms
        {
            get { return _ReminderTerms; }
            set { SetPropertyValue<ReminderTerms>("ReminderTerms", ref _ReminderTerms, value); }
        }
        PaymentTerms _CashFlowPaymentTerms;
        [ExplicitLoading(1)]
        [Association(@"ContactCashFlowPaymentTermsReferencesPaymentTerms")]
        public PaymentTerms CashFlowPaymentTerms
        {
            get { return _CashFlowPaymentTerms; }
            set { SetPropertyValue<PaymentTerms>("CashFlowPaymentTerms", ref _CashFlowPaymentTerms, value); }
        }
        string _ACN;
        [Size(30)]
        public string ACN
        {
            get { return _ACN; }
            set { SetPropertyValue<string>("ACN", ref _ACN, value); }
        }
        string _ABN;
        [Size(11)]
        public string ABN
        {
            get { return _ABN; }
            set { SetPropertyValue<string>("ABN", ref _ABN, value); }
        }
        bool _CompanyRegistered;
        public bool CompanyRegistered
        {
            get { return _CompanyRegistered; }
            set { SetPropertyValue<bool>("CompanyRegistered", ref _CompanyRegistered, value); }
        }
        PaymentMethod _PaymentMethod;
        [ExplicitLoading(1)]
        [Association(@"ContactReferencesPaymentMethod")]
        public PaymentMethod PaymentMethod
        {
            get { return _PaymentMethod; }
            set { SetPropertyValue<PaymentMethod>("PaymentMethod", ref _PaymentMethod, value); }
        }
        OwnershipType _OwnershipType;
        [ExplicitLoading(1)]
        [Association(@"ContactReferencesOwnershipType")]
        public OwnershipType OwnershipType
        {
            get { return _OwnershipType; }
            set { SetPropertyValue<OwnershipType>("OwnershipType", ref _OwnershipType, value); }
        }
        string _BusinessExtension;
        [Size(10)]
        public string BusinessExtension
        {
            get { return _BusinessExtension; }
            set { SetPropertyValue<string>("BusinessExtension", ref _BusinessExtension, value); }
        }
        string _SearchName;
        [Size(255)]
        public string SearchName
        {
            get { return _SearchName; }
            set { SetPropertyValue<string>("SearchName", ref _SearchName, value); }
        }
        [PersistentAlias("0.0m")]
        public decimal Balance
        {
            get { return (decimal)(EvaluateAlias("Balance")); }
        }
        BusinessType _BusinessType;
        [ExplicitLoading(1)]
        [Association(@"ContactReferencesBusinessType")]
        public BusinessType BusinessType
        {
            get { return _BusinessType; }
            set { SetPropertyValue<BusinessType>("BusinessType", ref _BusinessType, value); }
        }
        TIG.TotalLink.Shared.DataModel.Admin.PostingGroup _GSTBusinessPostingGroup;
        [TIG.TotalLink.Shared.DataModel.Core.Attribute.RuntimeAssociation("ContactReferencesGSTBusinessPostingGroup", "GSTBusinessPostingGroups")]
        public TIG.TotalLink.Shared.DataModel.Admin.PostingGroup GSTBusinessPostingGroup
        {
            get { return _GSTBusinessPostingGroup; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Admin.PostingGroup>("GSTBusinessPostingGroup", ref _GSTBusinessPostingGroup, value); }
        }
        TIG.TotalLink.Shared.DataModel.Admin.PostingGroup _GeneralBusinessPostingGroup;
        [TIG.TotalLink.Shared.DataModel.Core.Attribute.RuntimeAssociation("ContactReferencesGeneralBusinessPostingGroup", "GeneralBusinessPostingGroups")]
        public TIG.TotalLink.Shared.DataModel.Admin.PostingGroup GeneralBusinessPostingGroup
        {
            get { return _GeneralBusinessPostingGroup; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Admin.PostingGroup>("GeneralBusinessPostingGroup", ref _GeneralBusinessPostingGroup, value); }
        }
        TIG.TotalLink.Shared.DataModel.Admin.PostingGroup _ContactPostingGroup;
        [TIG.TotalLink.Shared.DataModel.Core.Attribute.RuntimeAssociation("ContactReferencesContactPostingGroup", "ContactPostingGroups")]
        public TIG.TotalLink.Shared.DataModel.Admin.PostingGroup ContactPostingGroup
        {
            get { return _ContactPostingGroup; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Admin.PostingGroup>("ContactPostingGroup", ref _ContactPostingGroup, value); }
        }
        ShipmentMethod _ShipmentMethod;
        [Association(@"ContactReferencesShipmentMethod")]
        public ShipmentMethod ShipmentMethod
        {
            get { return _ShipmentMethod; }
            set { SetPropertyValue<ShipmentMethod>("ShipmentMethod", ref _ShipmentMethod, value); }
        }
        bool _AllowPartialDelivery;
        public bool AllowPartialDelivery
        {
            get { return _AllowPartialDelivery; }
            set { SetPropertyValue<bool>("AllowPartialDelivery", ref _AllowPartialDelivery, value); }
        }
        [PersistentAlias("Replace([ObjectType.TypeName], 'TIG.TotalLink.Shared.DataModel.Crm.', '')")]
        public string ContactType
        {
            get { return (string)(EvaluateAlias("ContactType")); }
        }
        bool _IsVendor;
        public bool IsVendor
        {
            get { return _IsVendor; }
            set { SetPropertyValue<bool>("IsVendor", ref _IsVendor, value); }
        }
        string _LegacySource;
        [Size(30)]
        public string LegacySource
        {
            get { return _LegacySource; }
            set { SetPropertyValue<string>("LegacySource", ref _LegacySource, value); }
        }
        [DevExpress.Xpo.Aggregated]
        [Association(@"AddressReferencesContact", typeof(Address))]
        public XPCollection<Address> Addresses { get { return GetCollection<Address>("Addresses"); } }
        [DevExpress.Xpo.Aggregated]
        [Association(@"ContactLinkReferencesSourceContact", typeof(ContactLink))]
        public XPCollection<ContactLink> SourceContactLinks { get { return GetCollection<ContactLink>("SourceContactLinks"); } }
        [DevExpress.Xpo.Aggregated]
        [Association(@"ContactLinkReferencesTargetContact", typeof(ContactLink))]
        public XPCollection<ContactLink> TargetContactLinks { get { return GetCollection<ContactLink>("TargetContactLinks"); } }
        [DevExpress.Xpo.Aggregated]
        [Association(@"ContactGroupLinkReferencesContact", typeof(ContactGroupLink))]
        public XPCollection<ContactGroupLink> ContactGroupLinks { get { return GetCollection<ContactGroupLink>("ContactGroupLinks"); } }
    }

}
