//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Crm
{

    public partial class ContactGroupLink : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        ContactGroup _ContactGroup;
        [ExplicitLoading(1)]
        [Association(@"ContactGroupLinkReferencesContactGroup")]
        public ContactGroup ContactGroup
        {
            get { return _ContactGroup; }
            set { SetPropertyValue<ContactGroup>("ContactGroup", ref _ContactGroup, value); }
        }
        Contact _Contact;
        [ExplicitLoading(1)]
        [Association(@"ContactGroupLinkReferencesContact")]
        public Contact Contact
        {
            get { return _Contact; }
            set { SetPropertyValue<Contact>("Contact", ref _Contact, value); }
        }
        bool _IsPrimary;
        public bool IsPrimary
        {
            get { return _IsPrimary; }
            set { SetPropertyValue<bool>("IsPrimary", ref _IsPrimary, value); }
        }
    }

}
