//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Crm
{

    public partial class ContactLink : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        Contact _Source;
        [ExplicitLoading(1)]
        [Association(@"ContactLinkReferencesSourceContact")]
        public Contact Source
        {
            get { return _Source; }
            set { SetPropertyValue<Contact>("Source", ref _Source, value); }
        }
        Contact _Target;
        [ExplicitLoading(1)]
        [Association(@"ContactLinkReferencesTargetContact")]
        public Contact Target
        {
            get { return _Target; }
            set { SetPropertyValue<Contact>("Target", ref _Target, value); }
        }
        ContactLinkType _ContactLinkType;
        [ExplicitLoading(1)]
        [Association(@"ContactLinkReferencesContactLinkType")]
        public ContactLinkType ContactLinkType
        {
            get { return _ContactLinkType; }
            set { SetPropertyValue<ContactLinkType>("ContactLinkType", ref _ContactLinkType, value); }
        }
    }

}
