//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Crm
{

    public partial class ExchangeRate : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        Currency _Currency;
        [Association(@"ExchangeRateReferencesCurrency")]
        public Currency Currency
        {
            get { return _Currency; }
            set { SetPropertyValue<Currency>("Currency", ref _Currency, value); }
        }
        decimal _CurrentRate;
        public decimal CurrentRate
        {
            get { return _CurrentRate; }
            set { SetPropertyValue<decimal>("CurrentRate", ref _CurrentRate, value); }
        }
        decimal _Adjustment;
        public decimal Adjustment
        {
            get { return _Adjustment; }
            set { SetPropertyValue<decimal>("Adjustment", ref _Adjustment, value); }
        }
        [PersistentAlias("CurrentRate+Adjustment")]
        public decimal AdjustmentRate
        {
            get { return (decimal)(EvaluateAlias("AdjustmentRate")); }
        }
    }

}
