//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Crm
{

    public partial class Language : TIG.TotalLink.Shared.DataModel.Admin.StampedDataObjectBase
    {
        string _Code;
        [Size(10)]
        public string Code
        {
            get { return _Code; }
            set { SetPropertyValue<string>("Code", ref _Code, value); }
        }
        string _Name;
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        int _WindowsLanguageID;
        public int WindowsLanguageID
        {
            get { return _WindowsLanguageID; }
            set { SetPropertyValue<int>("WindowsLanguageID", ref _WindowsLanguageID, value); }
        }
        string _WindowsLanguageName;
        [Size(80)]
        public string WindowsLanguageName
        {
            get { return _WindowsLanguageName; }
            set { SetPropertyValue<string>("WindowsLanguageName", ref _WindowsLanguageName, value); }
        }
        [Association(@"ContactReferencesLanguages", typeof(Contact))]
        public XPCollection<Contact> Contacts { get { return GetCollection<Contact>("Contacts"); } }
    }

}
