//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Repository
{

    public partial class DataStore : TIG.TotalLink.Shared.DataModel.Core.DataObjectBase
    {
        TIG.TotalLink.Shared.DataModel.Core.Enum.Repository.DatabaseProvider _DatabaseProvider;
        public TIG.TotalLink.Shared.DataModel.Core.Enum.Repository.DatabaseProvider DatabaseProvider
        {
            get { return _DatabaseProvider; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Core.Enum.Repository.DatabaseProvider>("DatabaseProvider", ref _DatabaseProvider, value); }
        }
        string _Server;
        public string Server
        {
            get { return _Server; }
            set { SetPropertyValue<string>("Server", ref _Server, value); }
        }
        string _DatabaseName;
        public string DatabaseName
        {
            get { return _DatabaseName; }
            set { SetPropertyValue<string>("DatabaseName", ref _DatabaseName, value); }
        }
        bool _IntegratedSecurity;
        public bool IntegratedSecurity
        {
            get { return _IntegratedSecurity; }
            set { SetPropertyValue<bool>("IntegratedSecurity", ref _IntegratedSecurity, value); }
        }
        string _UserName;
        public string UserName
        {
            get { return _UserName; }
            set { SetPropertyValue<string>("UserName", ref _UserName, value); }
        }
        string _Password;
        public string Password
        {
            get { return _Password; }
            set { SetPropertyValue<string>("Password", ref _Password, value); }
        }
        double _DataFileSizeLimit;
        public double DataFileSizeLimit
        {
            get { return _DataFileSizeLimit; }
            set { SetPropertyValue<double>("DataFileSizeLimit", ref _DataFileSizeLimit, value); }
        }
        FileExtensionGroup _FileExtensionGroup;
        [Association(@"DataStoreReferencesFileExtensionGroup")]
        public FileExtensionGroup FileExtensionGroup
        {
            get { return _FileExtensionGroup; }
            set { SetPropertyValue<FileExtensionGroup>("FileExtensionGroup", ref _FileExtensionGroup, value); }
        }
        TIG.TotalLink.Shared.DataModel.Core.Enum.Repository.RepositoryType _Type;
        public TIG.TotalLink.Shared.DataModel.Core.Enum.Repository.RepositoryType Type
        {
            get { return _Type; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Core.Enum.Repository.RepositoryType>("Type", ref _Type, value); }
        }
        bool _IsDefault;
        public bool IsDefault
        {
            get { return _IsDefault; }
            set { SetPropertyValue<bool>("IsDefault", ref _IsDefault, value); }
        }
        [Association(@"FileVersionReferencesDataStore", typeof(FileVersion))]
        public XPCollection<FileVersion> FileVersions { get { return GetCollection<FileVersion>("FileVersions"); } }
    }

}
