//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Repository
{

    public partial class FileGroup : TIG.TotalLink.Shared.DataModel.Core.DataObjectBase
    {
        string _Name;
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        string _Description;
        public string Description
        {
            get { return _Description; }
            set { SetPropertyValue<string>("Description", ref _Description, value); }
        }
        int _LastVersion;
        public int LastVersion
        {
            get { return _LastVersion; }
            set { SetPropertyValue<int>("LastVersion", ref _LastVersion, value); }
        }
        [Association(@"FileBinderVersionReferencesFileGroup", typeof(FileBinderVersion))]
        public XPCollection<FileBinderVersion> FileBinderVersions { get { return GetCollection<FileBinderVersion>("FileBinderVersions"); } }
        [Association(@"FileGroupVersionReferencesFileGroup", typeof(FileGroupVersion))]
        public XPCollection<FileGroupVersion> FileGroupVersions { get { return GetCollection<FileGroupVersion>("FileGroupVersions"); } }
    }

}
