//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Repository
{

    public partial class File : TIG.TotalLink.Shared.DataModel.Core.DataObjectBase
    {
        string _Name;
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        bool _Searchable;
        public bool Searchable
        {
            get { return _Searchable; }
            set { SetPropertyValue<bool>("Searchable", ref _Searchable, value); }
        }
        string _Notes;
        public string Notes
        {
            get { return _Notes; }
            set { SetPropertyValue<string>("Notes", ref _Notes, value); }
        }
        string _Barcode;
        public string Barcode
        {
            get { return _Barcode; }
            set { SetPropertyValue<string>("Barcode", ref _Barcode, value); }
        }
        string _Comments;
        public string Comments
        {
            get { return _Comments; }
            set { SetPropertyValue<string>("Comments", ref _Comments, value); }
        }
        string _Description;
        public string Description
        {
            get { return _Description; }
            set { SetPropertyValue<string>("Description", ref _Description, value); }
        }
        bool _ActionableItem;
        public bool ActionableItem
        {
            get { return _ActionableItem; }
            set { SetPropertyValue<bool>("ActionableItem", ref _ActionableItem, value); }
        }
        DateTime _CreatedOn;
        public DateTime CreatedOn
        {
            get { return _CreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref _CreatedOn, value); }
        }
        Guid _CreateBy;
        public Guid CreateBy
        {
            get { return _CreateBy; }
            set { SetPropertyValue<Guid>("CreateBy", ref _CreateBy, value); }
        }
        DateTime _UpdateOn;
        public DateTime UpdateOn
        {
            get { return _UpdateOn; }
            set { SetPropertyValue<DateTime>("UpdateOn", ref _UpdateOn, value); }
        }
        Guid _UpdateBy;
        public Guid UpdateBy
        {
            get { return _UpdateBy; }
            set { SetPropertyValue<Guid>("UpdateBy", ref _UpdateBy, value); }
        }
        DateTime? _DataReceived;
        public DateTime? DataReceived
        {
            get { return _DataReceived; }
            set { SetPropertyValue<DateTime?>("DataReceived", ref _DataReceived, value); }
        }
        string _ApprovedOn;
        public string ApprovedOn
        {
            get { return _ApprovedOn; }
            set { SetPropertyValue<string>("ApprovedOn", ref _ApprovedOn, value); }
        }
        Guid? _ApprovedBy;
        public Guid? ApprovedBy
        {
            get { return _ApprovedBy; }
            set { SetPropertyValue<Guid?>("ApprovedBy", ref _ApprovedBy, value); }
        }
        DateTime _CheckOutOn;
        public DateTime CheckOutOn
        {
            get { return _CheckOutOn; }
            set { SetPropertyValue<DateTime>("CheckOutOn", ref _CheckOutOn, value); }
        }
        string _CheckOutBy;
        public string CheckOutBy
        {
            get { return _CheckOutBy; }
            set { SetPropertyValue<string>("CheckOutBy", ref _CheckOutBy, value); }
        }
        bool _Confidential;
        public bool Confidential
        {
            get { return _Confidential; }
            set { SetPropertyValue<bool>("Confidential", ref _Confidential, value); }
        }
        string _EmailFrom;
        public string EmailFrom
        {
            get { return _EmailFrom; }
            set { SetPropertyValue<string>("EmailFrom", ref _EmailFrom, value); }
        }
        string _EmailTo;
        public string EmailTo
        {
            get { return _EmailTo; }
            set { SetPropertyValue<string>("EmailTo", ref _EmailTo, value); }
        }
        string _EmailCc;
        public string EmailCc
        {
            get { return _EmailCc; }
            set { SetPropertyValue<string>("EmailCc", ref _EmailCc, value); }
        }
        string _EmailSubject;
        public string EmailSubject
        {
            get { return _EmailSubject; }
            set { SetPropertyValue<string>("EmailSubject", ref _EmailSubject, value); }
        }
        string _EmailBody;
        public string EmailBody
        {
            get { return _EmailBody; }
            set { SetPropertyValue<string>("EmailBody", ref _EmailBody, value); }
        }
        int? _EmailAttachments;
        public int? EmailAttachments
        {
            get { return _EmailAttachments; }
            set { SetPropertyValue<int?>("EmailAttachments", ref _EmailAttachments, value); }
        }
        int _LastVersion;
        public int LastVersion
        {
            get { return _LastVersion; }
            set { SetPropertyValue<int>("LastVersion", ref _LastVersion, value); }
        }
        DateTime? _DeleteOn;
        public DateTime? DeleteOn
        {
            get { return _DeleteOn; }
            set { SetPropertyValue<DateTime?>("DeleteOn", ref _DeleteOn, value); }
        }
        FileExtension _Extension;
        [Association(@"FileReferencesFileExtension")]
        public FileExtension Extension
        {
            get { return _Extension; }
            set { SetPropertyValue<FileExtension>("Extension", ref _Extension, value); }
        }
        string _IsRecord;
        public string IsRecord
        {
            get { return _IsRecord; }
            set { SetPropertyValue<string>("IsRecord", ref _IsRecord, value); }
        }
        RecordMetadata _RecordMetadata;
        [Association(@"FileReferencesRecordMetadata")]
        public RecordMetadata RecordMetadata
        {
            get { return _RecordMetadata; }
            set { SetPropertyValue<RecordMetadata>("RecordMetadata", ref _RecordMetadata, value); }
        }
        Category _Category;
        [Association(@"FileReferencesFirstCategory")]
        public Category Category
        {
            get { return _Category; }
            set { SetPropertyValue<Category>("Category", ref _Category, value); }
        }
        [Association(@"FileBinderVersionReferencesFile", typeof(FileBinderVersion))]
        public XPCollection<FileBinderVersion> FileBinderVersions { get { return GetCollection<FileBinderVersion>("FileBinderVersions"); } }
        [Association(@"FileGroupVersionReferencesFile", typeof(FileGroupVersion))]
        public XPCollection<FileGroupVersion> FileGroupVersions { get { return GetCollection<FileGroupVersion>("FileGroupVersions"); } }
        [Association(@"FileReferencesFilterOption", typeof(FilterOption))]
        public XPCollection<FilterOption> FilterOptions { get { return GetCollection<FilterOption>("FilterOptions"); } }
        [Association(@"FileVersionReferencesFile", typeof(FileVersion))]
        public XPCollection<FileVersion> FileVersions { get { return GetCollection<FileVersion>("FileVersions"); } }
    }

}
