//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Repository
{

    public partial class FileVersion : TIG.TotalLink.Shared.DataModel.Core.DataObjectBase
    {
        string _Server;
        public string Server
        {
            get { return _Server; }
            set { SetPropertyValue<string>("Server", ref _Server, value); }
        }
        Guid _FileDataID;
        public Guid FileDataID
        {
            get { return _FileDataID; }
            set { SetPropertyValue<Guid>("FileDataID", ref _FileDataID, value); }
        }
        int _Version;
        public int Version
        {
            get { return _Version; }
            set { SetPropertyValue<int>("Version", ref _Version, value); }
        }
        File _File;
        [Association(@"FileVersionReferencesFile")]
        public File File
        {
            get { return _File; }
            set { SetPropertyValue<File>("File", ref _File, value); }
        }
        DataStore _DataStore;
        [Association(@"FileVersionReferencesDataStore")]
        public DataStore DataStore
        {
            get { return _DataStore; }
            set { SetPropertyValue<DataStore>("DataStore", ref _DataStore, value); }
        }
    }

}
