//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Repository
{

    public partial class FileBinderVersion : TIG.TotalLink.Shared.DataModel.Core.DataObjectBase
    {
        FileBinder _FileBinder;
        [Association(@"FileBinderVersionReferencesFileBinder")]
        public FileBinder FileBinder
        {
            get { return _FileBinder; }
            set { SetPropertyValue<FileBinder>("FileBinder", ref _FileBinder, value); }
        }
        string _Version;
        public string Version
        {
            get { return _Version; }
            set { SetPropertyValue<string>("Version", ref _Version, value); }
        }
        [Association(@"FileBinderVersionReferencesFile", typeof(File))]
        public XPCollection<File> Files { get { return GetCollection<File>("Files"); } }
        [Association(@"FileBinderVersionReferencesFileGroup", typeof(FileGroup))]
        public XPCollection<FileGroup> FileGroups { get { return GetCollection<FileGroup>("FileGroups"); } }
    }

}
