//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Repository
{

    public partial class FileExtensionGroup : TIG.TotalLink.Shared.DataModel.Core.DataObjectBase
    {
        string _Name;
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        string _Description;
        public string Description
        {
            get { return _Description; }
            set { SetPropertyValue<string>("Description", ref _Description, value); }
        }
        bool _IsActive;
        public bool IsActive
        {
            get { return _IsActive; }
            set { SetPropertyValue<bool>("IsActive", ref _IsActive, value); }
        }
        [Association(@"FileExtensionReferencesFileExtensionGroup", typeof(FileExtension))]
        public XPCollection<FileExtension> FileExtensions { get { return GetCollection<FileExtension>("FileExtensions"); } }
        [Association(@"DataStoreReferencesFileExtensionGroup", typeof(DataStore))]
        public XPCollection<DataStore> DataStores { get { return GetCollection<DataStore>("DataStores"); } }
    }

}
