//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Repository
{

    public partial class FileGroupVersion : TIG.TotalLink.Shared.DataModel.Core.DataObjectBase
    {
        FileGroup _FileGroup;
        [Association(@"FileGroupVersionReferencesFileGroup")]
        public FileGroup FileGroup
        {
            get { return _FileGroup; }
            set { SetPropertyValue<FileGroup>("FileGroup", ref _FileGroup, value); }
        }
        int _Version;
        public int Version
        {
            get { return _Version; }
            set { SetPropertyValue<int>("Version", ref _Version, value); }
        }
        [Association(@"FileGroupVersionReferencesFile", typeof(File))]
        public XPCollection<File> Files { get { return GetCollection<File>("Files"); } }
    }

}
