//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Repository
{

    public partial class RecordMetadata : TIG.TotalLink.Shared.DataModel.Core.DataObjectBase
    {
        string _UserName;
        public string UserName
        {
            get { return _UserName; }
            set { SetPropertyValue<string>("UserName", ref _UserName, value); }
        }
        DateTime _CreatedOn;
        public DateTime CreatedOn
        {
            get { return _CreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref _CreatedOn, value); }
        }
        Guid _CreatedBy;
        public Guid CreatedBy
        {
            get { return _CreatedBy; }
            set { SetPropertyValue<Guid>("CreatedBy", ref _CreatedBy, value); }
        }
        [Association(@"FileReferencesRecordMetadata", typeof(File))]
        public XPCollection<File> Files { get { return GetCollection<File>("Files"); } }
    }

}
