//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Repository
{

    public partial class RepositoryInfo : TIG.TotalLink.Shared.DataModel.Core.DataObjectBase
    {
        TIG.TotalLink.Shared.DataModel.Core.Enum.Repository.DatabaseProvider _DatabaseProvider;
        public TIG.TotalLink.Shared.DataModel.Core.Enum.Repository.DatabaseProvider DatabaseProvider
        {
            get { return _DatabaseProvider; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Core.Enum.Repository.DatabaseProvider>("DatabaseProvider", ref _DatabaseProvider, value); }
        }
        string _Server;
        public string Server
        {
            get { return _Server; }
            set { SetPropertyValue<string>("Server", ref _Server, value); }
        }
        string _DatabaseName;
        [Indexed(Name = @"IX_DatabaseName", Unique = true)]
        public string DatabaseName
        {
            get { return _DatabaseName; }
            set { SetPropertyValue<string>("DatabaseName", ref _DatabaseName, value); }
        }
        bool _IntegratedSecurity;
        public bool IntegratedSecurity
        {
            get { return _IntegratedSecurity; }
            set { SetPropertyValue<bool>("IntegratedSecurity", ref _IntegratedSecurity, value); }
        }
        string _UserName;
        public string UserName
        {
            get { return _UserName; }
            set { SetPropertyValue<string>("UserName", ref _UserName, value); }
        }
        string _Password;
        public string Password
        {
            get { return _Password; }
            set { SetPropertyValue<string>("Password", ref _Password, value); }
        }
        double _DataFileSizeLimitGB;
        public double DataFileSizeLimitGB
        {
            get { return _DataFileSizeLimitGB; }
            set { SetPropertyValue<double>("DataFileSizeLimitGB", ref _DataFileSizeLimitGB, value); }
        }
        FileExtension _Extension;
        [Association(@"RepositoryInfoReferencesFileExtension")]
        public FileExtension Extension
        {
            get { return _Extension; }
            set { SetPropertyValue<FileExtension>("Extension", ref _Extension, value); }
        }
        TIG.TotalLink.Shared.DataModel.Core.Enum.Repository.RepositoryType _Type;
        public TIG.TotalLink.Shared.DataModel.Core.Enum.Repository.RepositoryType Type
        {
            get { return _Type; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Core.Enum.Repository.RepositoryType>("Type", ref _Type, value); }
        }
        [Association(@"FileVersionReferencesRepositoryAccessInfo", typeof(FileVersion))]
        public XPCollection<FileVersion> FileVersions { get { return GetCollection<FileVersion>("FileVersions"); } }
    }

}
