using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Windows;
using DevExpress.Mvvm.DataAnnotations;
using DevExpress.Xpf.LayoutControl;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Client.Editor.Helper;
using TIG.TotalLink.Client.Module.Admin.Attribute;
using TIG.TotalLink.Client.Module.Admin.Helper;
using TIG.TotalLink.Client.Module.Admin.ViewModel.Core;

namespace TIG.TotalLink.Client.Module.Admin.ViewModel.WidgetCustomizer
{
    [WidgetCustomizer("Filter", 400)]
    public class FilterWidgetCustomizerViewModel : WidgetCustomizerViewModelBase
    {
        #region Private Fields

        private readonly WidgetViewModelBase _widget;
        private object _currentItem;

        #endregion


        #region Constructors

        public FilterWidgetCustomizerViewModel()
        {
        }

        public FilterWidgetCustomizerViewModel(WidgetViewModelBase widget)
            : this()
        {
            // Display this viewmodel in the DataLayoutControl
            CurrentItem = this;

            // Initialize properties
            _widget = widget;
         }

        #endregion


        #region Public Properties

        /// <summary>
        /// The object being displayed in the DataLayoutControl.
        /// This will automatically be initialized to contain a reference to this viewmodel.
        /// </summary>
        [Display(AutoGenerateField = false)]
        public object CurrentItem
        {
            get { return _currentItem; }
            set { SetProperty(ref _currentItem, value, () => CurrentItem); }
        }

        /// <summary>
        /// Indicates if the loading panel is visible.  Always false.
        /// Since the LocalDetailView is usually used directly in a widget, it contains a WidgetLoadingPanelView which will attempt to bind to this property.
        /// Therefore we include this property definition to avoid binding errors.
        /// </summary>
        [Display(AutoGenerateField = false)]
        public bool IsLoadingPanelVisible
        {
            get { return false; }
        }

        /// <summary>
        /// Indicates if the widget has any entity filters.
        /// </summary>
        [Display(AutoGenerateField = false)]
        public bool HasFilters
        {
            get { return _widget.FilterData.HasFilters; }
        }

        /// <summary>
        /// Specifies the mode to use when processing filters.
        /// </summary>
        public WidgetFilterData.FilterModes FilterMode
        {
            get { return _widget.FilterData.FilterMode; }
            set
            {
                _widget.FilterData.FilterMode = value;
                RaisePropertyChanged(() => FilterMode);
            }
        }

        /// <summary>
        /// A list of types that this filter data will filter by when FilterMode = SelectedTypesOnly.
        /// </summary>
        public ObservableCollection<WidgetFilter> SelectedTypes
        {
            get { return _widget.FilterData.SelectedTypes; }
        }

        /// <summary>
        /// A list of types that this widget can filter by.
        /// </summary>
        [Display(AutoGenerateField = false)]
        public ObservableCollection<WidgetFilter> AvailableTypes
        {
            get { return _widget.FilterData.AvailableTypes; }
        }

        #endregion


        #region Overrides

        public new static WidgetCustomizerViewModelBase CreateCustomizer(FrameworkElement content, WidgetViewModelBase widget)
        {
            // If the widget contains entity filters...
            if (widget.FilterData != null && widget.FilterData.HasFilters)
            {
                // Add a FilterWidgetCustomizerViewModel
                return new FilterWidgetCustomizerViewModel(widget);
            }

            // Otherwise, return null
            return null;
        }

        #endregion


        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<FilterWidgetCustomizerViewModel> builder)
        {
            builder.DataFormLayout()
                .ContainsProperty(p => p.FilterMode)
                .ContainsProperty(p => p.SelectedTypes);

            builder.Property(p => p.FilterMode)
                .DisplayName("Auto Filter On")
                .Description("Specifies which types this widget will auto filter on.");
            builder.Property(p => p.SelectedTypes)
                .AutoGenerated()
                .Description("A list of all types that this widget can auto filter on.");
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<FilterWidgetCustomizerViewModel> builder)
        {
            builder.Condition(i => i != null && i.FilterMode == WidgetFilterData.FilterModes.SelectedTypesOnly)
                .ContainsProperty(p => p.FilterMode)
                .AffectsPropertyEnabled(p => p.SelectedTypes);

            builder.Property(p => p.FilterMode)
                .ReplaceEditor(new OptionEditorDefinition(typeof(WidgetFilterData.FilterModes)))
                .LabelPosition(LayoutItemLabelPosition.Top);
            builder.Property(p => p.SelectedTypes)
                .ReplaceEditor(new CheckedListBoxEditorDefinition()
                {
                    ItemsSourcePropertyName = "AvailableTypes"
                })
                .HideLabel();
        }

        #endregion
    }
}
