//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Admin
{

    public partial class Appointment : StampedDataObjectBase
    {
        DateTime _StartDate;
        public DateTime StartDate
        {
            get { return _StartDate; }
            set { SetPropertyValue<DateTime>("StartDate", ref _StartDate, value); }
        }
        DateTime _EndDate;
        public DateTime EndDate
        {
            get { return _EndDate; }
            set { SetPropertyValue<DateTime>("EndDate", ref _EndDate, value); }
        }
        bool _AllDay;
        public bool AllDay
        {
            get { return _AllDay; }
            set { SetPropertyValue<bool>("AllDay", ref _AllDay, value); }
        }
        string _Description;
        [Size(255)]
        public string Description
        {
            get { return _Description; }
            set { SetPropertyValue<string>("Description", ref _Description, value); }
        }
        int _Label;
        public int Label
        {
            get { return _Label; }
            set { SetPropertyValue<int>("Label", ref _Label, value); }
        }
        string _Location;
        [Size(255)]
        public string Location
        {
            get { return _Location; }
            set { SetPropertyValue<string>("Location", ref _Location, value); }
        }
        string _Subject;
        [Size(150)]
        public string Subject
        {
            get { return _Subject; }
            set { SetPropertyValue<string>("Subject", ref _Subject, value); }
        }
        string _RecurrenceInfo;
        [Size(SizeAttribute.Unlimited)]
        public string RecurrenceInfo
        {
            get { return _RecurrenceInfo; }
            set { SetPropertyValue<string>("RecurrenceInfo", ref _RecurrenceInfo, value); }
        }
        string _ReminderInfo;
        [Size(SizeAttribute.Unlimited)]
        public string ReminderInfo
        {
            get { return _ReminderInfo; }
            set { SetPropertyValue<string>("ReminderInfo", ref _ReminderInfo, value); }
        }
        int _ResourceId;
        public int ResourceId
        {
            get { return _ResourceId; }
            set { SetPropertyValue<int>("ResourceId", ref _ResourceId, value); }
        }
        int _Status;
        public int Status
        {
            get { return _Status; }
            set { SetPropertyValue<int>("Status", ref _Status, value); }
        }
        int _EventType;
        public int EventType
        {
            get { return _EventType; }
            set { SetPropertyValue<int>("EventType", ref _EventType, value); }
        }
        string _OutlookEntryId;
        [Size(256)]
        public string OutlookEntryId
        {
            get { return _OutlookEntryId; }
            set { SetPropertyValue<string>("OutlookEntryId", ref _OutlookEntryId, value); }
        }
    }

}
