//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Admin
{

    public partial class Country : TIG.TotalLink.Shared.DataModel.Core.DataObjectBase
    {
        string _Code;
        [Indexed(Name = @"IX_Code")]
        [Size(10)]
        public string Code
        {
            get { return _Code; }
            set { SetPropertyValue<string>("Code", ref _Code, value); }
        }
        string _Name;
        [Size(255)]
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        bool _Authorized;
        public bool Authorized
        {
            get { return _Authorized; }
            set { SetPropertyValue<bool>("Authorized", ref _Authorized, value); }
        }
        [DevExpress.Xpo.Aggregated]
        [Association(@"StateReferencesCountry", typeof(State))]
        public XPCollection<State> States { get { return GetCollection<State>("States"); } }
    }

}
