//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Admin
{

    public partial class DocumentAction : StampedDataObjectBase
    {
        string _Name;
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        Document _Document;
        [ExplicitLoading(1)]
        [Association(@"DocumentActionReferencesDocument")]
        public Document Document
        {
            get { return _Document; }
            set { SetPropertyValue<Document>("Document", ref _Document, value); }
        }
    }

}
