//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Admin
{

    public partial class Document : StampedDataObjectBase
    {
        string _Name;
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        TIG.TotalLink.Shared.DataModel.Core.Enum.Admin.DocumentView _View;
        public TIG.TotalLink.Shared.DataModel.Core.Enum.Admin.DocumentView View
        {
            get { return _View; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Core.Enum.Admin.DocumentView>("View", ref _View, value); }
        }
        string _DataModelName;
        [Size(1000)]
        public string DataModelName
        {
            get { return _DataModelName; }
            set { SetPropertyValue<string>("DataModelName", ref _DataModelName, value); }
        }
        [DevExpress.Xpo.Aggregated, TIG.TotalLink.Shared.DataModel.Core.Attribute.DoNotCopy]
        [Association(@"PanelReferencesDocument", typeof(Panel))]
        public XPCollection<Panel> Panels { get { return GetCollection<Panel>("Panels"); } }
        [DevExpress.Xpo.Aggregated]
        [Association(@"DocumentDataReferencesDocument", typeof(DocumentData))]
        public XPCollection<DocumentData> DocumentDatas { get { return GetCollection<DocumentData>("DocumentDatas"); } }
        [Association(@"DocumentActionReferencesDocument", typeof(DocumentAction))]
        public XPCollection<DocumentAction> DocumentActions { get { return GetCollection<DocumentAction>("DocumentActions"); } }
        [DevExpress.Xpo.Aggregated, TIG.TotalLink.Shared.DataModel.Core.Attribute.DoNotCopy]
        [Association(@"PanelGroupReferencesDocument", typeof(PanelGroup))]
        public XPCollection<PanelGroup> PanelGroups { get { return GetCollection<PanelGroup>("PanelGroups"); } }
    }

}
