//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Admin
{

    [TIG.TotalLink.Shared.DataModel.Core.Attribute.NotAutoGenerated, TIG.TotalLink.Shared.DataModel.Core.Attribute.ModifiesParent("Document")]
    public partial class DocumentData : KeyedDataBase
    {
        Document _Document;
        [Association(@"DocumentDataReferencesDocument")]
        public Document Document
        {
            get { return _Document; }
            set { SetPropertyValue<Document>("Document", ref _Document, value); }
        }
    }

}
