//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Admin
{

    public partial class DynamicLink : TIG.TotalLink.Shared.DataModel.Core.DataObjectBase
    {
        int _EntityType;
        public int EntityType
        {
            get { return _EntityType; }
            set { SetPropertyValue<int>("EntityType", ref _EntityType, value); }
        }
        Guid _EntityOid;
        public Guid EntityOid
        {
            get { return _EntityOid; }
            set { SetPropertyValue<Guid>("EntityOid", ref _EntityOid, value); }
        }
    }

}
