//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Admin
{

    [NonPersistent]
    public partial class KeyedDataBase : TIG.TotalLink.Shared.DataModel.Core.DataObjectBase
    {
        string _GroupKey;
        public string GroupKey
        {
            get { return _GroupKey; }
            set { SetPropertyValue<string>("GroupKey", ref _GroupKey, value); }
        }
        string _ItemKey;
        [Size(1000)]
        public string ItemKey
        {
            get { return _ItemKey; }
            set { SetPropertyValue<string>("ItemKey", ref _ItemKey, value); }
        }
        byte[] _Data;
        public byte[] Data
        {
            get { return _Data; }
            set { SetPropertyValue<byte[]>("Data", ref _Data, value); }
        }
    }

}
