//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Admin
{

    public partial class Panel : StampedDataObjectBase
    {
        string _Name;
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        string _ViewName;
        public string ViewName
        {
            get { return _ViewName; }
            set { SetPropertyValue<string>("ViewName", ref _ViewName, value); }
        }
        Document _Document;
        [ExplicitLoading(1)]
        [Association(@"PanelReferencesDocument")]
        public Document Document
        {
            get { return _Document; }
            set { SetPropertyValue<Document>("Document", ref _Document, value); }
        }
        PanelGroup _PanelGroup;
        [ExplicitLoading(1)]
        [Association(@"PanelReferencesPanelGroup")]
        public PanelGroup PanelGroup
        {
            get { return _PanelGroup; }
            set { SetPropertyValue<PanelGroup>("PanelGroup", ref _PanelGroup, value); }
        }
        [DevExpress.Xpo.Aggregated]
        [Association(@"PanelDataReferencesPanel", typeof(PanelData))]
        public XPCollection<PanelData> PanelDatas { get { return GetCollection<PanelData>("PanelDatas"); } }
    }

}
