//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Admin
{

    public partial class RibbonPage : StampedDataObjectBase
    {
        string _Name;
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        RibbonCategory _RibbonCategory;
        [ExplicitLoading(1)]
        [Association(@"RibbonPageReferencesRibbonCategory")]
        public RibbonCategory RibbonCategory
        {
            get { return _RibbonCategory; }
            set { SetPropertyValue<RibbonCategory>("RibbonCategory", ref _RibbonCategory, value); }
        }
        [DevExpress.Xpo.Aggregated]
        [Association(@"RibbonGroupReferencesRibbonPage", typeof(RibbonGroup))]
        public XPCollection<RibbonGroup> RibbonGroups { get { return GetCollection<RibbonGroup>("RibbonGroups"); } }
    }

}
