//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Admin
{

    public partial class RibbonItem : StampedDataObjectBase
    {
        string _Name;
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        TIG.TotalLink.Shared.DataModel.Core.Enum.Admin.RibbonItemType _ItemType;
        public TIG.TotalLink.Shared.DataModel.Core.Enum.Admin.RibbonItemType ItemType
        {
            get { return _ItemType; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Core.Enum.Admin.RibbonItemType>("ItemType", ref _ItemType, value); }
        }
        TIG.TotalLink.Shared.DataModel.Core.Enum.Admin.CommandType _CommandType;
        public TIG.TotalLink.Shared.DataModel.Core.Enum.Admin.CommandType CommandType
        {
            get { return _CommandType; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Core.Enum.Admin.CommandType>("CommandType", ref _CommandType, value); }
        }
        string _CommandParameter;
        public string CommandParameter
        {
            get { return _CommandParameter; }
            set { SetPropertyValue<string>("CommandParameter", ref _CommandParameter, value); }
        }
        RibbonGroup _RibbonGroup;
        [ExplicitLoading(1)]
        [Association(@"RibbonItemReferencesRibbonGroup")]
        public RibbonGroup RibbonGroup
        {
            get { return _RibbonGroup; }
            set { SetPropertyValue<RibbonGroup>("RibbonGroup", ref _RibbonGroup, value); }
        }
        string _Description;
        [Size(SizeAttribute.Unlimited)]
        public string Description
        {
            get { return _Description; }
            set { SetPropertyValue<string>("Description", ref _Description, value); }
        }
    }

}
