//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Admin
{

    public partial class RibbonCategory : StampedDataObjectBase
    {
        string _Name;
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        bool _IsDefault;
        public bool IsDefault
        {
            get { return _IsDefault; }
            set { SetPropertyValue<bool>("IsDefault", ref _IsDefault, value); }
        }
        [DevExpress.Xpo.Aggregated]
        [Association(@"RibbonPageReferencesRibbonCategory", typeof(RibbonPage))]
        public XPCollection<RibbonPage> RibbonPages { get { return GetCollection<RibbonPage>("RibbonPages"); } }
    }

}
