//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Admin
{

    public partial class RibbonGroup : StampedDataObjectBase
    {
        string _Name;
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        bool _ShowCaptionButton;
        public bool ShowCaptionButton
        {
            get { return _ShowCaptionButton; }
            set { SetPropertyValue<bool>("ShowCaptionButton", ref _ShowCaptionButton, value); }
        }
        RibbonPage _RibbonPage;
        [ExplicitLoading(1)]
        [Association(@"RibbonGroupReferencesRibbonPage")]
        public RibbonPage RibbonPage
        {
            get { return _RibbonPage; }
            set { SetPropertyValue<RibbonPage>("RibbonPage", ref _RibbonPage, value); }
        }
        [DevExpress.Xpo.Aggregated]
        [Association(@"RibbonItemReferencesRibbonGroup", typeof(RibbonItem))]
        public XPCollection<RibbonItem> RibbonItems { get { return GetCollection<RibbonItem>("RibbonItems"); } }
    }

}
