//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Admin
{

    public partial class Sequence : TIG.TotalLink.Shared.DataModel.Core.DataObjectBase
    {
        string _Name;
        [Size(1000)]
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        int _Code;
        public int Code
        {
            get { return _Code; }
            set { SetPropertyValue<int>("Code", ref _Code, value); }
        }
        long _NextNumber;
        public long NextNumber
        {
            get { return _NextNumber; }
            set { SetPropertyValue<long>("NextNumber", ref _NextNumber, value); }
        }
    }

}
