//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Admin
{

    [NonPersistent]
    public partial class StampedDataObjectBase : TIG.TotalLink.Shared.DataModel.Core.DataObjectBase
    {
        User _CreatedBy;
        [ExplicitLoading(1)]
        public User CreatedBy
        {
            get { return _CreatedBy; }
            set { SetPropertyValue<User>("CreatedBy", ref _CreatedBy, value); }
        }
        DateTime _CreatedDate;
        public DateTime CreatedDate
        {
            get { return _CreatedDate; }
            set { SetPropertyValue<DateTime>("CreatedDate", ref _CreatedDate, value); }
        }
        User _ModifiedBy;
        [ExplicitLoading(1)]
        public User ModifiedBy
        {
            get { return _ModifiedBy; }
            set { SetPropertyValue<User>("ModifiedBy", ref _ModifiedBy, value); }
        }
        DateTime _ModifiedDate;
        public DateTime ModifiedDate
        {
            get { return _ModifiedDate; }
            set { SetPropertyValue<DateTime>("ModifiedDate", ref _ModifiedDate, value); }
        }
    }

}
