//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Admin
{

    public partial class State : TIG.TotalLink.Shared.DataModel.Core.DataObjectBase
    {
        string _Code;
        [Indexed(@"Country", Name = @"IX_CodeCountry")]
        [Size(10)]
        public string Code
        {
            get { return _Code; }
            set { SetPropertyValue<string>("Code", ref _Code, value); }
        }
        string _Name;
        [Size(255)]
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        Country _Country;
        [ExplicitLoading(1)]
        [Association(@"StateReferencesCountry")]
        public Country Country
        {
            get { return _Country; }
            set { SetPropertyValue<Country>("Country", ref _Country, value); }
        }
        [DevExpress.Xpo.Aggregated]
        [Association(@"SuburbReferencesState", typeof(Postcode))]
        public XPCollection<Postcode> Postcodes { get { return GetCollection<Postcode>("Postcodes"); } }
    }

}
