//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Admin
{

    public partial class User : StampedDataObjectBase
    {
        string _UserName;
        public string UserName
        {
            get { return _UserName; }
            set { SetPropertyValue<string>("UserName", ref _UserName, value); }
        }
        string _DisplayName;
        [Size(200)]
        public string DisplayName
        {
            get { return _DisplayName; }
            set { SetPropertyValue<string>("DisplayName", ref _DisplayName, value); }
        }
        string _Password;
        public string Password
        {
            get { return _Password; }
            set { SetPropertyValue<string>("Password", ref _Password, value); }
        }
        string _Salt;
        public string Salt
        {
            get { return _Salt; }
            set { SetPropertyValue<string>("Salt", ref _Salt, value); }
        }
        Guid? _ActiveDirectoryId;
        public Guid? ActiveDirectoryId
        {
            get { return _ActiveDirectoryId; }
            set { SetPropertyValue<Guid?>("ActiveDirectoryId", ref _ActiveDirectoryId, value); }
        }
        TIG.TotalLink.Shared.DataModel.Core.Enum.Admin.UserType _UserType;
        public TIG.TotalLink.Shared.DataModel.Core.Enum.Admin.UserType UserType
        {
            get { return _UserType; }
            set { SetPropertyValue<TIG.TotalLink.Shared.DataModel.Core.Enum.Admin.UserType>("UserType", ref _UserType, value); }
        }
    }

}
