using System;

namespace TIG.TotalLink.Shared.DataModel.Core.Attribute
{
    /// <summary>
    /// Indicates that no editors will ever be auto generated for the target class.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class)]
    public class NotAutoGeneratedAttribute : System.Attribute
    {
    }
}
