using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.Facade.Crm;

namespace TIG.TotalLink.Shared.DataModel.Crm
{
    [FacadeType(typeof(ICrmFacade))]
    [DisplayField("Name")]
    public partial class Industry
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<Industry> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.Name)
                .ContainsProperty(p => p.IndustryClasses);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.Name)
                .Group("Industry Classes")
                    .ContainsProperty(p => p.IndustryClasses);


            builder.Property(p => p.IndustryClasses).AutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<Industry> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Name);

            builder.GridBaseColumnEditors().Property(p => p.IndustryClasses).ReplaceEditor(new PopupGridEditorDefinition
            {
                EntityType = typeof(IndustryClass),
                FilterMethod = context => CriteriaOperator.Parse("Industry.Oid = ?", ((Industry)context).Oid)
            });

            builder.DataFormEditors().Property(p => p.IndustryClasses).ReplaceEditor(new GridEditorDefinition
            {
                EntityType = typeof(IndustryClass),
                FilterMethod = context => CriteriaOperator.Parse("Industry.Oid = ?", ((Industry)context).Oid)
            });
        }

        #endregion
    }
}
