//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.Global
{

    public partial class XpoProvider : TIG.TotalLink.Shared.DataModel.Core.DataObjectBase
    {
        string _Name;
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        string _FileFilter;
        public string FileFilter
        {
            get { return _FileFilter; }
            set { SetPropertyValue<string>("FileFilter", ref _FileFilter, value); }
        }
        bool _HasIntegratedSecurity;
        public bool HasIntegratedSecurity
        {
            get { return _HasIntegratedSecurity; }
            set { SetPropertyValue<bool>("HasIntegratedSecurity", ref _HasIntegratedSecurity, value); }
        }
        bool _HasMultipleDatabases;
        public bool HasMultipleDatabases
        {
            get { return _HasMultipleDatabases; }
            set { SetPropertyValue<bool>("HasMultipleDatabases", ref _HasMultipleDatabases, value); }
        }
        bool _HasPassword;
        public bool HasPassword
        {
            get { return _HasPassword; }
            set { SetPropertyValue<bool>("HasPassword", ref _HasPassword, value); }
        }
        bool _HasUserName;
        public bool HasUserName
        {
            get { return _HasUserName; }
            set { SetPropertyValue<bool>("HasUserName", ref _HasUserName, value); }
        }
        bool _IsFileBased;
        public bool IsFileBased
        {
            get { return _IsFileBased; }
            set { SetPropertyValue<bool>("IsFileBased", ref _IsFileBased, value); }
        }
        bool _IsServerBased;
        public bool IsServerBased
        {
            get { return _IsServerBased; }
            set { SetPropertyValue<bool>("IsServerBased", ref _IsServerBased, value); }
        }
        bool _MeanSchemaGeneration;
        public bool MeanSchemaGeneration
        {
            get { return _MeanSchemaGeneration; }
            set { SetPropertyValue<bool>("MeanSchemaGeneration", ref _MeanSchemaGeneration, value); }
        }
        bool _SupportStoredProcedures;
        public bool SupportStoredProcedures
        {
            get { return _SupportStoredProcedures; }
            set { SetPropertyValue<bool>("SupportStoredProcedures", ref _SupportStoredProcedures, value); }
        }
    }

}
