using System.Collections.ObjectModel;
using System.Linq;
using System.Windows.Controls;
using DevExpress.Mvvm.DataAnnotations;
using DevExpress.Xpf.LayoutControl;
using TIG.TotalLink.Client.Core.Extension;
using TIG.TotalLink.Client.Core.ViewModel;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.DataModel.Inventory;
using TIG.TotalLink.Shared.DataModel.Sale;

namespace TIG.TotalLink.Client.Module.Sale.ViewModel.Options
{
    [DialogSize(600, 400)]
    public class ReleaseSalesOrderOptionsViewModel : LocalDataObjectBase
    {
        #region Private Fields

        private ObservableCollection<SalesOrder> _salesOrders;
        private ObservableCollection<BinLocation> _binLocations;
        private ObservableCollection<PhysicalStockType> _physicalStockTypes;
        private bool? _allowPartialDelivery;
        private string _summary;

        #endregion


        #region Public Properties

        /// <summary>
        /// The SalesOrders that will be released.
        /// </summary>
        public ObservableCollection<SalesOrder> SalesOrders
        {
            get { return _salesOrders; }
            set
            {
                SetProperty(ref _salesOrders, value, () => SalesOrders,
                    UpdateSummary
                );
            }
        }

        /// <summary>
        /// The BinLocations that the SalesOrders will be released from.
        /// </summary>
        public ObservableCollection<BinLocation> BinLocations
        {
            get { return _binLocations; }
            set { SetProperty(ref _binLocations, value, () => BinLocations); }
        }

        /// <summary>
        /// The PhysicalStockTypes that the SalesOrders will be released from.
        /// </summary>
        public ObservableCollection<PhysicalStockType> PhysicalStockTypes
        {
            get { return _physicalStockTypes; }
            set { SetProperty(ref _physicalStockTypes, value, () => PhysicalStockTypes); }
        }

        /// <summary>
        /// Indicates if the SalesOrders can be part released.
        /// If set, this overrides the value on each SalesOrder.
        /// </summary>
        public bool? AllowPartialDelivery
        {
            get { return _allowPartialDelivery; }
            set { SetProperty(ref _allowPartialDelivery, value, () => AllowPartialDelivery); }
        }

        /// <summary>
        /// A summary of the SalesOrders that will be released.
        /// </summary>
        public string Summary
        {
            get { return _summary; }
            set { SetProperty(ref _summary, value, () => Summary); }
        }

        #endregion


        #region Private Methods

        /// <summary>
        /// Updates the summary.
        /// </summary>
        private void UpdateSummary()
        {
            var quantityRemaining = SalesOrders.Sum(s => s.TotalQuantity - s.TotalQuantityReleased - s.TotalQuantityCancelled);
            Summary = string.Format("{0} {1}\r\n{2} {3} to be released", SalesOrders.Count, SalesOrders.Count.Pluralize("sales order"), quantityRemaining, quantityRemaining.Pluralize("item"));
        }

        #endregion


        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<ReleaseSalesOrderOptionsViewModel> builder)
        {
            builder.DataFormLayout()
                .GroupBox("Summary")
                    .ContainsProperty(p => p.Summary)
                .EndGroup()
                .GroupBox("Parameters")
                    .ContainsProperty(p => p.AllowPartialDelivery)
                    .Group("Source", Orientation.Horizontal)
                        .ContainsProperty(p => p.BinLocations)
                        .ContainsProperty(p => p.PhysicalStockTypes);

            builder.Property(p => p.BinLocations)
                .DisplayName("Bins")
                .AutoGenerated();
            builder.Property(p => p.PhysicalStockTypes)
                .DisplayName("Stock Types")
                .AutoGenerated();
            builder.Property(p => p.SalesOrders).NotAutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<ReleaseSalesOrderOptionsViewModel> builder)
        {
            builder.Property(p => p.Summary)
                .ReplaceEditor(new LabelEditorDefinition())
                .HideLabel();
            builder.Property(p => p.AllowPartialDelivery).AllowNull();

            builder.Property(p => p.BinLocations)
                 .ReplaceEditor(new GridEditorDefinition
                 {
                     EntityType = typeof(BinLocation),
                     ItemsSourceMethod = context => ((ReleaseSalesOrderOptionsViewModel)context).BinLocations
                 })
                 .LabelPosition(LayoutItemLabelPosition.Top);

            builder.Property(p => p.PhysicalStockTypes)
                 .ReplaceEditor(new GridEditorDefinition
                 {
                     EntityType = typeof(PhysicalStockType),
                     ItemsSourceMethod = context => ((ReleaseSalesOrderOptionsViewModel)context).PhysicalStockTypes
                 })
                 .LabelPosition(LayoutItemLabelPosition.Top);
        }

        #endregion
    }
}
