using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.Facade.Inventory;

namespace TIG.TotalLink.Shared.DataModel.Inventory
{
    [FacadeType(typeof(IInventoryFacade))]
    [DisplayField("Name")]
    [EntityFilter(typeof(WarehouseLocation), "WarehouseLocation.Oid IN (?)", "WarehouseLocation IN (?)")]
    public partial class BinLocation
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<BinLocation> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.Name)
                .ContainsProperty(p => p.IsleCode)
                .ContainsProperty(p => p.BinCode)
                .ContainsProperty(p => p.WarehouseLocation)
                .ContainsProperty(p => p.PhysicalStocks);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.Name)
                    .ContainsProperty(p => p.IsleCode)
                    .ContainsProperty(p => p.BinCode)
                    .ContainsProperty(p => p.WarehouseLocation)
                .EndGroup()
                .Group("Physical Stock")
                    .ContainsProperty(p => p.PhysicalStocks);

            builder.Property(p => p.PhysicalStocks)
                .AutoGenerated()
                .DisplayName("Physical Stock");
            builder.Property(p => p.TargetStockAdjustments).NotAutoGenerated();
            builder.Property(p => p.SourceStockAdjustments).NotAutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<BinLocation> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Name);

            builder.GridBaseColumnEditors().Property(p => p.PhysicalStocks)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(PhysicalStock),
                    FilterMethod = context => CriteriaOperator.Parse("BinLocation.Oid=?", ((BinLocation)context).Oid)
                });

            builder.DataFormEditors().Property(p => p.PhysicalStocks)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(PhysicalStock),
                    FilterMethod = context => CriteriaOperator.Parse("BinLocation.Oid=?", ((BinLocation)context).Oid),
                });
        }

        #endregion
    }
}