using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.Facade.Inventory;

namespace TIG.TotalLink.Shared.DataModel.Inventory
{
    [FacadeType(typeof(IInventoryFacade))]
    [DisplayField("Name")]
    public partial class ColourCategory
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<ColourCategory> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.Name)
                .ContainsProperty(p => p.Colours);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.Name)
                .EndGroup()
                .Group("Colours")
                    .ContainsProperty(p => p.Colours);

            builder.Property(p => p.Colours).AutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<ColourCategory> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Name);

            builder.GridBaseColumnEditors().Property(p => p.Colours)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(Colour),
                    FilterMethod = context => CriteriaOperator.Parse("Category.Oid = ?", ((ColourCategory)context).Oid)
                });

            builder.DataFormEditors().Property(p => p.Colours)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(Colour),
                    FilterMethod = context => CriteriaOperator.Parse("Category.Oid = ?", ((ColourCategory)context).Oid)
                });
        }

        #endregion
    }
}