using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.Facade.Inventory;

namespace TIG.TotalLink.Shared.DataModel.Inventory
{
    [FacadeType(typeof(IInventoryFacade))]
    [DisplayField("Name")]
    public partial class Colour
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<Colour> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.Name)
                .ContainsProperty(p => p.Category);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.Name)
                    .ContainsProperty(p => p.Category);

            builder.Property(p => p.Skus).NotAutoGenerated();
            builder.Property(p => p.Web_Skus).NotAutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<Colour> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Category)
                .ContainsProperty(p => p.Name);
        }

        #endregion
    }
}