using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.Facade.Inventory;

namespace TIG.TotalLink.Shared.DataModel.Inventory
{
    [FacadeType(typeof(IInventoryFacade))]
    [DisplayField("Name")]
    public partial class SizeRange
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<SizeRange> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.Name)
                .ContainsProperty(p => p.Sizes);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.Name)
                .EndGroup()
                .Group("Sizes")
                    .ContainsProperty(p => p.Sizes);

            builder.Property(p => p.Sizes).AutoGenerated();
            builder.Property(p => p.Styles).NotAutoGenerated();
            builder.Property(p => p.Web_Styles).NotAutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<SizeRange> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Name);

            builder.GridBaseColumnEditors().Property(p => p.Sizes)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(Size),
                    FilterMethod = context => CriteriaOperator.Parse("SizeRange.Oid = ?", ((SizeRange)context).Oid)
                });

            builder.DataFormEditors().Property(p => p.Sizes)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(Size),
                    FilterMethod = context => CriteriaOperator.Parse("SizeRange.Oid = ?", ((SizeRange)context).Oid)
                });
        }

        #endregion
    }
}