using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.Facade.Inventory;

namespace TIG.TotalLink.Shared.DataModel.Inventory
{
    [FacadeType(typeof(IInventoryFacade))]
    [DisplayField("Name")]
    public partial class Style
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<Style> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.Reference)
                .ContainsProperty(p => p.Name)
                .ContainsProperty(p => p.Code)
                .ContainsProperty(p => p.Gender)
                .ContainsProperty(p => p.SizeRange)
                .ContainsProperty(p => p.Fit)
                .ContainsProperty(p => p.Fabric)
                .ContainsProperty(p => p.Category)
                .ContainsProperty(p => p.ProductCategory)
                .ContainsProperty(p => p.ProductType)
                .ContainsProperty(p => p.StyleClass)
                .ContainsProperty(p => p.Department)
                .ContainsProperty(p => p.Skus);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.Reference)
                    .ContainsProperty(p => p.Name)
                    .ContainsProperty(p => p.Code)
                    .ContainsProperty(p => p.Gender)
                    .ContainsProperty(p => p.SizeRange)
                    .ContainsProperty(p => p.Fit)
                    .ContainsProperty(p => p.Fabric)
                    .ContainsProperty(p => p.Category)
                    .ContainsProperty(p => p.ProductCategory)
                    .ContainsProperty(p => p.ProductType)
                    .ContainsProperty(p => p.StyleClass)
                    .ContainsProperty(p => p.Department)
                .EndGroup()
                .Group("Additional")
                    .ContainsProperty(p => p.Content)
                    .ContainsProperty(p => p.LongDescription)
                .EndGroup()
                .Group("Skus")
                    .ContainsProperty(p => p.Skus)
                .EndGroup()
                .Group("Web")
                    .ContainsProperty(p => p.Web_Number)
                    .ContainsProperty(p => p.Web_Name)
                    .ContainsProperty(p => p.Web_Description)
                    .ContainsProperty(p => p.Web_LongDescription)
                    .ContainsProperty(p => p.Web_Details)
                    .ContainsProperty(p => p.Web_Category)
                    .ContainsProperty(p => p.Web_ProductCategory)
                    .ContainsProperty(p => p.Web_ProductType)
                    .ContainsProperty(p => p.Web_StyleClass)
                    .ContainsProperty(p => p.Web_Industry)
                    .ContainsProperty(p => p.Web_Fabric)
                    .ContainsProperty(p => p.Web_SizingTable)
                    .ContainsProperty(p => p.Web_Fit)
                    .ContainsProperty(p => p.Web_SizeRange)
                    .ContainsProperty(p => p.Web_ImageCode1)
                    .ContainsProperty(p => p.Web_ImageCode2)
                    .ContainsProperty(p => p.Web_ImageCode3);

            builder.Property(p => p.Reference).ReadOnly();

            builder.Property(p => p.Skus).AutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<Style> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Name);

            builder.GridBaseColumnEditors()
                .Property(p => p.Content).Hidden().EndProperty()
                .Property(p => p.LongDescription).Hidden().EndProperty()
                .Property(p => p.Web_Number).Hidden().EndProperty()
                .Property(p => p.Web_Name).Hidden().EndProperty()
                .Property(p => p.Web_Description).Hidden().EndProperty()
                .Property(p => p.Web_LongDescription).Hidden().EndProperty()
                .Property(p => p.Web_Details).Hidden().EndProperty()
                .Property(p => p.Web_Category).Hidden().EndProperty()
                .Property(p => p.Web_ProductCategory).Hidden().EndProperty()
                .Property(p => p.Web_ProductType).Hidden().EndProperty()
                .Property(p => p.Web_StyleClass).Hidden().EndProperty()
                .Property(p => p.Web_Industry).Hidden().EndProperty()
                .Property(p => p.Web_Fabric).Hidden().EndProperty()
                .Property(p => p.Web_SizingTable).Hidden().EndProperty()
                .Property(p => p.Web_Fit).Hidden().EndProperty()
                .Property(p => p.Web_SizeRange).Hidden().EndProperty()
                .Property(p => p.Web_ImageCode1).Hidden().EndProperty()
                .Property(p => p.Web_ImageCode2).Hidden().EndProperty()
                .Property(p => p.Web_ImageCode3).Hidden().EndProperty();

            builder.DataFormEditors()
                .Property(p => p.Web_Number).DisplayName("Number").EndProperty()
                .Property(p => p.Web_Name).DisplayName("Name").EndProperty()
                .Property(p => p.Web_Description).DisplayName("Description").EndProperty()
                .Property(p => p.Web_LongDescription).DisplayName("Long Description").EndProperty()
                .Property(p => p.Web_Details).DisplayName("Details").EndProperty()
                .Property(p => p.Web_Category).DisplayName("Category").EndProperty()
                .Property(p => p.Web_ProductCategory).DisplayName("Product Category").EndProperty()
                .Property(p => p.Web_ProductType).DisplayName("Product Type").EndProperty()
                .Property(p => p.Web_StyleClass).DisplayName("Style Class").EndProperty()
                .Property(p => p.Web_Industry).DisplayName("Industry").EndProperty()
                .Property(p => p.Web_Fabric).DisplayName("Fabric").EndProperty()
                .Property(p => p.Web_SizingTable).DisplayName("Sizing Table").EndProperty()
                .Property(p => p.Web_Fit).DisplayName("Fit").EndProperty()
                .Property(p => p.Web_SizeRange).DisplayName("Size Range").EndProperty()
                .Property(p => p.Web_ImageCode1).DisplayName("Image Code 1").EndProperty()
                .Property(p => p.Web_ImageCode2).DisplayName("Image Code 2").EndProperty()
                .Property(p => p.Web_ImageCode3).DisplayName("Image Code 3").EndProperty();

            builder.Property(p => p.Reference).GetEditor<SpinEditorDefinition>().DisplayFormat = "D0";

            builder.Property(p => p.LongDescription)
                .ReplaceEditor(new MemoEditorDefinition());

            builder.Property(p => p.Web_Description)
                .ReplaceEditor(new MemoEditorDefinition());

            builder.Property(p => p.Web_LongDescription)
                .ReplaceEditor(new MemoEditorDefinition());

            builder.GridBaseColumnEditors().Property(p => p.Skus).ReplaceEditor(new PopupGridEditorDefinition
            {
                EntityType = typeof(Sku),
                FilterMethod = context => CriteriaOperator.Parse("Style.Oid = ?", ((Style)context).Oid)
            });

            builder.DataFormEditors().Property(p => p.Skus)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(Sku),
                    FilterMethod = context => CriteriaOperator.Parse("Style.Oid = ?", ((Style)context).Oid)
                });
        }

        #endregion
    }
}