using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.DataModel.Core.Extension;
using TIG.TotalLink.Shared.Facade.Inventory;

namespace TIG.TotalLink.Shared.DataModel.Inventory
{
    [FacadeType(typeof(IInventoryFacade))]
    [DisplayField("Name")]
    public partial class WarehouseLocation
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<WarehouseLocation> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.Name)
                .ContainsProperty(p => p.Code)
                .ContainsProperty(p => p.Address)
                .ContainsProperty(p => p.BinLocations);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.Name)
                    .ContainsProperty(p => p.Code)
                    .ContainsProperty(p => p.Address)
                .EndGroup()
                .Group("Bin Locations")
                    .ContainsProperty(p => p.BinLocations);

            builder.Property(p => p.BinLocations).AutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<WarehouseLocation> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Name);

            var gridsEditor = new GridEditorDefinition
            {
                EntityType = typeof(BinLocation),
                FilterMethod = context => CriteriaOperator.Parse("WarehouseLocation.Oid = ?", ((WarehouseLocation)context).Oid),
                ShowToolBar = true,
                BuildNewRowMethod = (context, session) => new BinLocation(session)
                {
                    WarehouseLocation = session.GetDataObject((WarehouseLocation)context)
                }
            };
            builder.DataFormEditors().Property(p => p.BinLocations)
                .ReplaceEditor(gridsEditor)
                .HideLabel();

            var gridsPopupEditor = new PopupGridEditorDefinition
            {
                EntityType = typeof(BinLocation),
                FilterMethod = context => CriteriaOperator.Parse("WarehouseLocation.Oid = ?", ((WarehouseLocation)context).Oid)
            };
            builder.GridBaseColumnEditors().Property(p => p.BinLocations)
                .ReplaceEditor(gridsPopupEditor);
        }

        #endregion
    }
}