using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.Facade.Repository;

namespace TIG.TotalLink.Shared.DataModel.Repository
{
    [FacadeType(typeof(IRepositoryFacade))]
    [DisplayField("Name")]
    partial class Category
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<Category> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.Name)
                .ContainsProperty(p => p.Parent)
                .ContainsProperty(p => p.Files)
                .ContainsProperty(p => p.ChildrenCategories);

            builder.Property(p => p.Files).AutoGenerated();
            builder.Property(p => p.ChildrenCategories).AutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<Category> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Name);

            builder.GridBaseColumnEditors().Property(p => p.Files).ReplaceEditor(new PopupGridEditorDefinition
            {
                EntityType = typeof(File),
                FilterMethod = context => CriteriaOperator.Parse("Category.Oid = ?", ((Category)context).Oid)
            });

            builder.DataFormEditors().Property(p => p.Files).ReplaceEditor(new PopupGridEditorDefinition
            {
                EntityType = typeof(File),
                FilterMethod = context => CriteriaOperator.Parse("Category.Oid = ?", ((Category)context).Oid)
            });

            builder.GridBaseColumnEditors().Property(p => p.ChildrenCategories).ReplaceEditor(new PopupGridEditorDefinition
            {
                EntityType = typeof(File),
                FilterMethod = context => CriteriaOperator.Parse("Parent.Oid = ?", ((Category)context).Oid)
            });

            builder.DataFormEditors().Property(p => p.ChildrenCategories).ReplaceEditor(new PopupGridEditorDefinition
            {
                EntityType = typeof(File),
                FilterMethod = context => CriteriaOperator.Parse("Parent.Oid = ?", ((Category)context).Oid)
            });
        }

        #endregion
    }
}
