using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.Facade.Repository;

namespace TIG.TotalLink.Shared.DataModel.Repository
{
    [FacadeType(typeof(IRepositoryFacade))]
    [DisplayField("Name")]
    public partial class FileBinder
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<FileBinder> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.Name)
                .ContainsProperty(p => p.Description)
                .ContainsProperty(p => p.LastVersion)
             .EndGroup()
             .Group("Versions")
                .ContainsProperty(p => p.FileBinderVersions);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.Name)
                    .ContainsProperty(p => p.Description)
                    .ContainsProperty(p => p.LastVersion);

            builder.Property(p => p.Name).Required();

            builder.Property(p => p.FileBinderVersions).AutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<FileBinder> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Name);

            builder.DataFormEditors().Property(p => p.FileBinderVersions).Hidden();

            builder.DataFormEditors()
                .Property(p => p.FileBinderVersions)
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(FileBinderVersion),
                    FilterMethod = context => CriteriaOperator.Parse("FileBinder.Oid = ?", ((FileBinder)context).Oid)
                }).HideLabel();

            builder.GridBaseColumnEditors()
                .Property(p => p.FileBinderVersions)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(FileBinderVersion),
                    FilterMethod = context => CriteriaOperator.Parse("FileBinder.Oid = ?", ((FileBinder)context).Oid)
                });
        }

        #endregion
    }
}