using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.Facade.Repository;

namespace TIG.TotalLink.Shared.DataModel.Repository
{
    [DisplayField("Name")]
    [FacadeType(typeof(IRepositoryFacade))]
    public partial class FileExtensionGroup
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<FileExtensionGroup> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.Name)
                .ContainsProperty(p => p.Description)
                .ContainsProperty(p => p.FileExtensions);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.Name)
                    .ContainsProperty(p => p.Description)
                    .ContainsProperty(p => p.FileExtensions);

            builder.Property(p => p.FileExtensions).AutoGenerated();
            builder.Property(p => p.DataStores).NotAutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<FileExtensionGroup> builder)
        {
            builder.GridBaseColumnEditors().Property(p => p.FileExtensions).ReplaceEditor(new PopupGridEditorDefinition
            {
                EntityType = typeof(FileExtension),
                FilterMethod = context => CriteriaOperator.Parse("[FileExtensionGroups][Oid = ?]", ((FileExtensionGroup)context).Oid)
            });

            builder.DataFormEditors().Property(p => p.FileExtensions).ReplaceEditor(new GridEditorDefinition
            {
                EntityType = typeof(FileExtension),
                FilterMethod = context => CriteriaOperator.Parse("[FileExtensionGroups][Oid = ?]", ((FileExtensionGroup)context).Oid)
            });
        }

        #endregion
    }
}