using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.Facade.Repository;

namespace TIG.TotalLink.Shared.DataModel.Repository
{
    [FacadeType(typeof(IRepositoryFacade))]
    [DisplayField("Name")]
    public partial class FileGroup
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<FileGroup> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.Name)
                .ContainsProperty(p => p.Description)
                .ContainsProperty(p => p.LastVersion)
                .ContainsProperty(p => p.FileBinderVersions)
             .EndGroup()
             .Group("Versions")
                .ContainsProperty(p => p.FileGroupVersions);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.Name)
                    .ContainsProperty(p => p.Description)
                    .ContainsProperty(p => p.LastVersion)
                .EndGroup()
                .Group("Versions")
                    .ContainsProperty(p => p.FileGroupVersions);

            builder.Property(p => p.Name).Required();
            builder.Property(p => p.LastVersion).ReadOnly();

            builder.Property(p => p.FileBinderVersions).NotAutoGenerated();
            builder.Property(p => p.FileGroupVersions).AutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<FileGroup> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Name);

            builder.DataFormEditors().Property(p => p.FileGroupVersions).Hidden();

            builder.DataFormEditors()
                .Property(p => p.FileGroupVersions)
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(FileGroupVersion),
                    FilterMethod = context => CriteriaOperator.Parse("FileGroup.Oid = ?", ((FileGroup)context).Oid)
                }).HideLabel();

            builder.GridBaseColumnEditors()
                .Property(p => p.FileGroupVersions)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(FileGroupVersion),
                    FilterMethod = context => CriteriaOperator.Parse("FileGroup.Oid = ?", ((FileGroup)context).Oid)
                });
        }

        #endregion
    }
}