using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.Facade.Repository;

namespace TIG.TotalLink.Shared.DataModel.Repository
{
    [DisplayField("Name")]
    [FacadeType(typeof(IRepositoryFacade))]
    public partial class FileExtension
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<FileExtension> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.Name);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.Name)
                .EndGroup()
                .Group("Files")
                    .ContainsProperty(p => p.Files);

            builder.Property(p => p.Files).AutoGenerated();
            builder.Property(p => p.FileExtensionGroups).AutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<FileExtension> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Name);

            builder.GridBaseColumnEditors().Property(p => p.Files).ReplaceEditor(new PopupGridEditorDefinition
            {
                EntityType = typeof(File),
                FilterMethod = context => CriteriaOperator.Parse("Extension.Oid = ?", ((FileExtension)context).Oid)
            });

            builder.DataFormEditors().Property(p => p.Files).ReplaceEditor(new GridEditorDefinition
            {
                EntityType = typeof(File),
                FilterMethod = context => CriteriaOperator.Parse("Extension.Oid = ?", ((FileExtension)context).Oid)
            }).HideLabel();

            builder.GridBaseColumnEditors().Property(p => p.FileExtensionGroups).ReplaceEditor(new PopupGridEditorDefinition
            {
                EntityType = typeof(FileExtensionGroup),
                FilterMethod = context => CriteriaOperator.Parse("[FileExtensions][Oid = ?]", ((FileExtension)context).Oid)
            });

            builder.DataFormEditors().Property(p => p.FileExtensionGroups).ReplaceEditor(new GridEditorDefinition
            {
                EntityType = typeof(FileExtensionGroup),
                FilterMethod = context => CriteriaOperator.Parse("[FileExtensions][Oid = ?]", ((FileExtension)context).Oid)
            }).HideLabel();
        }

        #endregion
    }
}