using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.Facade.Repository;

namespace TIG.TotalLink.Shared.DataModel.Repository
{
    [FacadeType(typeof(IRepositoryFacade))]
    [DisplayField("Version")]
    public partial class FileBinderVersion
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<FileBinderVersion> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.FileBinder)
                .ContainsProperty(p => p.Version)
                .ContainsProperty(p => p.Files)
                .ContainsProperty(p => p.FileGroups);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                .ContainsProperty(p => p.FileBinder)
                .ContainsProperty(p => p.Version)
                .EndGroup()
                .Group("Files")
                    .ContainsProperty(p => p.Files)
                .EndGroup()
                .Group("File Groups")
                    .ContainsProperty(p => p.FileGroups);

            builder.Property(p => p.Files).AutoGenerated();
            builder.Property(p => p.FileGroups).AutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<FileBinderVersion> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Version);

            // TODO: Need to handle many to many mapping.

            builder.DataFormEditors()
                .Property(p => p.Files)
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(File),
                    FilterMethod = context => CriteriaOperator.Parse("[FileBinderVersions][Oid = ?]", ((FileBinder)context).Oid)
                }).HideLabel();

            builder.GridBaseColumnEditors()
                .Property(p => p.Files)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(File),
                    FilterMethod = context => CriteriaOperator.Parse("[FileBinderVersions][Oid = ?]", ((FileBinder)context).Oid)
                });

            builder.DataFormEditors()
                .Property(p => p.FileGroups)
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(FileGroup),
                    FilterMethod = context => CriteriaOperator.Parse("[FileBinderVersions][Oid = ?]", ((FileBinder)context).Oid)
                }).HideLabel();

            builder.GridBaseColumnEditors()
                .Property(p => p.FileGroups)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(FileGroup),
                    FilterMethod = context => CriteriaOperator.Parse("[FileBinderVersions][Oid = ?]", ((FileBinder)context).Oid)
                });
        }

        #endregion
    }
}