using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.Facade.Repository;

namespace TIG.TotalLink.Shared.DataModel.Repository
{
    [FacadeType(typeof(IRepositoryFacade))]
    [DisplayField("Version")]
    public partial class FileGroupVersion
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<FileGroupVersion> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.FileGroup)
                .ContainsProperty(p => p.Version)
                .ContainsProperty(p => p.Files);

            builder.Property(p => p.Files).AutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<FileGroupVersion> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Version);

            // TODO: Need to handle many to many mapping.

            builder.DataFormEditors()
                .Property(p => p.Files)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(File),
                    FilterMethod = context => CriteriaOperator.Parse("[FileGroupVersions][Oid = ?]", ((FileGroupVersion)context).Oid)
                });

            builder.GridBaseColumnEditors()
                .Property(p => p.Files)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(File),
                    FilterMethod = context => CriteriaOperator.Parse("[FileGroupVersions][Oid = ?]", ((FileGroupVersion)context).Oid)
                });
        }

        #endregion
    }
}