//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TIG.TotalLink.Shared.DataModel.RepositoryStore.DataModel
{

    public partial class FileData : TIG.TotalLink.Shared.DataModel.Core.DataObjectBase
    {
﻿		byte[] _Body;
        public byte[] Body
        {
            get { return _Body; }
            set { SetPropertyValue<byte[]>("Body", ref _Body, value); }
        }
﻿		long _Size;
        public long Size
        {
            get { return _Size; }
            set { SetPropertyValue<long>("Size", ref _Size, value); }
        }
﻿		byte[] _HashHex;
        public byte[] HashHex
        {
            get { return _HashHex; }
            set { SetPropertyValue<byte[]>("HashHex", ref _HashHex, value); }
        }
﻿		string _Description;
        public string Description
        {
            get { return _Description; }
            set { SetPropertyValue<string>("Description", ref _Description, value); }
        }
﻿		DateTime _CreatedOn;
        public DateTime CreatedOn
        {
            get { return _CreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref _CreatedOn, value); }
        }
    }

}
