using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.Facade.Admin;

namespace TIG.TotalLink.Shared.DataModel.Admin
{
    [FacadeType(typeof(IAdminFacade))]
    [DisplayField("Name")]
    public partial class Country
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<Country> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.Name)
                .ContainsProperty(p => p.Code)
                .ContainsProperty(p => p.Authorized)
                .ContainsProperty(p => p.States);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.Name)
                    .ContainsProperty(p => p.Code)
                    .ContainsProperty(p => p.Authorized)
                .EndGroup()
                .Group("States")
                    .ContainsProperty(p => p.States);

            builder.Property(p => p.Name).Required();
            builder.Property(p => p.Code).Required();
            builder.Property(p => p.Authorized).DisplayName("Authorised");

            builder.Property(p => p.States).AutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<Country> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Name);

            builder.GridBaseColumnEditors().Property(p => p.States).ReplaceEditor(new PopupGridEditorDefinition
            {
                EntityType = typeof(State),
                FilterMethod = context => CriteriaOperator.Parse("Country.Oid = ?", ((Country)context).Oid)
            });

            builder.DataFormEditors().Property(p => p.States).ReplaceEditor(new GridEditorDefinition
            {
                EntityType = typeof(State),
                FilterMethod = context => CriteriaOperator.Parse("Country.Oid = ?", ((Country)context).Oid)
            })
            .HideLabel();
        }

        #endregion
    }
}
