using System.Linq;
using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using DevExpress.Xpo;
using TIG.TotalLink.Client.Core;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Client.Module.Admin.Provider;
using TIG.TotalLink.Client.Module.Admin.ViewModel.Document;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.DataModel.Core.Enum.Admin;
using TIG.TotalLink.Shared.Facade.Admin;

namespace TIG.TotalLink.Shared.DataModel.Admin
{
    [FacadeType(typeof(IAdminFacade))]
    [DisplayField("Name")]
    public partial class Document
    {
        #region Private Fields

        private static IDataModelTypeProvider _dataModelTypeProvider;
        private DocumentModelTypeViewModel _dataModel;
        private bool _documentDataModelChanging;

        #endregion


        #region Public Properties

        /// <summary>
        /// The data model that this document will be initialized with.
        /// </summary>
        [NonPersistent]
        [DoNotCopy]
        public DocumentModelTypeViewModel DataModel
        {
            get { return _dataModel; }
            set
            {
                SetProperty(ref _dataModel, value, () => DataModel, () =>
                {
                    // Abort if the DataModel was changed because the DataModelName changed
                    if (_documentDataModelChanging)
                        return;

                    // Set the DataModelName from the DataModel
                    _documentDataModelChanging = true;
                    DataModelName = (_dataModel != null ? _dataModel.Name : null);
                    _documentDataModelChanging = false;
                });
            }
        }

        #endregion


        #region Private Properties

        /// <summary>
        /// An instance of the DataModelTypeProvider.
        /// </summary>
        private static IDataModelTypeProvider DataModelTypeProvider
        {
            get { return _dataModelTypeProvider ?? (_dataModelTypeProvider = AutofacViewLocator.Default.Resolve<IDataModelTypeProvider>()); }
        }

        #endregion


        #region Private Methods

        /// <summary>
        /// Assigns the value of the DataModel property by looking up the data model specified in DataModelName.
        /// </summary>
        private void SetDataModelFromDataModelName()
        {
            // Abort if the DataModelName was changed because the DataModel changed
            if (_documentDataModelChanging)
                return;

            // Set the DataModel from the DataModelName
            _documentDataModelChanging = true;
            DataModel = DataModelTypeProvider.DocumentDataModels.FirstOrDefault(d => d.Name == DataModelName);
            _documentDataModelChanging = false;
        }

        #endregion


        #region Overrides

        protected override void OnLoaded()
        {
            base.OnLoaded();

            SetDataModelFromDataModelName();
        }

        protected override void OnChanged(string propertyName, object oldValue, object newValue)
        {
            base.OnChanged(propertyName, oldValue, newValue);

            switch (propertyName)
            {
                case "DataModelName":
                    SetDataModelFromDataModelName();
                    break;
            }
        }

        #endregion


        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<Document> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.Name)
                .ContainsProperty(p => p.View)
                .ContainsProperty(p => p.DataModel)
                .ContainsProperty(p => p.PanelGroups)
                .ContainsProperty(p => p.Panels);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.Name)
                    .ContainsProperty(p => p.View)
                    .ContainsProperty(p => p.DataModel)
                .EndGroup()
                .Group("Panel Groups")
                    .ContainsProperty(p => p.PanelGroups)
                .EndGroup()
                .Group("Panels")
                    .ContainsProperty(p => p.Panels);

            builder.Property(p => p.Name).Required();
            builder.Property(p => p.DataModelName).NotAutoGenerated();
            builder.Property(p => p.PanelGroups).AutoGenerated();
            builder.Property(p => p.Panels).AutoGenerated();
            builder.Property(p => p.DocumentDatas).NotAutoGenerated();
            builder.Property(p => p.DocumentActions).NotAutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<Document> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Name);

            builder.Property(p => p.DataModel).AllowNull();

            builder.DataFormEditors().Property(p => p.View)
                .ReplaceEditor(new OptionEditorDefinition(typeof(DocumentView)));

            builder.GridBaseColumnEditors().Property(p => p.View)
                .ReplaceEditor(new PopupOptionEditorDefinition(typeof(DocumentView)));

            var dataModelTypeProvider = DataModelTypeProvider;
            builder.Property(p => p.DataModel).ReplaceEditor(new LookUpEditorDefinition()
            {
                ItemsSource = (dataModelTypeProvider != null ? dataModelTypeProvider.DocumentDataModels : null),
                EntityType = typeof(DocumentModelTypeViewModel)
            });

            builder.DataFormEditors().Property(p => p.PanelGroups)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition()
                {
                    EntityType = typeof(PanelGroup),
                    FilterMethod = context => CriteriaOperator.Parse("Document.Oid = ?", ((Document)context).Oid)
                });

            builder.GridBaseColumnEditors().Property(p => p.PanelGroups)
                .ReplaceEditor(new PopupGridEditorDefinition()
                {
                    EntityType = typeof(PanelGroup),
                    FilterMethod = context => CriteriaOperator.Parse("Document.Oid = ?", ((Document)context).Oid)
                });

            builder.DataFormEditors().Property(p => p.Panels)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition()
                {
                    EntityType = typeof(Panel),
                    FilterMethod = context => CriteriaOperator.Parse("Document.Oid = ?", ((Document)context).Oid)
                });

            builder.GridBaseColumnEditors().Property(p => p.Panels)
                .ReplaceEditor(new PopupGridEditorDefinition()
                {
                    EntityType = typeof(Panel),
                    FilterMethod = context => CriteriaOperator.Parse("Document.Oid = ?", ((Document)context).Oid)
                });
        }

        #endregion
    }
}
