using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using DevExpress.Xpo;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Core.Enum;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Control;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.Facade.Admin;

namespace TIG.TotalLink.Shared.DataModel.Admin
{
    [FacadeType(typeof(IAdminFacade))]
    [DisplayField("Name")]
    public partial class PanelGroup
    {
        #region Private Fields

        private string _documentName;

        #endregion


        #region Public Properties

        /// <summary>
        /// The name of the parent Document.
        /// We can't assign the Document to a Panel until after the Panel is saved, but we want to display the parent Document so the user knows the panel is being added to the right place.
        /// So we display this property on the add dialog, instead of the main Document property.
        /// </summary>
        [NonPersistent]
        [DoNotCopy]
        public string DocumentName
        {
            get { return _documentName; }
            set { SetProperty(ref _documentName, value, () => DocumentName); }
        }

        #endregion


        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<PanelGroup> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.Name)
                .ContainsProperty(p => p.Document)
                .ContainsProperty(p => p.Panels);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.Name)
                    .ContainsProperty(p => p.DocumentName)
                    .ContainsProperty(p => p.Document)
                .EndGroup()
                .Group("Panels")
                    .ContainsProperty(p => p.Panels);

            builder.Property(p => p.Name).Required();
            builder.Property(p => p.Document).ReadOnly();
            builder.Property(p => p.DocumentName)
                .DisplayName("Document")
                .ReadOnly();

            builder.Property(p => p.Panels).AutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<PanelGroup> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Name);

            builder.GridBaseColumnEditors()
                .Property(p => p.DocumentName).Hidden().EndProperty();

            builder.DataFormEditors().Property(p => p.Panels)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition()
                {
                    EntityType = typeof(Panel),
                    FilterMethod = context => CriteriaOperator.Parse("PanelGroup.Oid = ?", ((PanelGroup)context).Oid)
                });

            builder.GridBaseColumnEditors().Property(p => p.Panels)
                .ReplaceEditor(new PopupGridEditorDefinition()
                {
                    EntityType = typeof(Panel),
                    FilterMethod = context => CriteriaOperator.Parse("PanelGroup.Oid = ?", ((PanelGroup)context).Oid)
                });
        }

        /// <summary>
        /// Builds metadata for form editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        /// <param name="dataLayoutControl">The DataLayoutControlEx that is displaying the object.</param>
        public void BuildFormMetadata(EditorMetadataBuilder<PanelGroup> builder, DataLayoutControlEx dataLayoutControl)
        {
            if (dataLayoutControl.EditMode == DetailEditMode.Add)
            {
                builder.DataFormEditors()
                    .Property(p => p.Document).Hidden().EndProperty();
            }
            else
            {
                builder.DataFormEditors()
                    .Property(p => p.DocumentName).Hidden().EndProperty();
            }
        }

        #endregion
    }
}
