using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.Facade.Admin;

namespace TIG.TotalLink.Shared.DataModel.Admin
{
    [FacadeType(typeof(IAdminFacade))]
    [DisplayField("Name")]
    public partial class RibbonGroup
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<RibbonGroup> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.Name)
                .ContainsProperty(p => p.ShowCaptionButton)
                .ContainsProperty(p => p.RibbonPage)
                .ContainsProperty(p => p.RibbonItems);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.Name)
                    .ContainsProperty(p => p.ShowCaptionButton)
                    .ContainsProperty(p => p.RibbonPage)
                .EndGroup()
                .Group("Items")
                    .ContainsProperty(p => p.RibbonItems);

            builder.Property(p => p.Name).Required();
            builder.Property(p => p.RibbonPage)
                .Required()
                .DisplayName("Page");

            builder.Property(p => p.RibbonItems)
                .DisplayName("Items")
                .AutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<RibbonGroup> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Name);

            var ribbonItemsEditor = new GridEditorDefinition()
            {
                EntityType = typeof(RibbonItem),
                FilterMethod = context => CriteriaOperator.Parse("RibbonGroup.Oid = ?", ((RibbonGroup)context).Oid)
            };
            builder.DataFormEditors().Property(p => p.RibbonItems)
                .ReplaceEditor(ribbonItemsEditor)
                .HideLabel();

            var ribbonItemsPopupEditor = new PopupGridEditorDefinition()
            {
                EntityType = typeof(RibbonItem),
                FilterMethod = context => CriteriaOperator.Parse("RibbonGroup.Oid = ?", ((RibbonGroup)context).Oid)
            };
            builder.GridBaseColumnEditors().Property(p => p.RibbonItems)
                .ReplaceEditor(ribbonItemsPopupEditor);
        }

        #endregion
    }
}
