using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Core.Enum;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Control;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.Facade.Admin;

namespace TIG.TotalLink.Shared.DataModel.Admin
{
    [FacadeType(typeof(IAdminFacade))]
    [DisplayField("Name")]
    public partial class RibbonCategory
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<RibbonCategory> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.Name)
                .ContainsProperty(p => p.IsDefault)
                .ContainsProperty(p => p.RibbonPages);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.Name)
                    .ContainsProperty(p => p.IsDefault)
                .EndGroup()
                .Group("Pages")
                    .ContainsProperty(p => p.RibbonPages);

            builder.Property(p => p.Name).Required();
            builder.Property(p => p.IsDefault).ReadOnly();

            builder.Property(p => p.RibbonPages)
                .DisplayName("Pages")
                .AutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<RibbonCategory> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Name);

            var ribbonPagesEditor = new GridEditorDefinition()
            {
                EntityType = typeof(RibbonPage),
                FilterMethod = context => CriteriaOperator.Parse("RibbonCategory.Oid = ?", ((RibbonCategory)context).Oid)
            };
            builder.DataFormEditors().Property(p => p.RibbonPages).ReplaceEditor(ribbonPagesEditor);

            var ribbonPagesPopupEditor = new PopupGridEditorDefinition()
            {
                EntityType = typeof(RibbonPage),
                FilterMethod = context => CriteriaOperator.Parse("RibbonCategory.Oid = ?", ((RibbonCategory)context).Oid)
            };
            builder.GridBaseColumnEditors().Property(p => p.RibbonPages)
                .ReplaceEditor(ribbonPagesPopupEditor)
                .HideLabel();
        }

        /// <summary>
        /// Builds metadata for form editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        /// <param name="dataLayoutControl">The DataLayoutControlEx that is displaying the object.</param>
        public void BuildFormMetadata(EditorMetadataBuilder<RibbonCategory> builder, DataLayoutControlEx dataLayoutControl)
        {
            if (dataLayoutControl.EditMode == DetailEditMode.Add)
            {
                builder.DataFormEditors()
                    .Property(p => p.IsDefault).Hidden().EndProperty();
            }
        }

        #endregion
    }
}
