using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.Facade.Admin;

namespace TIG.TotalLink.Shared.DataModel.Admin
{
    [FacadeType(typeof(IAdminFacade))]
    [DisplayField("Name")]
    public partial class RibbonPage
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<RibbonPage> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.Name)
                .ContainsProperty(p => p.RibbonCategory)
                .ContainsProperty(p => p.RibbonGroups);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.Name)
                    .ContainsProperty(p => p.RibbonCategory)
                .EndGroup()
                .Group("Groups")
                    .ContainsProperty(p => p.RibbonGroups);

            builder.Property(p => p.Name).Required();
            builder.Property(p => p.RibbonCategory)
                .Required()
                .DisplayName("Category");

            builder.Property(p => p.RibbonGroups)
                .DisplayName("Groups")
                .AutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<RibbonPage> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Name);

            var ribbonGroupsEditor = new GridEditorDefinition()
            {
                EntityType = typeof(RibbonGroup),
                FilterMethod = context => CriteriaOperator.Parse("RibbonPage.Oid = ?", ((RibbonPage)context).Oid)
            };
            builder.DataFormEditors().Property(p => p.RibbonGroups)
                .ReplaceEditor(ribbonGroupsEditor)
                .HideLabel();

            var ribbonGroupsPopupEditor = new PopupGridEditorDefinition()
            {
                EntityType = typeof(RibbonGroup),
                FilterMethod = context => CriteriaOperator.Parse("RibbonPage.Oid = ?", ((RibbonPage)context).Oid)
            };
            builder.GridBaseColumnEditors().Property(p => p.RibbonGroups)
                .ReplaceEditor(ribbonGroupsPopupEditor);
        }

        #endregion
    }
}
