using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.Facade.Admin;

namespace TIG.TotalLink.Shared.DataModel.Admin
{
    [FacadeType(typeof(IAdminFacade))]
    [DisplayField("Name")]
    [EntityFilter(typeof(Country), "Country.Oid IN (?)", "Country IN (?)")]
    public partial class State
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<State> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.Name)
                .ContainsProperty(p => p.Code)
                .ContainsProperty(p => p.Country);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.Name)
                    .ContainsProperty(p => p.Code)
                    .ContainsProperty(p => p.Country)
                .EndGroup()
                .Group("Postcodes")
                    .ContainsProperty(p => p.Postcodes);

            builder.Property(p => p.Name).Required();
            builder.Property(p => p.Country).Required();

            builder.Property(p => p.Postcodes).AutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<State> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Name);

            builder.GridBaseColumnEditors().Property(p => p.Postcodes).ReplaceEditor(new PopupGridEditorDefinition
            {
                EntityType = typeof(Postcode),
                FilterMethod = context => CriteriaOperator.Parse("State.Oid = ?", ((State)context).Oid)
            });

            builder.DataFormEditors().Property(p => p.Postcodes).ReplaceEditor(new GridEditorDefinition
            {
                EntityType = typeof(Postcode),
                FilterMethod = context => CriteriaOperator.Parse("State.Oid = ?", ((State)context).Oid)
            })
            .HideLabel();

            builder.DataFormEditors().Property(p => p.Postcodes).HideLabel();
        }

        #endregion
    }
}
