using System;
using System.Linq;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.DataModel.Core.Enum.Admin;
using TIG.TotalLink.Shared.Facade.Admin;

namespace TIG.TotalLink.Shared.DataModel.Admin
{
    [FacadeType(typeof(IAdminFacade))]
    [DisplayField("DisplayName")]
    public partial class User
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<User> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.DisplayName)
                .ContainsProperty(p => p.UserName)
                .ContainsProperty(p => p.UserType)
                .ContainsProperty(p => p.ActiveDirectoryId);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.DisplayName)
                    .ContainsProperty(p => p.UserName)
                    .ContainsProperty(p => p.UserType)
                    .ContainsProperty(p => p.ActiveDirectoryId);

            builder.Property(p => p.DisplayName).Required();
            builder.Property(p => p.UserName).Required();
            builder.Property(p => p.ActiveDirectoryId).ReadOnly();
            builder.Property(p => p.UserType).ReadOnly();
            builder.Property(p => p.Password).NotAutoGenerated();
            builder.Property(p => p.Salt).NotAutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<User> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.DisplayName);

            builder.Condition(context => context != null && context.UserType != UserType.TotalLink)
                .ContainsProperty(p => p.UserType)
                .AffectsPropertyReadOnly(p => p.UserName);

            builder.Property(p => p.DisplayName)
                .ColumnWidth(300)
                .AddValidation((value, context) =>
                {
                    // Only allow letters, digits, spaces and basic punctuation in the DisplayName
                    return ((string)value).Any(c => !char.IsLetterOrDigit(c) && !char.IsPunctuation(c) && c != ' ')
                        ? "DisplayName can only contain letters, digits, spaces and basic punctuation."
                        : null;
                });

            builder.Property(p => p.UserName)
                .ColumnWidth(300)
                .AddValidation((value, context) =>
                {
                    // Don't validate UserName for non TotalLink users because it can't be modified anyway
                    if (context != null && ((User)context).UserType != UserType.TotalLink)
                        return null;

                    // Only allow letters and digits in the UserName
                    return ((string)value).Any(c => !char.IsLetterOrDigit(c))
                        ? "UserName can only contain letters and digits."
                        : null;
                });

            builder.Property(p => p.UserType)
                .ReplaceEditor(new ComboEditorDefinition(typeof(UserType)));
        }

        #endregion
    }
}
