using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.Facade.Integration;

namespace TIG.TotalLink.Shared.DataModel.Integration
{
    [FacadeType(typeof(IIntegrationFacade))]
    [DisplayField("EntityName")]
    public partial class SyncEntity
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<SyncEntity> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.IsActive)
                .ContainsProperty(p => p.EntityName)
                .ContainsProperty(p => p.TableName)
                .ContainsProperty(p => p.PrimaryKey)
                .ContainsProperty(p => p.AgentPluginId)
                .ContainsProperty(p => p.ChangeTrackerPluginId)
                .ContainsProperty(p => p.Bundle)
                .ContainsProperty(p => p.PriorityInBundle);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.IsActive)
                    .ContainsProperty(p => p.EntityName)
                    .ContainsProperty(p => p.TableName)
                    .ContainsProperty(p => p.PrimaryKey)
                    .ContainsProperty(p => p.AgentPluginId)
                    .ContainsProperty(p => p.ChangeTrackerPluginId)
                    .ContainsProperty(p => p.Bundle)
                    .ContainsProperty(p => p.PriorityInBundle);

            builder.Property(p => p.PriorityInBundle).DisplayName("Priority");
            builder.Property(p => p.LastChangeTrackerVersionId).NotAutoGenerated();
            builder.Property(p => p.SourceEntityMaps).NotAutoGenerated();
            builder.Property(p => p.TargetEntityMaps).NotAutoGenerated();
            builder.Property(p => p.Instances).NotAutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<SyncEntity> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.EntityName);

            builder.Property(p => p.AgentPluginId)
                .ReplaceEditor(new TextEditorDefinition());

            builder.Property(p => p.ChangeTrackerPluginId)
                .ReplaceEditor(new TextEditorDefinition());
        }

        #endregion
    }
}
