using DevExpress.Data.Filtering;
using DevExpress.Mvvm.DataAnnotations;
using TIG.TotalLink.Client.Core.Attribute;
using TIG.TotalLink.Client.Editor.Builder;
using TIG.TotalLink.Client.Editor.Definition;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.Facade.Integration;

namespace TIG.TotalLink.Shared.DataModel.Integration
{
    [FacadeType(typeof(IIntegrationFacade))]
    [DisplayField("Name")]
    public partial class SyncEntityBundle
    {
        #region Metadata

        /// <summary>
        /// Builds metadata for properties.
        /// </summary>
        /// <param name="builder">The MetadataBuilder for defining property metadata.</param>
        public static void BuildMetadata(MetadataBuilder<SyncEntityBundle> builder)
        {
            builder.TableLayout().Group("")
                .ContainsProperty(p => p.IsActive)
                .ContainsProperty(p => p.Name)
                .ContainsProperty(p => p.Timeout)
                .ContainsProperty(p => p.Entities);

            builder.DataFormLayout().TabbedGroup("Tabs")
                .Group("General")
                    .ContainsProperty(p => p.IsActive)
                    .ContainsProperty(p => p.Name)
                    .ContainsProperty(p => p.Timeout)
                .EndGroup()
                .Group("Entities")
                    .ContainsProperty(p => p.Entities);

            builder.Property(p => p.InstanceBundles).NotAutoGenerated();
        }

        /// <summary>
        /// Builds metadata for editors.
        /// </summary>
        /// <param name="builder">The EditorMetadataBuilder for defining editor metadata.</param>
        public static void BuildEditorMetadata(EditorMetadataBuilder<SyncEntityBundle> builder)
        {
            builder.Sort()
                .ContainsProperty(p => p.Name);

            builder.Property(p => p.Timeout).AllowNull();

            builder.GridBaseColumnEditors().Property(p => p.Entities)
                .ReplaceEditor(new PopupGridEditorDefinition
                {
                    EntityType = typeof(SyncEntity),
                    FilterMethod = context => CriteriaOperator.Parse("Bundle.Oid=?", ((SyncEntityBundle)context).Oid)
                });

            builder.DataFormEditors().Property(p => p.Entities)
                .HideLabel()
                .ReplaceEditor(new GridEditorDefinition
                {
                    EntityType = typeof(SyncEntity),
                    FilterMethod = context => CriteriaOperator.Parse("Bundle.Oid=?", ((SyncEntityBundle)context).Oid),
                });
        }

        #endregion
    }
}
