using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Reflection;
using DevExpress.Entity.Model;
using DevExpress.Mvvm.Native;
using DevExpress.Mvvm.UI.Native.ViewGenerator;
using TIG.TotalLink.Client.Core.Helper;
using TIG.TotalLink.Shared.DataModel.Core;
using TIG.TotalLink.Shared.DataModel.Core.Attribute;
using TIG.TotalLink.Shared.DataModel.Core.Helper;

namespace TIG.TotalLink.Client.Core.Extension
{
    public static class TypeExtension
    {
        #region Public Methods

        /// <summary>
        /// Determines whether an instance of the current generic <see cref="T:System.Type"/> can be assigned from an instance of the specified Type.
        /// Note: This will not work with generic interfaces.
        /// </summary>
        /// <param name="type">The generic type to compare to.</param>
        /// <param name="compareType">The type to be compared.</param>
        /// <returns>True if compareType can be assigned to type.</returns>
        public static bool IsAssignableFromGeneric(this Type type, Type compareType)
        {
            while (!type.IsAssignableFrom(compareType))
            {
                if (compareType == null || compareType == typeof(object))
                {
                    return false;
                }

                if (compareType.IsGenericType && !compareType.IsGenericTypeDefinition)
                {
                    compareType = compareType.GetGenericTypeDefinition();
                }
                else
                {
                    compareType = compareType.BaseType;
                }
            }

            return true;
        }

        /// <summary>
        /// Returns a sorted list of visible properties that should be displayed as editors.
        /// Properties which have a related dynamic alias will be be replaced with an AliasedFieldMapping.
        /// </summary>
        /// <param name="type">The type to return properties for.</param>
        /// <param name="layoutType">The type of layout to collect properties for.</param>
        /// <returns>A list of IEdmPropertyInfo.</returns>
        public static IEnumerable<VisiblePropertyWrapper> GetVisibleAndAliasedProperties(this Type type, LayoutType layoutType = LayoutType.Default)
        {
            // Get a list of visible properties for the type
            var visibleProperties = GetVisibleProperties(type, layoutType);
            if (visibleProperties == null)
                return null;

            // Get a list of all AliasedFieldMappings for the type
            var aliasedFieldMappings = DataModelHelper.AliasedFieldMappings.Where(a => a.OwnerType == type).ToList();

            // Build and return a list of VisiblePropertyWrappers
            return visibleProperties.Select(p =>
            {
                return new VisiblePropertyWrapper(type, p, aliasedFieldMappings.FirstOrDefault(a => a.SourceFieldName == p.Name));
            }).ToList();
        }

        /// <summary>
        /// Returns a sorted list of visible properties that should be displayed as editors.
        /// </summary>
        /// <param name="type">The type to return properties for.</param>
        /// <param name="layoutType">The type of layout to collect properties for.</param>
        /// <returns>A list of IEdmPropertyInfo.</returns>
        public static IEnumerable<IEdmPropertyInfo> GetVisibleProperties(this Type type, LayoutType layoutType = LayoutType.Default)
        {
            // Get all supported properties
            var properties = GetSupportedProperties(type);
            if (properties == null)
                return null;

            // Sort and filter the list to only visible properties, and return it
            return EditorsSource.GetFilteredAndSortedProperties(properties, false, false, layoutType);
        }

        /// <summary>
        /// Returns a list of all properties that should be displayed as editors.
        /// Properties which have a related dynamic alias will be be replaced with an AliasedFieldMapping.
        /// </summary>
        /// <param name="type">The type to return properties for.</param>
        /// <param name="allowNotAutoGenerated">Indicates if properties should be returned for NotAutoGenerated classes.</param>
        /// <returns>A list of IEdmPropertyInfo.</returns>
        public static IEnumerable<VisiblePropertyWrapper> GetSupportedAndAliasedProperties(this Type type, bool allowNotAutoGenerated = false)
        {
            // Get a list of supported properties for the type
            var supportedProperties = GetSupportedProperties(type, allowNotAutoGenerated);
            if (supportedProperties == null)
                return null;

            // Get a list of all AliasedFieldMappings for the type
            var aliasedFieldMappings = DataModelHelper.AliasedFieldMappings.Where(a => a.OwnerType == type).ToList();

            // Build and return a list of VisiblePropertyWrappers
            return supportedProperties.Select(p =>
            {
                return new VisiblePropertyWrapper(type, p, aliasedFieldMappings.FirstOrDefault(a => a.SourceFieldName == p.Name));
            }).ToList();
        }

        /// <summary>
        /// Returns a list of all properties that should be displayed as editors.
        /// </summary>
        /// <param name="type">The type to return properties for.</param>
        /// <param name="allowNotAutoGenerated">Indicates if properties should be returned for NotAutoGenerated classes.</param>
        /// <returns>A list of IEdmPropertyInfo.</returns>
        public static IEnumerable<IEdmPropertyInfo> GetSupportedProperties(this Type type, bool allowNotAutoGenerated = false)
        {
            // If the class is marked as NotAutoGenerated, return null
            if (!allowNotAutoGenerated && type.GetCustomAttribute<NotAutoGeneratedAttribute>(false) != null)
                return null;

            // Get private properties with the DisplayAttribute where AutoGenerateField = true
            var privateProperties = type.GetProperties(BindingFlags.Instance | BindingFlags.NonPublic)
                .Where(p =>
                {
                    var displayAttribute = p.GetCustomAttribute<DisplayAttribute>(true);
                    return displayAttribute != null && displayAttribute.AutoGenerateField;
                })
                .Select(p => new PropertyDescriptorEx(p) as PropertyDescriptor);
            var privateEntityProperties = new ReflectionEntityProperties(privateProperties, type, true) as IEntityProperties;

            // Get public properties
            IEntityTypeInfo typeInfo = new ReflectionEntityTypeInfo(type, true);

            // Get a combined list of all properties
            var supportedProperties = typeInfo.AllProperties.Union(privateEntityProperties.AllProperties);

            // If the type inherits from DataObjectBase, exclude all properties in the baseObjectProperties list
            if (typeof(DataObjectBase).IsAssignableFrom(type))
                supportedProperties = supportedProperties.Where(p => !DataModelHelper.NonSerializableDataObjectBaseProperties.Contains(p.Name));

            // Return the list of supported properties
            return supportedProperties.ToList();
        }

        /// <summary>
        /// Gets a nullable version of this type.
        /// </summary>
        /// <param name="type">The type to get the nullable version of.</param>
        /// <returns>A nullable type.</returns>
        public static Type GetNullableType(this Type type)
        {
            // There is no Nullable version of void
            if (type == typeof(void))
                return null;

            // If the type is not a value type then return the type unchanged, otherwise return a nullable version
            return !type.IsValueType || (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(Nullable<>))
                ? type
                : typeof(Nullable<>).MakeGenericType(type);
        }

        #endregion
    }
}
